// Generated by pnpm kyberion generate artifact-kinds. Do not edit.

export interface StandardIntentCatalog {
  $schema?: string;
  version: string;
  ux_contract?: string;
  notes?: string[];
  intents: Intent[];
}
export interface Intent {
  id: string;
  category:
    | 'outcome_execution'
    | 'environment_setup'
    | 'actuator_management'
    | 'llm_reasoning_setup'
    | 'conversation_orchestration'
    | 'knowledge_lifecycle'
    | 'system_observability'
    | 'mission_process'
    | 'governance_control';
  legacy_category: string;
  exposed_to_surface: boolean;
  target:
    | 'outcome'
    | 'environment'
    | 'actuator'
    | 'llm'
    | 'knowledge'
    | 'system_state'
    | 'mission_process'
    | 'agent_team'
    | 'external_service'
    | 'conversation';
  action:
    | 'create'
    | 'change'
    | 'inspect'
    | 'diagnose'
    | 'prepare'
    | 'verify'
    | 'activate'
    | 'query'
    | 'distill'
    | 'organize'
    | 'compose'
    | 'delegate'
    | 'execute'
    | 'review'
    | 'promote';
  object: string;
  execution_shape:
    | 'direct_reply'
    | 'task_session'
    | 'mission'
    | 'project_bootstrap'
    | 'browser_session'
    | 'pipeline'
    | 'actuator_action';
  mission_class:
    | 'product_delivery'
    | 'code_change'
    | 'research_and_absorption'
    | 'content_and_media'
    | 'operations_and_release'
    | 'environment_and_recovery'
    | 'decision_support'
    | 'customer_engagement'
    | 'platform_onboarding'
    | 'finance_and_accounting'
    | 'people_and_talent'
    | 'legal_and_compliance'
    | 'strategy_and_governance'
    | 'procurement_and_supply'
    | 'long_running_job';
  risk_profile: 'low' | 'review_required' | 'approval_required' | 'high_stakes';
  description: string;
  surface_examples?: string[];
  plan_outline?: string[];
  outcome_ids: string[];
  specialist_id?: string;
  execution_profile_id?: string;
  trigger_keywords: string[];
  intake_requirements?: string[];
  resolution?: Resolution;
  pipeline?: PipelineStep[];
}
export interface Resolution {
  shape?: string;
  task_kind?: string;
  result_shape?: string;
}
export interface PipelineStep {
  op: string;
  params?: {
    [k: string]: unknown;
  };
}

export type StandardIntentDefinition = StandardIntentCatalog['intents'][number];
export type StandardIntentCategory = StandardIntentDefinition['category'];
export type StandardIntentTarget = StandardIntentDefinition['target'];
export type StandardIntentAction = StandardIntentDefinition['action'];
export type StandardIntentExecutionShape = StandardIntentDefinition['execution_shape'];
export type StandardIntentMissionClass = StandardIntentDefinition['mission_class'];
export type StandardIntentRiskProfile = StandardIntentDefinition['risk_profile'];
export type StandardIntentResolution = NonNullable<StandardIntentDefinition['resolution']>;
export type StandardIntentPipelineStep = NonNullable<StandardIntentDefinition['pipeline']>[number];
