import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack(spacing: 12) {
            Text("{{APP_NAME}}")
                .font(.largeTitle)
            Text("Generated by Kyberion (E2E-05 scaffold)")
                .font(.footnote)
                .foregroundStyle(.secondary)
        }
        .padding()
    }
}

#Preview {
    ContentView()
}
