import { describe, expect, it } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { safeReadFile } from '@agent/core/secure-io';

const rootDir = process.cwd();

function read(relPath: string): string {
  return safeReadFile(path.join(rootDir, relPath), { encoding: 'utf8' }) as string;
}

describe('mission orchestration dashboard contract', () => {
  it('shows mission orchestration state in the sovereign dashboard', () => {
    const dashboard = read('scripts/sovereign_dashboard.ts');
    expect(dashboard).toContain('MISSION ORCHESTRATION');
    expect(dashboard).toContain('OWNER SUMMARIES');
    expect(dashboard).toContain('RUNTIME LEASE DOCTOR');
    expect(dashboard).toContain('SURFACE OUTBOX');
    expect(dashboard).toContain('PLAN READY');
    expect(dashboard).toContain('NEXT_TASKS.json');
  });

  it('shows mission intelligence in Chronos default view', () => {
    const page = read('presence/displays/chronos-mirror-v2/src/app/page.tsx');
    const component = read('presence/displays/chronos-mirror-v2/src/components/MissionIntelligence.tsx');
    const route = read('presence/displays/chronos-mirror-v2/src/app/api/intelligence/route.ts');
    const streamRoute = read('presence/displays/chronos-mirror-v2/src/app/api/intelligence/stream/route.ts');
    const messageFeed = read('presence/displays/chronos-mirror-v2/src/lib/agent-message-feed.ts');
    const agentRoute = read('presence/displays/chronos-mirror-v2/src/app/api/agent/route.ts');

    expect(page).toContain('MissionIntelligence');
    expect(page).toContain('Jump to section');
    expect(page).toContain('mission-control-plane');
    expect(page).toContain('runtime-lease-doctor');
    expect(page).toContain('recent-surface-outbox');
    expect(component).toContain('Mission Control');
    expect(component).toContain('control summary');
    expect(component).toContain('requested by');
    expect(component).toContain('Recent Control Actions');
    expect(component).toContain('show details');
    expect(component).toContain('jump to target');
    expect(component).toContain('show latest action');
    expect(component).toContain('retry latest action');
    expect(component).toContain('operator guidance');
    expect(component).toContain('next valid actions');
    expect(component).toContain('safe actions');
    expect(component).toContain('risky actions');
    expect(component).toContain('approval required');
    expect(component).toContain('Orchestration Audit');
    expect(component).toContain('Browser Session Oversight');
    expect(component).toContain('recent browser trail');
    expect(component).toContain('close session');
    expect(component).toContain('restart session');
    expect(component).toContain('strict or hint mode');
    expect(component).toContain('Agent Traffic');
    expect(component).toContain('Selected Mission Thread');
    expect(component).toContain('A2A Handoff Trail');
    expect(component).toContain('all missions');
    expect(component).toContain('a2a handoff');
    expect(component).toContain('pin mission thread');
    expect(component).toContain('mission pinned');
    expect(component).toContain('url.searchParams.set("mission", selectedMissionId)');
    expect(component).toContain('const mission = params.get("mission")');
    expect(component).toContain('EventSource("/api/intelligence/stream")');
    expect(component).toContain('No mission-scoped agent messages observed yet.');
    expect(component).toContain('Owner Summaries');
    expect(component).toContain('Delivery Exceptions');
    expect(component).toContain('clear outbox');
    expect(component).toContain('Surface Control');
    expect(component).toContain('mission_controller');
    expect(component).toContain('surface_runtime');
    expect(component).toContain('accessRole');
    expect(component).toContain('localhost auto-admin');
    expect(component).toContain('Runtime Governance');
    expect(component).toContain('cleanup_runtime_lease');
    expect(component).toContain('restart_runtime_lease');
    expect(route).toContain('activeMissions');
    expect(route).toContain('controlSummary');
    expect(route).toContain('controlTone');
    expect(route).toContain('controlRequestedBy');
    expect(route).toContain('pendingMissionTargets');
    expect(route).toContain('pendingSurfaceTargets');
    expect(route).toContain(' pending');
    expect(route).toContain('execution ready');
    expect(route).toContain('planning pending');
    expect(route).toContain('surfaces');
    expect(route).toContain('controlSummary');
    expect(route).toContain('controlTone');
    expect(route).toContain('needs attention');
    expect(route).toContain('stable');
    expect(route).toContain('stopped');
    expect(route).toContain('recentEvents');
    expect(route).toContain('agentMessages');
    expect(route).toContain('a2aHandoffs');
    expect(route).toContain('collectAgentMessages');
    expect(route).toContain('collectA2AHandoffs');
    expect(messageFeed).toContain('a2a_message_routed');
    expect(messageFeed).toContain('handoff from');
    expect(messageFeed).toContain('prompt');
    expect(messageFeed).toContain('response');
    expect(streamRoute).toContain('text/event-stream');
    expect(streamRoute).toContain('collectAgentMessages');
    expect(streamRoute).toContain('collectA2AHandoffs');
    expect(streamRoute).toContain('collectRecentEvents');
    expect(streamRoute).toContain('collectControlActions');
    expect(streamRoute).toContain('collectControlActionDetails');
    expect(streamRoute).toContain('collectOwnerSummaries');
    expect(streamRoute).toContain('collectBrowserSessions');
    expect(streamRoute).toContain('buildRuntimeTopology');
    expect(streamRoute).toContain('listAgentRuntimeSnapshots');
    expect(streamRoute).toContain('runtimeTopology');
    expect(streamRoute).toContain('runtimeSummary');
    expect(streamRoute).toContain('retry: 3000');
    expect(route).toContain('controlActionCatalog');
    expect(route).toContain('controlActionAvailability');
    expect(route).toContain('approvalRequired');
    expect(route).toContain('disabledReason');
    expect(route).toContain('Mission is already active.');
    expect(route).toContain('Surface is already running.');
    expect(route).toContain('Surface is already stopped.');
    expect(route).toContain('finish');
    expect(route).toContain('refresh team');
    expect(route).toContain('reconcile surfaces');
    expect(route).toContain('controlActions');
    expect(route).toContain('controlActionDetails');
    expect(route).toContain('ownerSummaries');
    expect(route).toContain('browserSessions');
    expect(route).toContain('close_browser_session');
    expect(route).toContain('restart_browser_session');
    expect(route).toContain('surfaceOutbox');
    expect(route).toContain('recentSurfaceOutbox');
    expect(route).toContain('clear_surface_outbox');
    expect(route).toContain('mission_control');
    expect(route).toContain('surface_control');
    expect(route).toContain('mission_control_requested');
    expect(route).toContain('surface_control_requested');
    expect(route).toContain('startMissionOrchestrationWorker');
    expect(route).toContain('chronos_localadmin');
    expect(route).toContain('roleToMissionRole');
    expect(route).toContain('surface_outbox_cleared');
    expect(route).toContain('runtimeLeases');
    expect(route).toContain('runtimeDoctor');
    expect(route).toContain('MISSION_RUNTIME_REMEDIATION');
    expect(route).toContain('runtime-remediation');
    expect(route).toContain('runtime_lease_remediation_applied');
    expect(route).toContain('cleanup_runtime_lease');
    expect(route).toContain('restart_runtime_lease');
    expect(route).toContain('collectControlActionCatalog');
    expect(route).toContain('collectControlActionAvailability');
    expect(agentRoute).toContain('RUN_PIPELINE_PATTERN');
    expect(agentRoute).toContain('dist/scripts/run_pipeline.js');
    expect(agentRoute).toContain('import("@agent/core/core")');
    expect(route).toContain('from "@agent/core"');
    expect(route).toContain('emitMissionOrchestrationObservation');
  });

  it('keeps core public entrypoint free of presence-actuator runtime dependency', () => {
    const coreIndex = read('libs/core/index.ts');

    expect(coreIndex).not.toContain('presenceAction');
    expect(coreIndex).not.toContain('presence-actuator');

    const coreDistPath = path.join(process.cwd(), 'libs/core/dist/index.js');
    if (fs.existsSync(coreDistPath)) {
      const coreDistIndex = fs.readFileSync(coreDistPath, 'utf8');
      expect(coreDistIndex).not.toContain('presence-actuator');
      expect(coreDistIndex).not.toContain('presenceAction');
    }
  });
});
