name: { { APP_NAME } }
options:
  bundleIdPrefix: { { BUNDLE_ID } }
  deploymentTarget:
    iOS: '16.0'
targets:
  { { APP_NAME } }:
    type: application
    platform: iOS
    sources: [Sources]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: { { BUNDLE_ID } }
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        CODE_SIGNING_ALLOWED: NO
