// Generated by pnpm kyberion generate artifact-kinds. Do not edit.

export type IntentLabelRule = {
  id?: string;
  match: RoutingMatch;
  label?: string;
  label_from?: 'intentId' | 'taskType' | 'queryType';
} & IntentLabelRule1;
export type IntentLabelRule1 = {
  [k: string]: unknown;
};

export interface WorkPolicyFile {
  $schema?: string;
  version: string;
  specialist_routing: SpecialistRouting;
  profile_routing: ProfileRouting;
  design_rules: DesignRules;
  agent_routing?: AgentRouting;
}
export interface SpecialistRouting {
  rules: {
    id?: string;
    match: RoutingMatch;
    specialist_id: string;
  }[];
  fallback_specialist_id: string;
}
export interface RoutingMatch {
  intent_ids?: string[];
  task_types?: string[];
  query_types?: string[];
  shapes?: string[];
  catalog_shapes?: string[];
}
export interface ProfileRouting {
  execution_boundary_rules?: ProfileRule[];
  runtime_design_rules?: ProfileRule[];
  defaults: {
    execution_boundary_profile_id: string;
    runtime_design_profile_id: string;
  };
}
export interface ProfileRule {
  id?: string;
  match: RoutingMatch;
  profile_id: string;
}
export interface DesignRules {
  process_checklist_rules: ChecklistRule[];
  execution_shape_rules: ExecutionShapeRule[];
  intent_label_rules: IntentLabelRule[];
  defaults: {
    fallback_intent_label: string;
  };
}
export interface ChecklistRule {
  id?: string;
  match: RoutingMatch;
  items: string[];
}
export interface ExecutionShapeRule {
  id?: string;
  match: RoutingMatch;
  shape: 'direct_reply' | 'task_session' | 'mission' | 'project_bootstrap';
}
export interface AgentRouting {
  mode_rules: AgentRoutingRule[];
}
export interface AgentRoutingRule {
  id?: string;
  match: RoutingMatch;
  mode: 'prompt' | 'subagent' | 'coordination';
  scope?: 'single_artifact' | 'multi_artifact' | 'stateful_flow' | 'boundary_crossing';
  autonomy?: 'low' | 'medium' | 'high';
  boundary_crossing?: boolean;
  fanout?: 'none' | 'parallel' | 'review' | 'cross_critique';
  owner: string;
  delegates?: string[];
  artifact_count?: number;
  stop_condition?: string;
  rationale?: string;
}
