/**
 * pad-ui.ts — PA-03 shared UI foundation for the localhost pads
 * (PADS_A2UI_AND_AVATAR_PLAN_2026-09-23 §4).
 *
 * The pads are raw `node:http` servers. This module gives each of them the
 * same A2UI kit the other surfaces use, without a hand-maintained allow-list
 * per pad:
 *
 *   GET /shared-ui/<module>.js            -> libs/shared-ui/vanilla/<module>.js
 *        (any file directly in that directory whose name is `[a-z0-9-]+.js`)
 *   GET /shared-ui/messages/<locale>.json -> { ok, locale, messages }  (`ui` bundle)
 *   GET /design-tokens.css                -> scripts/lib/pad-ui/design-tokens.css (--kb-ui-* only)
 *   GET /kyberion-ui.css                  -> scripts/lib/pad-ui/kyberion-ui.css
 *   GET /pad-ui/pad-client.js             -> scripts/lib/pad-ui/pad-client.js
 *
 * Both stylesheets are generated by `scripts/generate_design_tokens.ts`; the
 * design-token drift gates in `check_catalog_integrity.ts` /
 * `check_ui_ux_governance.ts` know them.
 *
 * Page language (`resolvePadLocale`): `?lang=` → the shared `kb-ui-locale`
 * cookie → `Accept-Language` → `resolveLocale()` (identity / env). Theme is a
 * browser-only preference (`kyberion.ui.theme`), applied by an inline
 * pre-paint script in `renderPadPage`.
 */
import type { IncomingMessage, ServerResponse } from 'node:http';
import * as path from 'node:path';
import { getUiMessageBundle } from '@agent/core';
import { pathResolver } from '@agent/core/path-resolver';
import { safeExistsSync, safeLstat, safeReadFile } from '@agent/core/secure-io';
import { resolveLocale } from '@agent/core/locale';
import {
  normalizeLocale,
  SUPPORTED_LOCALES,
  type SupportedLocale,
} from '@agent/core/locale-normalize';
import { t as catalogT, type VocabularyKey } from '@agent/core/t';
import { resolveVocabularyEntry } from '@agent/core/vocabulary-catalog';
import type { MessageParams } from '@agent/core/message-format';

/** Shared server-side mirror of the language choice (same as computer-surface). */
export const PAD_LOCALE_COOKIE = 'kb-ui-locale';
/** Locales a cookie or `Accept-Language` may select; `?lang=` also accepts any supported one. */
export const PAD_PAGE_LOCALES = ['en', 'ja'] as const satisfies readonly SupportedLocale[];
export const PAD_THEME_STORAGE_KEY = 'kyberion.ui.theme';
export const PAD_LOCALE_STORAGE_KEY = 'kyberion.ui.locale';

export const PAD_UI_VANILLA_DIR = 'libs/shared-ui/vanilla';
export const PAD_UI_ASSET_DIR = 'scripts/lib/pad-ui';
export const PAD_UI_TOKENS_CSS = `${PAD_UI_ASSET_DIR}/design-tokens.css`;
export const PAD_UI_STYLESHEET = `${PAD_UI_ASSET_DIR}/kyberion-ui.css`;
export const PAD_UI_CLIENT_SCRIPT = `${PAD_UI_ASSET_DIR}/pad-client.js`;

export const PAD_UI_ROUTES = Object.freeze({
  renderer: '/shared-ui/kyberion-ui.js',
  modulePrefix: '/shared-ui/',
  messagesPrefix: '/shared-ui/messages/',
  tokens: '/design-tokens.css',
  stylesheet: '/kyberion-ui.css',
  client: '/pad-ui/pad-client.js',
});

/** Vocabulary the shell and `pad-client.js` always need (beyond the `ui` bundle). */
export const PAD_SHELL_TEXT_KEYS = [
  'local_pads:badge',
  'local_pads:noscript_notice',
] as const satisfies readonly VocabularyKey[];

const JS_TYPE = 'text/javascript; charset=utf-8';
const CSS_TYPE = 'text/css; charset=utf-8';
const JSON_TYPE = 'application/json; charset=utf-8';
const MODULE_FILE = /^[a-z0-9-]+\.js$/;
const LOCALE_FILE = /^([a-z]{2,3}(?:-[a-z0-9]{2,8})?)\.json$/;
const FIXED_ASSETS: Readonly<Record<string, { file: string; type: string }>> = Object.freeze({
  [PAD_UI_ROUTES.tokens]: { file: PAD_UI_TOKENS_CSS, type: CSS_TYPE },
  [PAD_UI_ROUTES.stylesheet]: { file: PAD_UI_STYLESHEET, type: CSS_TYPE },
  [PAD_UI_ROUTES.client]: { file: PAD_UI_CLIENT_SCRIPT, type: JS_TYPE },
});

// ---------------------------------------------------------------------------
// Asset serving
// ---------------------------------------------------------------------------

type PadRequest = Pick<IncomingMessage, 'method' | 'url' | 'headers'>;

/** The request path without the query string, or null for a missing / non-path URL. */
function requestPath(req: Pick<IncomingMessage, 'url'>): string | null {
  const url = typeof req.url === 'string' ? req.url : '';
  if (!url.startsWith('/')) return null;
  const end = url.search(/[?#]/);
  return end === -1 ? url : url.slice(0, end);
}

function isOwnedPath(pathname: string): boolean {
  return (
    pathname.startsWith(PAD_UI_ROUTES.modulePrefix) ||
    pathname.startsWith('/pad-ui/') ||
    Object.prototype.hasOwnProperty.call(FIXED_ASSETS, pathname)
  );
}

/**
 * The repository-relative source of a `/shared-ui/<module>.js` request, or
 * null. The raw path must already be canonical (`[a-z0-9-]+.js`, no
 * percent-encoding), so `..`, `%2e%2e`, `%2F`, uppercase, `x.test.js`,
 * `.d.ts` and subdirectories never match; after decoding, the resolved path
 * must still sit directly in the vanilla directory and be a regular file
 * (not a symlink).
 */
export function resolveSharedUiModule(pathname: string): string | null {
  if (!pathname.startsWith(PAD_UI_ROUTES.modulePrefix)) return null;
  const raw = pathname.slice(PAD_UI_ROUTES.modulePrefix.length);
  if (!MODULE_FILE.test(raw)) return null;
  let decoded: string;
  try {
    decoded = decodeURIComponent(raw);
  } catch {
    return null;
  }
  if (!MODULE_FILE.test(decoded)) return null;
  const dir = pathResolver.rootResolve(PAD_UI_VANILLA_DIR);
  const resolved = path.resolve(dir, decoded);
  if (path.dirname(resolved) !== dir) return null;
  if (!safeExistsSync(resolved) || !safeLstat(resolved).isFile()) return null;
  return `${PAD_UI_VANILLA_DIR}/${decoded}`;
}

/** `/shared-ui/messages/<locale>.json` -> the locale when it is exactly a supported one. */
export function parsePadMessagesPath(pathname: string): SupportedLocale | null {
  if (!pathname.startsWith(PAD_UI_ROUTES.messagesPrefix)) return null;
  const match = LOCALE_FILE.exec(pathname.slice(PAD_UI_ROUTES.messagesPrefix.length));
  if (!match) return null;
  return (SUPPORTED_LOCALES as readonly string[]).includes(match[1])
    ? (match[1] as SupportedLocale)
    : null;
}

function baseHeaders(type: string): Record<string, string> {
  return {
    'Content-Type': type,
    'Cache-Control': 'no-store',
    'X-Content-Type-Options': 'nosniff',
  };
}

function sendNotFound(res: ServerResponse): void {
  res.writeHead(404, baseHeaders('text/plain; charset=utf-8'));
  res.end('not found');
}

function sendFile(res: ServerResponse, relativeFile: string, type: string): void {
  const body = safeReadFile(pathResolver.rootResolve(relativeFile), { encoding: null }) as Buffer;
  res.writeHead(200, { ...baseHeaders(type), 'Content-Length': String(body.byteLength) });
  res.end(body);
}

/**
 * Serve the shared UI assets for a pad. Returns true when the request was
 * one of the pad-ui routes (answered, possibly with 404 / 405), false when
 * the pad should handle it itself. Call it first in the pad's request
 * handler.
 */
export function handlePadUiAsset(req: PadRequest, res: ServerResponse): boolean {
  const pathname = requestPath(req);
  if (!pathname || !isOwnedPath(pathname)) return false;
  if (req.method !== 'GET') {
    res.writeHead(405, { ...baseHeaders('text/plain; charset=utf-8'), Allow: 'GET' });
    res.end('method not allowed');
    return true;
  }
  try {
    const fixed = Object.prototype.hasOwnProperty.call(FIXED_ASSETS, pathname)
      ? FIXED_ASSETS[pathname]
      : undefined;
    if (fixed) {
      sendFile(res, fixed.file, fixed.type);
      return true;
    }
    if (pathname.startsWith(PAD_UI_ROUTES.messagesPrefix)) {
      const locale = parsePadMessagesPath(pathname);
      if (!locale) {
        sendNotFound(res);
        return true;
      }
      res.writeHead(200, baseHeaders(JSON_TYPE));
      res.end(JSON.stringify({ ok: true, ...getUiMessageBundle(locale) }));
      return true;
    }
    const moduleFile = resolveSharedUiModule(pathname);
    if (!moduleFile) {
      sendNotFound(res);
      return true;
    }
    sendFile(res, moduleFile, JS_TYPE);
  } catch {
    if (!res.headersSent) res.writeHead(500, baseHeaders('text/plain; charset=utf-8'));
    res.end('asset unavailable');
  }
  return true;
}

// ---------------------------------------------------------------------------
// Locale and vocabulary
// ---------------------------------------------------------------------------

function headerText(value: string | string[] | undefined, separator: string): string {
  return Array.isArray(value) ? value.join(separator) : value || '';
}

function pageLocale(value: unknown): SupportedLocale | null {
  const locale = normalizeLocale(value);
  return locale && (PAD_PAGE_LOCALES as readonly string[]).includes(locale) ? locale : null;
}

/** The `kb-ui-locale` cookie value when it names a page locale. */
export function padLocaleFromCookie(
  cookieHeader: string | string[] | undefined
): SupportedLocale | null {
  for (const part of headerText(cookieHeader, ';').split(';')) {
    const eq = part.indexOf('=');
    if (eq === -1 || part.slice(0, eq).trim() !== PAD_LOCALE_COOKIE) continue;
    return pageLocale(part.slice(eq + 1).trim());
  }
  return null;
}

/** The highest-weighted `Accept-Language` tag that names a page locale. */
export function padLocaleFromAcceptLanguage(
  header: string | string[] | undefined
): SupportedLocale | null {
  const tags = headerText(header, ',')
    .split(',')
    .map((part, index) => {
      const [tag, ...params] = part.split(';').map((piece) => piece.trim());
      const q = params.find((param) => param.startsWith('q='));
      const weight = q ? Number(q.slice(2)) : 1;
      return { tag, weight: Number.isFinite(weight) ? weight : 0, index };
    })
    .filter((entry) => entry.tag && entry.tag !== '*' && entry.weight > 0)
    .sort((a, b) => b.weight - a.weight || a.index - b.index);
  for (const { tag } of tags) {
    const locale = pageLocale(tag);
    if (locale) return locale;
  }
  return null;
}

/**
 * The page language for one request: `?lang=` (any supported locale,
 * including the `qps-ploc` pseudo-locale for testing) → the `kb-ui-locale`
 * cookie → `Accept-Language` (en / ja) → `resolveLocale()`.
 */
export function resolvePadLocale(
  req: Pick<IncomingMessage, 'url' | 'headers'>,
  fallback: () => SupportedLocale = () => resolveLocale()
): SupportedLocale {
  const url = typeof req.url === 'string' ? req.url : '';
  const queryStart = url.indexOf('?');
  if (queryStart !== -1) {
    const query = new URLSearchParams(url.slice(queryStart + 1).split('#')[0]);
    const explicit = normalizeLocale(query.get('lang'));
    if (explicit) return explicit;
  }
  return (
    padLocaleFromCookie(req.headers?.cookie) ??
    padLocaleFromAcceptLanguage(req.headers?.['accept-language']) ??
    fallback()
  );
}

export type PadTranslator = (key: VocabularyKey, params?: MessageParams) => string;

/** A catalog translator bound to `locale` (never the process default). */
export function padT(locale: SupportedLocale): PadTranslator {
  return (key, params) => catalogT(key, params, locale);
}

/** Raw catalog text (placeholders kept) for the browser; the key itself when missing. */
export function padTexts(
  keys: readonly VocabularyKey[],
  locale: SupportedLocale
): Record<string, string> {
  return Object.fromEntries(
    keys.map((key) => {
      const resolved = resolveVocabularyEntry(key);
      const text = resolved?.entry[locale] ?? resolved?.entry.en;
      return [key, typeof text === 'string' && text ? text : key];
    })
  );
}

// ---------------------------------------------------------------------------
// Page shell
// ---------------------------------------------------------------------------

export function escapePadHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** JSON safe inside `<script type="application/json">` (no `</script`, `<!--`, or line separators). */
export function toPadInlineJson(value: unknown): string {
  return JSON.stringify(value ?? null)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

/** Inline script source that cannot close its element early. */
function inlineScriptSource(source: string): string {
  return source.replace(/<\/(script)/gi, '<\\/$1').replace(/<\!--/g, '<\\!--');
}

/**
 * Pre-paint theme: the shared stored choice (`kyberion.ui.theme`) as
 * `data-theme`; otherwise no attribute, so the generated tokens follow
 * `prefers-color-scheme`. Storage can be unavailable — never throw.
 */
export const PAD_THEME_PREPAINT_SCRIPT = `(function(){var r=document.documentElement,v=null;try{v=window.localStorage.getItem(${JSON.stringify(PAD_THEME_STORAGE_KEY)});}catch(e){}if(v==='light'||v==='dark')r.setAttribute('data-theme',v);else r.removeAttribute('data-theme');})();`;

export interface PadHeaderOptions {
  locale: SupportedLocale;
  /** Plain text (escaped here). */
  title: string;
  /** Plain text (escaped here). */
  subtitle?: string;
  /** Trusted markup placed before the display controls. */
  actionsHtml?: string;
}

/**
 * The common pad header: title + "Local pad" badge, optional subtitle, and
 * an actions slot ending in the `[data-pad-display-controls]` host that
 * `pad-client.js` fills with `ui:display-controls`.
 */
export function renderPadHeader(options: PadHeaderOptions): string {
  const t = padT(options.locale);
  const subtitle = options.subtitle
    ? `<p class="kb-page-header__subtitle">${escapePadHtml(options.subtitle)}</p>`
    : '';
  return [
    '<header class="kb-page-header">',
    '<div class="kb-page-header__titles">',
    `<h1 class="kb-page-header__title">${escapePadHtml(options.title)} <span class="kb-badge" data-role="local-pad">${escapePadHtml(t('local_pads:badge'))}</span></h1>`,
    subtitle,
    '</div>',
    '<div class="kb-page-header__actions">',
    options.actionsHtml ?? '',
    '<div data-pad-display-controls></div>',
    '</div>',
    '</header>',
  ].join('');
}

export interface PadPageOptions {
  locale: SupportedLocale;
  /** Plain-text page title (escaped); the document title becomes "{title} — Kyberion". */
  title: string;
  /** Trusted pad markup, placed inside `<main class="kb-app-shell__main">`. */
  bodyHtml: string;
  /** Trusted extra `<head>` markup (page CSS, preloads). */
  headExtra?: string;
  /** Inline ES module source (import from `/pad-ui/pad-client.js`, `/shared-ui/*.js`). */
  scriptModule?: string;
  /** Pad-specific bootstrap data (JSON-serializable). `locale`, `messages`, `texts` are reserved. */
  bootstrap?: Record<string, unknown>;
  /** Extra vocabulary the page script reads via `t(key)`. */
  textKeys?: readonly VocabularyKey[];
  density?: 'comfortable' | 'compact';
  /** `data-role` on the app shell (e.g. the pad id). */
  role?: string;
}

/** The bootstrap object embedded as `#pad-bootstrap`. Reserved keys always win. */
export function buildPadBootstrap(
  options: Pick<PadPageOptions, 'locale' | 'bootstrap' | 'textKeys'>
): Record<string, unknown> {
  const keys = [...new Set<VocabularyKey>([...PAD_SHELL_TEXT_KEYS, ...(options.textKeys ?? [])])];
  return {
    ...(options.bootstrap ?? {}),
    locale: options.locale,
    messages: getUiMessageBundle(options.locale).messages,
    texts: padTexts(keys, options.locale),
  };
}

/** A complete pad HTML document on the shared kit. */
export function renderPadPage(options: PadPageOptions): string {
  const t = padT(options.locale);
  const density = options.density === 'compact' ? 'compact' : 'comfortable';
  const role = options.role ? ` data-role="${escapePadHtml(options.role)}"` : '';
  const script = options.scriptModule
    ? `<script type="module">${inlineScriptSource(options.scriptModule)}</script>`
    : '';
  return [
    '<!doctype html>',
    `<html lang="${escapePadHtml(options.locale)}">`,
    '<head>',
    '<meta charset="utf-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1" />',
    '<meta name="color-scheme" content="light dark" />',
    `<title>${escapePadHtml(t('local_pads:page_title', { title: options.title }))}</title>`,
    `<script>${PAD_THEME_PREPAINT_SCRIPT}</script>`,
    `<link rel="stylesheet" href="${PAD_UI_ROUTES.tokens}" />`,
    `<link rel="stylesheet" href="${PAD_UI_ROUTES.stylesheet}" />`,
    options.headExtra ?? '',
    `<script type="application/json" id="pad-bootstrap">${toPadInlineJson(buildPadBootstrap(options))}</script>`,
    '</head>',
    '<body>',
    `<div class="kb-app-shell" data-density="${density}"${role}>`,
    '<main class="kb-app-shell__main">',
    `<noscript><div class="kb-callout" data-tone="warning"><div class="kb-callout__content"><p class="kb-callout__body">${escapePadHtml(t('local_pads:noscript_notice'))}</p></div></div></noscript>`,
    options.bodyHtml,
    '</main>',
    '</div>',
    script,
    '</body>',
    '</html>',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Offline / stamped documents
// ---------------------------------------------------------------------------

/**
 * The token layer plus the component stylesheet as one CSS text, for
 * documents that must render without the pad server (report-review stamps).
 * Wrap it in `<style>`; `</style` cannot occur in the generated CSS, but it
 * is neutralized anyway.
 */
export function inlinePadStylesheets(): string {
  const read = (file: string) =>
    String(safeReadFile(pathResolver.rootResolve(file), { encoding: 'utf8' }));
  return `${read(PAD_UI_TOKENS_CSS)}\n${read(PAD_UI_STYLESHEET)}`.replace(/<\/(style)/gi, '<\\/$1');
}
