import type { LocalPadContext } from '../lib/local-artifact-pad.js';
import { getSurfaceContract, type PadSurfaceContract } from './surface.js';

/** Shared browser runtime. Pad-specific behavior is data-driven by adapters. */
export function personalPadsClientScript(
  token: string,
  context: LocalPadContext,
  contract: PadSurfaceContract = getSurfaceContract()
): string {
  const pads = contract.menu;
  const adapters = contract.content;
  return `<script>
(function(){
var token=${JSON.stringify(token)},pads=${JSON.stringify(pads)},adapters=${JSON.stringify(adapters)},currentPad=(pads[0]&&pads[0].id)||'',currentTier=${JSON.stringify(context.scope.tier)},currentRecordId='',dirty=false,lastTier=currentTier,saving=false,tierSwitching=false,pendingActions=0,historyRequest=0,historyCursor='',tierRequest=0,actionRequest=0,fieldGeneration=0,artifactLoadRequest=0,pendingFileReads=0,pendingArtifactReads=0,draftRevision=0,fieldValues={},recordingStates={},voiceStates={},canvasHistory={},artifactFieldRequest={},artifactPendingByField={},artifactFailedFields={},rawBody='',$=function(id){return document.getElementById(id)};
function esc(x){return String(x||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function say(x){$('status').textContent=x}
function api(path,options){options=options||{};options.headers=Object.assign({'X-Pads-Token':token,'Content-Type':'application/json'},options.headers||{});return fetch(path,options).then(function(r){return r.json().then(function(x){if(!r.ok)throw new Error(x.error||'request failed');return x})})}
function selected(){return pads.find(function(p){return p.id===currentPad})||pads[0]}
function adapter(){return adapters.find(function(p){return p.pad_id===currentPad})||adapters[0]}
function storageLabel(){return currentTier==='personal'?'このテナントの個人記録':currentTier==='confidential'?'このテナントの共有記録':'公開 scope の '+selected().label}
function invalidateArtifactField(fieldId){var pending=artifactPendingByField[fieldId]||0,failed=artifactFailedFields[fieldId]?1:0;pendingArtifactReads=Math.max(0,pendingArtifactReads-pending-failed);artifactPendingByField[fieldId]=0;artifactFieldRequest[fieldId]=(artifactFieldRequest[fieldId]||0)+1;delete artifactFailedFields[fieldId];return artifactFieldRequest[fieldId]}
function beginArtifactField(fieldId,count){var request=invalidateArtifactField(fieldId);artifactPendingByField[fieldId]=count;pendingArtifactReads+=count;return request}
function finishArtifactField(fieldId,request){if(artifactFieldRequest[fieldId]!==request)return;var pending=artifactPendingByField[fieldId]||0;if(pending>0){artifactPendingByField[fieldId]=pending-1;pendingArtifactReads=Math.max(0,pendingArtifactReads-1)}}
function hasArtifactFailures(){return Object.keys(artifactFailedFields).some(function(key){return artifactFailedFields[key]})}
function setScopeSwitching(active){tierSwitching=active;document.querySelectorAll('button,input,textarea,select').forEach(function(el){el.disabled=active})}
function interpolate(template,values){return template.replace(/\\{([a-z0-9_]+)\\}/gi,function(_,key){return values[key]||''}).trim()}
/* Data-driven field renderer: adapter metadata, including drawing tools and
 * image overlays, is the only source of pad-specific controls. */
function fieldMarkup(field,prefix,fieldAttr){
  var id=(prefix||'pad')+'-field-'+field.id,attr=fieldAttr||'data-field';
  var voice=field.voice_input?'<button type="button" class="secondary" data-voice-field="'+id+'" data-voice-start="'+esc(field.voice_input.label)+'" data-voice-stop="'+esc(field.voice_input.stop_label)+'">'+esc(field.voice_input.label)+'</button><small class="help" id="voice-status-'+id+'"></small>':'';
  if(field.kind==='drawing'){
    var canvas='<canvas id="'+id+'" width="900" height="360" aria-label="'+esc(field.label)+'"></canvas>';
    if(field.overlay_field){
      canvas='<div class="annotation-stage"><img class="annotation-overlay" data-overlay-preview="'+esc(field.overlay_field)+'" alt="" hidden>'+canvas+'</div>';
    }
    var tools=(field.drawing_tools||[{id:'pen',label:'ペン'},{id:'eraser',label:'消しゴム'}]).map(function(tool){return '<button type="button" class="secondary'+(tool.id==='pen'?' active-tool':'')+'" data-drawing-tool="'+esc(tool.id)+'" data-drawing-canvas="'+id+'">'+esc(tool.label)+'</button>'}).join('');
    var download=field.download?'<button type="button" class="secondary" data-download-canvas="'+id+'" data-download-filename="'+esc(field.download.filename)+'">'+esc(field.download.label)+'</button>':'';
    return '<div class="field drawing-field"><span>'+esc(field.label)+'</span>'+canvas+'<div class="drawing-actions"><div class="drawing-tool-list">'+tools+'</div><label class="help">色 <input type="color" data-drawing-color="'+id+'" value="#246b61" aria-label="描画色"></label><label class="help">線幅 <input type="range" min="1" max="24" value="3" data-drawing-width="'+id+'" aria-label="線幅"></label><button type="button" class="secondary" data-undo-canvas="'+id+'">一つ戻す</button><button type="button" class="secondary" data-clear-canvas="'+id+'">描画を消去</button>'+download+'</div><small class="help">'+esc(field.help||'ドラッグして描画できます')+'</small></div>'
  }
  if(field.kind==='file'||field.kind==='image'||field.kind==='recording'){var recording=field.kind==='recording',drop=field.kind==='image'&&field.paste_drop?'<div class="image-drop-zone secondary" data-image-drop-field="'+id+'" tabindex="0" role="button">画像を貼り付け／ドロップ</div>':'';return '<label class="field"><span>'+esc(field.label)+'</span><div class="file-row"><input id="'+id+'" type="file" '+attr+'="'+esc(field.id)+'" accept="'+esc(field.accept||'*/*')+'"'+(field.multiple?' multiple':'')+'>'+(recording?'<button type="button" class="secondary" data-record-audio="'+esc(field.id)+'">録音開始</button>':'')+'</div>'+drop+'<small class="help" id="'+id+'-name">'+esc(field.help||'ファイルを選択')+'</small>'+(recording?'<small class="help" id="'+id+'-record-status">マイク権限を確認できます（録音は明示操作で開始）</small>':'')+'<img class="image-preview" id="'+id+'-preview" alt="" hidden></label>'}
  if(field.kind==='select')return '<label class="field"><span>'+esc(field.label)+'</span><select id="'+id+'" '+attr+'="'+esc(field.id)+'">'+(field.options||[]).map(function(o){return '<option value="'+esc(o.value)+'">'+esc(o.label)+'</option>'}).join('')+'</select></label>';
  return '<label class="field"><span>'+esc(field.label)+'</span>'+(field.kind==='textarea'?'<textarea':'<input type="text"')+' id="'+id+'" '+attr+'="'+esc(field.id)+'" placeholder="'+esc(field.placeholder||'')+'"'+(field.kind==='textarea'?'></textarea>':'>')+voice+'</label>'
}
function actionFieldMarkup(action,field){var prefix='action-'+action.id.replace(/[^a-z0-9_-]/gi,'-');return fieldMarkup(field,prefix,'data-action-field')}
function actionMarkup(action){var fields=(action.input_fields||[]).map(function(field){return actionFieldMarkup(action,field)}).join('');return '<div class="action-item"><button type="button" class="secondary" data-action="'+esc(action.id)+'" title="'+esc(action.description||'')+'">'+esc(action.label)+'</button>'+fields+'<small class="action-status" id="action-status-'+esc(action.id)+'" data-action-status="'+esc(action.id)+'">確認中…</small></div>'}
function fieldsFromDom(){var values=Object.assign({},fieldValues);document.querySelectorAll('[data-field]').forEach(function(el){if(el.type==='file')return;values[el.dataset.field]=el.value});document.querySelectorAll('[data-action-field]').forEach(function(el){if(el.type==='file')return;values[el.dataset.actionField]=el.value});return values}
function updateEditorPreview(){var a=adapter(),values=fieldsFromDom();values.body=a.body_mode==='composed'?rawBody:$('body').value;var preview=interpolate(a.preview_template,values);if(a.body_mode==='composed'){$('body').value=preview;$('body').readOnly=true;$('body-field').querySelector('span').textContent='保存される内容（自動生成）'}else{$('body').readOnly=false;$('body-field').querySelector('span').textContent='内容'}fieldValues=values}
function showActionResult(result){var box=$('action-result');var details=result&&result.result;var text=details&&typeof details.markdown==='string'?details.markdown:details?JSON.stringify(details,null,2):'';box.textContent=text;box.hidden=!text}
function applyDraftPatch(patch){if(!patch)return;var values=patch.fields||{};Object.keys(values).forEach(function(key){fieldValues[key]=String(values[key]||'');var fieldId=key.endsWith('_data')?key.slice(0,-5):key,el=$('pad-field-'+fieldId);if(el&&key===fieldId&&el.tagName!=='CANVAS'&&el.type!=='file')el.value=fieldValues[key];if(el&&key.endsWith('_data')&&el.accept&&el.accept.indexOf('image/')===0){var preview=$(el.id+'-preview');if(preview){preview.src=fieldValues[key];preview.hidden=false}}});if(typeof patch.title==='string')$('title').value=patch.title;if(typeof patch.body==='string'){rawBody=patch.body;$('body').value=patch.body}dirty=true;draftRevision++;updatePreview()}
function wireActions(){document.querySelectorAll('[data-action]').forEach(function(button){button.onclick=function(){if(tierSwitching||saving||pendingFileReads>0||pendingArtifactReads>0){say('scope 切替、保存、または添付の読み込みが完了してから操作してください');return}var padAtAction=currentPad,tierAtAction=currentTier,revisionAtAction=draftRevision,recordAtAction=currentRecordId,request=++actionRequest;pendingActions++;button.disabled=true;say(button.textContent+'…');api('/api/action?tier='+encodeURIComponent(tierAtAction),{method:'POST',body:JSON.stringify({pad_id:padAtAction,action_id:button.dataset.action,tier:tierAtAction,title:$('title').value,body:$('body').value,fields:fieldsFromDom(),record_id:recordAtAction||undefined})}).then(function(x){if(request!==actionRequest||padAtAction!==currentPad||tierAtAction!==currentTier||revisionAtAction!==draftRevision||tierSwitching)return;if(x.status==='unavailable'){say(x.message||'この操作は利用できません');showActionResult(x);return}applyDraftPatch(x.draft_patch);say(x.message||'操作が完了しました');showActionResult(x)}).catch(function(e){if(request===actionRequest&&padAtAction===currentPad&&tierAtAction===currentTier&&!tierSwitching)say('操作できません: '+e.message)}).finally(function(){pendingActions=Math.max(0,pendingActions-1);button.disabled=false})}})}
function wireActionReadiness(){var padAtReadiness=currentPad,tierAtReadiness=currentTier;api('/api/action-readiness?pad='+encodeURIComponent(padAtReadiness)+'&tier='+encodeURIComponent(tierAtReadiness)).then(function(x){if(padAtReadiness!==currentPad||tierAtReadiness!==currentTier||tierSwitching)return;(x.actions||[]).forEach(function(item){var status=$("action-status-"+item.action_id);if(!status){status=document.querySelector('[data-action-status="'+item.action_id.replace(/"/g,'\\"')+'"]')}if(status)status.textContent=item.message||item.status||''})}).catch(function(){if(padAtReadiness!==currentPad||tierAtReadiness!==currentTier||tierSwitching)return;document.querySelectorAll('.action-status').forEach(function(status){status.textContent='クリック時に利用可否を確認します'})})}
function stopActiveRecordings(){Object.keys(recordingStates).forEach(function(key){var state=recordingStates[key];if(state.recorder&&state.recording){try{state.recorder.stop()}catch(_){}}if(state.stream)state.stream.getTracks().forEach(function(track){track.stop()})});recordingStates={};Object.keys(voiceStates).forEach(function(key){var state=voiceStates[key];if(state.recognition&&state.recording){try{state.recognition.stop()}catch(_){}}});voiceStates={}}
function readFileList(el,files,generation){var fieldId=el.dataset.field||el.dataset.actionField;if(!files.length){invalidateArtifactField(fieldId);return}var fieldRequest=invalidateArtifactField(fieldId),multi=el.multiple,names=files.map(function(file){return file.name});Object.keys(fieldValues).forEach(function(key){if(key===fieldId||key.indexOf(fieldId+'_data')===0||key.indexOf(fieldId+'_name_')===0)delete fieldValues[key]});fieldValues[fieldId]=multi?names.join('\\n'):names[0];names.forEach(function(name,index){fieldValues[fieldId+'_name_'+index]=name});$(el.id+'-name').textContent=multi?names.join(', '):names[0];dirty=true;draftRevision++;files.forEach(function(file,index){pendingFileReads++;var reader=new FileReader();reader.onload=function(){pendingFileReads=Math.max(0,pendingFileReads-1);if(generation!==fieldGeneration||artifactFieldRequest[fieldId]!==fieldRequest)return;var key=multi&&index>0?fieldId+'_data_'+index:fieldId+'_data';fieldValues[key]=String(reader.result||'');var preview=$(el.id+'-preview');if(preview&&el.accept&&el.accept.indexOf('image/')===0){preview.src=fieldValues[key];preview.hidden=false}updatePreview()};reader.onerror=function(){pendingFileReads=Math.max(0,pendingFileReads-1);if(generation===fieldGeneration&&artifactFieldRequest[fieldId]===fieldRequest)say('添付の読み込みに失敗しました')};reader.readAsDataURL(file)});updatePreview()}
function readFiles(el,generation){readFileList(el,Array.prototype.slice.call(el.files||[]),generation)}
function wireImageDropControls(generation){document.querySelectorAll('[data-image-drop-field]').forEach(function(zone){var input=$(zone.dataset.imageDropField);if(!input)return;zone.addEventListener('dragover',function(event){event.preventDefault();zone.classList.add('hot')});zone.addEventListener('dragleave',function(){zone.classList.remove('hot')});zone.addEventListener('drop',function(event){event.preventDefault();zone.classList.remove('hot');var files=Array.prototype.slice.call(event.dataTransfer&&event.dataTransfer.files||[]).filter(function(file){return String(file.type||'').indexOf('image/')===0});if(files.length)readFileList(input,files,generation)});zone.addEventListener('paste',function(event){var items=event.clipboardData&&event.clipboardData.items||[];for(var i=0;i<items.length;i++){if(String(items[i].type||'').indexOf('image/')===0){var file=items[i].getAsFile();if(file){event.preventDefault();readFileList(input,[file],generation);return}}}})});if(!window.__kyberionPadsImagePasteBound){document.addEventListener('paste',function(event){var zone=document.querySelector('[data-image-drop-field]'),items=event.clipboardData&&event.clipboardData.items||[];if(!zone)return;for(var i=0;i<items.length;i++){if(String(items[i].type||'').indexOf('image/')===0){var file=items[i].getAsFile(),input=$(zone.dataset.imageDropField);if(file&&input){event.preventDefault();readFileList(input,[file],fieldGeneration);return}}}});window.__kyberionPadsImagePasteBound=true}}
function probeMicrophonePermission(status){if(!navigator.permissions||!navigator.permissions.query)return;navigator.permissions.query({name:'microphone'}).then(function(permission){function update(){status.textContent=permission.state==='granted'?'マイク権限: 許可済み':permission.state==='denied'?'マイク権限: 拒否（設定を確認してください）':'マイク権限: 録音開始時に確認'}update();permission.onchange=update}).catch(function(){status.textContent='マイク権限: 録音開始時に確認'})}
function wireRecordingControls(generation){document.querySelectorAll('[data-record-audio]').forEach(function(button){var fieldId=button.dataset.recordAudio,status=$("pad-field-"+fieldId+"-record-status"),state={recorder:null,stream:null,chunks:[],recording:false,generation:generation};recordingStates[fieldId]=state;function report(message){if(status)status.textContent=message}probeMicrophonePermission(status);button.onclick=function(){if(state.recording){try{state.recorder.stop()}catch(_){report('録音を停止できませんでした')}return}if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia||!window.MediaRecorder){report('このブラウザは連続録音に対応していません。録音ファイルを選択してください');return}var requestGeneration=fieldGeneration;report('マイク権限を確認しています…');navigator.mediaDevices.getUserMedia({audio:true}).then(function(stream){if(requestGeneration!==fieldGeneration){stream.getTracks().forEach(function(track){track.stop()});return}state.stream=stream;state.chunks=[];var mime='';if(MediaRecorder.isTypeSupported('audio/webm;codecs=opus'))mime='audio/webm;codecs=opus';else if(MediaRecorder.isTypeSupported('audio/webm'))mime='audio/webm';else if(MediaRecorder.isTypeSupported('audio/mp4'))mime='audio/mp4';state.recorder=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);state.recorder.ondataavailable=function(event){if(event.data&&event.data.size)state.chunks.push(event.data)};state.recorder.onerror=function(){report('録音中にエラーが発生しました');state.recording=false;button.disabled=false;button.textContent='録音開始';stream.getTracks().forEach(function(track){track.stop()})};state.recorder.onstop=function(){state.recording=false;button.disabled=false;button.textContent='録音開始';stream.getTracks().forEach(function(track){track.stop()});if(requestGeneration!==fieldGeneration)return;var blob=new Blob(state.chunks,{type:state.recorder.mimeType||'audio/webm'});if(!blob.size){report('録音データが空でした');return}pendingFileReads++;var reader=new FileReader();reader.onload=function(){pendingFileReads=Math.max(0,pendingFileReads-1);if(requestGeneration!==fieldGeneration)return;var mimeType=blob.type||'audio/webm',extension=mimeType.indexOf('mp4')>=0?'.m4a':'.webm';fieldValues[fieldId]='recording-'+Date.now()+extension;fieldValues[fieldId+'_name_0']=fieldValues[fieldId];fieldValues[fieldId+'_data']=String(reader.result||'');dirty=true;draftRevision++;report('録音を下書きへ取り込みました。保存前に内容を確認してください');updatePreview()};reader.onerror=function(){pendingFileReads=Math.max(0,pendingFileReads-1);if(requestGeneration===fieldGeneration)report('録音データの読み込みに失敗しました')};reader.readAsDataURL(blob)};state.recorder.start(250);state.recording=true;button.disabled=false;button.textContent='録音停止';report('録音中… 終了したら停止してください')}).catch(function(error){report('マイクを利用できません: '+(error&&error.message?error.message:String(error)))})}})}
function wireVoiceControls(generation){
  document.querySelectorAll('[data-voice-field]').forEach(function(button){
    var field=$(button.dataset.voiceField),status=$('voice-status-'+button.dataset.voiceField),Speech=window.SpeechRecognition||window.webkitSpeechRecognition,state={recognition:null,recording:false,generation:generation};
    voiceStates[button.dataset.voiceField]=state;
    function report(message){if(status)status.textContent=message}
    button.onclick=function(){
      if(state.recording){try{state.recognition.stop()}catch(_){report('音声入力を停止できませんでした')}return}
      if(!Speech){report('このブラウザは音声入力に対応していません');return}
      var recognition=new Speech();state.recognition=recognition;recognition.lang='ja-JP';recognition.continuous=true;recognition.interimResults=true;
      recognition.onresult=function(event){var text='';for(var i=event.resultIndex;i<event.results.length;i++){if(event.results[i].isFinal)text+=event.results[i][0].transcript}if(text&&state.generation===fieldGeneration){field.value=(field.value?field.value+' ':'')+text;field.dispatchEvent(new Event('input',{bubbles:true}));dirty=true;draftRevision++;updatePreview()}};
      recognition.onerror=function(event){report('音声入力エラー: '+(event.error||''));state.recording=false;button.textContent=button.dataset.voiceStart};
      recognition.onend=function(){state.recording=false;button.textContent=button.dataset.voiceStart;report('音声入力を停止しました')};
      try{recognition.start();state.recording=true;button.textContent=button.dataset.voiceStop;report('音声入力中…')}catch(error){report('音声入力を開始できません: '+(error&&error.message?error.message:String(error)))}
    };
  });
}
function wireFields(){
  var generation=fieldGeneration;
  document.querySelectorAll('[data-field],[data-action-field]').forEach(function(el){
    el.addEventListener('input',function(){dirty=true;draftRevision++;updatePreview()});
    if(el.tagName==='SELECT')el.addEventListener('change',function(){dirty=true;draftRevision++;updatePreview()});
    if(el.type==='file')el.addEventListener('change',function(){readFiles(el,generation)});
  });
  wireRecordingControls(generation);
  wireVoiceControls(generation);
  wireImageDropControls(generation);
  document.querySelectorAll('[data-download-canvas]').forEach(function(button){
    button.onclick=function(){
      var canvas=$(button.dataset.downloadCanvas),link=document.createElement('a'),field=adapter().fields.find(function(candidate){return candidate.id===canvas.id.slice('pad-field-'.length)}),overlay=field&&field.overlay_field?$('pad-field-'+field.overlay_field+'-preview'):null;
      if(!canvas)return;
      var finish=function(background){var output=document.createElement('canvas'),ctx=output.getContext('2d');output.width=canvas.width;output.height=canvas.height;ctx.fillStyle='#f6faf9';ctx.fillRect(0,0,output.width,output.height);if(background&&background.naturalWidth){var scale=Math.min(output.width/background.naturalWidth,output.height/background.naturalHeight),width=background.naturalWidth*scale,height=background.naturalHeight*scale;ctx.drawImage(background,(output.width-width)/2,(output.height-height)/2,width,height)}ctx.drawImage(canvas,0,0);link.href=output.toDataURL('image/png');link.download=button.dataset.downloadFilename||'drawing.png';link.click()};
      if(overlay&&overlay.src){if(overlay.complete)finish(overlay);else{overlay.onload=function(){finish(overlay)}}}else finish(null)
    };
  });
  document.querySelectorAll('[data-clear-canvas]').forEach(function(button){
    button.onclick=function(){
      var canvas=$(button.dataset.clearCanvas),fieldId=canvas.id.slice('pad-field-'.length),ctx=canvas.getContext('2d');
      invalidateArtifactField(fieldId);canvasHistory[fieldId]=[];ctx.clearRect(0,0,canvas.width,canvas.height);
      fieldValues[fieldId]='';dirty=true;draftRevision++;updatePreview();
    };
  });
  document.querySelectorAll('[data-undo-canvas]').forEach(function(button){
    button.onclick=function(){
      var canvas=$(button.dataset.undoCanvas),fieldId=canvas.id.slice('pad-field-'.length),history=canvasHistory[fieldId]||[],previous=history.pop()||'',ctx=canvas.getContext('2d');
      invalidateArtifactField(fieldId);ctx.clearRect(0,0,canvas.width,canvas.height);fieldValues[fieldId]=previous;
      if(previous){var image=new Image();image.onload=function(){ctx.drawImage(image,0,0,canvas.width,canvas.height)};image.src=previous}
      dirty=true;draftRevision++;updatePreview();
    };
  });
  document.querySelectorAll('.drawing-field canvas').forEach(function(canvas){
    var fieldId=canvas.id.slice('pad-field-'.length),drawing=false,startX=0,startY=0,snapshot=null,tool='pen',ctx=canvas.getContext('2d');
    canvasHistory[fieldId]=[];canvas.dataset.drawingTool='pen';ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#246b61';
    var toolButtons=document.querySelectorAll('[data-drawing-canvas="'+canvas.id+'"]');
    function setTool(next){
      tool=next||'pen';canvas.dataset.drawingTool=tool;
      toolButtons.forEach(function(button){var active=button.dataset.drawingTool===tool;button.classList.toggle('active-tool',active);button.setAttribute('aria-pressed',active?'true':'false');button.style.background=active?'#dff1ec':'';button.style.borderColor=active?'#9ac9be':'';button.style.color=active?'#246b61':''});
      ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';
    }
    function markChanged(){fieldValues[fieldId]=canvas.toDataURL('image/png');dirty=true;draftRevision++;updatePreview()}
    function pointerPos(event){var rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*(canvas.width/rect.width),y:(event.clientY-rect.top)*(canvas.height/rect.height)}}
    function strokeStyle(){ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=Number((document.querySelector('[data-drawing-width="'+canvas.id+'"]')||{}).value)||3;ctx.strokeStyle=(document.querySelector('[data-drawing-color="'+canvas.id+'"]')||{}).value||'#246b61';ctx.fillStyle=ctx.strokeStyle;ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over'}
    function restoreSnapshot(){if(snapshot)ctx.putImageData(snapshot,0,0)}
    function drawArrow(x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();var angle=Math.atan2(y2-y1,x2-x1),len=12+ctx.lineWidth;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-len*Math.cos(angle-Math.PI/6),y2-len*Math.sin(angle-Math.PI/6));ctx.lineTo(x2-len*Math.cos(angle+Math.PI/6),y2-len*Math.sin(angle+Math.PI/6));ctx.closePath();ctx.fill()}
    toolButtons.forEach(function(button){button.onclick=function(){setTool(button.dataset.drawingTool)}});
    var color=document.querySelector('[data-drawing-color="'+canvas.id+'"]'),width=document.querySelector('[data-drawing-width="'+canvas.id+'"]');
    if(color)color.oninput=function(){if(tool==='eraser')setTool('pen');strokeStyle()};
    if(width)width.oninput=function(){strokeStyle()};
    setTool('pen');
    canvas.addEventListener('pointerdown',function(event){
      var point=pointerPos(event);startX=point.x;startY=point.y;
      if(tool==='text'){
        canvasHistory[fieldId].push(fieldValues[fieldId]||'');
        if(canvasHistory[fieldId].length>40)canvasHistory[fieldId].shift();
        var label=window.prompt('テキスト','');
        if(label){strokeStyle();ctx.font=(16+(Number(width&&width.value)||3)*2)+'px sans-serif';ctx.fillText(label,startX,startY);markChanged()}
        return;
      }
      drawing=true;snapshot=ctx.getImageData(0,0,canvas.width,canvas.height);canvasHistory[fieldId].push(fieldValues[fieldId]||'');
      if(canvasHistory[fieldId].length>40)canvasHistory[fieldId].shift();canvas.setPointerCapture(event.pointerId);strokeStyle();
      if(tool==='pen'||tool==='eraser'){ctx.beginPath();ctx.moveTo(startX,startY)}
    });
    canvas.addEventListener('pointermove',function(event){
      if(!drawing)return;var point=pointerPos(event);
      if(tool==='pen'||tool==='eraser'){ctx.lineTo(point.x,point.y);ctx.stroke();ctx.beginPath();ctx.moveTo(point.x,point.y);markChanged();return}
      restoreSnapshot();strokeStyle();
      if(tool==='rect')ctx.strokeRect(startX,startY,point.x-startX,point.y-startY);
      else if(tool==='ellipse'){ctx.beginPath();ctx.ellipse((startX+point.x)/2,(startY+point.y)/2,Math.abs(point.x-startX)/2,Math.abs(point.y-startY)/2,0,0,Math.PI*2);ctx.stroke()}
      else if(tool==='line'){ctx.beginPath();ctx.moveTo(startX,startY);ctx.lineTo(point.x,point.y);ctx.stroke()}
      else if(tool==='arrow')drawArrow(startX,startY,point.x,point.y);
      fieldValues[fieldId]=canvas.toDataURL('image/png');dirty=true;draftRevision++;updatePreview();
    });
    function endDraw(){if(drawing){drawing=false;snapshot=null;markChanged()}}
    canvas.addEventListener('pointerup',endDraw);canvas.addEventListener('pointercancel',endDraw);
  });
}
function syncAnnotationOverlays(){document.querySelectorAll('[data-overlay-preview]').forEach(function(overlay){var fieldId=overlay.dataset.overlayPreview,input=$('pad-field-'+fieldId),preview=input&&$(input.id+'-preview');if(preview&&preview.src){overlay.src=preview.src;overlay.hidden=false}})}
function updatePreview(){updateEditorPreview();syncAnnotationOverlays()}
function renderPad(){var p=selected(),a=adapter();stopActiveRecordings();fieldGeneration++;artifactLoadRequest++;pendingFileReads=0;pendingArtifactReads=0;artifactFieldRequest={};artifactPendingByField={};artifactFailedFields={};canvasHistory={};actionRequest++;currentRecordId='';draftRevision++;$('pad-kind').textContent=p.id;$('pad-title').textContent=p.label;$('pad-description').textContent=p.description;$('storage-label').textContent=storageLabel();document.querySelectorAll('.pad').forEach(function(x){x.classList.toggle('active',x.dataset.pad===currentPad);x.setAttribute('aria-pressed',x.dataset.pad===currentPad?'true':'false')});fieldValues={};rawBody='';$('title').value='';$('pad-fields').innerHTML=a.fields.map(fieldMarkup).join('');$('pad-actions').innerHTML=(a.actions||[]).map(actionMarkup).join('');$('action-result').hidden=true;$('action-result').textContent='';$('body').value='';$('body').readOnly=false;$('body').placeholder=a.body_mode==='composed'?'入力欄から保存内容を生成します':'ここに記録します';$('history').innerHTML='<div class="empty">履歴を読み込んでいます…</div>';wireFields();wireActions();wireActionReadiness();updatePreview();loadHistory()}
function restoreArtifacts(record){var refs=record.artifact_refs||[],padAtRestore=currentPad,tierAtRestore=currentTier,load=artifactLoadRequest,fieldCounts={},fieldIndexes={},fieldTokens={};refs.forEach(function(ref){fieldCounts[ref.field_id]=(fieldCounts[ref.field_id]||0)+1});Object.keys(fieldCounts).forEach(function(fieldId){fieldTokens[fieldId]=beginArtifactField(fieldId,fieldCounts[fieldId])});refs.forEach(function(ref){var index=fieldIndexes[ref.field_id]||0;fieldIndexes[ref.field_id]=index+1;var fieldToken=fieldTokens[ref.field_id];api('/api/history/'+encodeURIComponent(record.record_id)+'?pad='+encodeURIComponent(padAtRestore)+'&tier='+encodeURIComponent(tierAtRestore)+'&artifact='+encodeURIComponent(ref.artifact_id)).then(function(x){if(load!==artifactLoadRequest||padAtRestore!==currentPad||tierAtRestore!==currentTier||artifactFieldRequest[ref.field_id]!==fieldToken)return;var data='data:'+(x.artifact.ref.mime||'application/octet-stream')+';base64,'+x.artifact.data_base64,field=adapter().fields.find(function(candidate){return candidate.id===ref.field_id}),isDrawing=field&&field.kind==='drawing',key=isDrawing?ref.field_id:index===0?ref.field_id+'_data':ref.field_id+'_data_'+index;if(isDrawing){fieldValues[ref.field_id]=data;fieldValues[ref.field_id+'_name_'+index]=ref.name}else{fieldValues[key]=data;fieldValues[ref.field_id+'_name_'+index]=ref.name;var currentNames=fieldValues[ref.field_id]?fieldValues[ref.field_id].split('\\n').filter(Boolean):[];if(currentNames.indexOf(ref.name)<0)currentNames.push(ref.name);fieldValues[ref.field_id]=currentNames.join('\\n')}var input=$('pad-field-'+ref.field_id);if(input&&input.accept&&input.accept.indexOf('image/')===0){var preview=$(input.id+'-preview');preview.src=data;preview.hidden=false}if(isDrawing){var canvas=$('pad-field-'+ref.field_id);if(canvas){var image=new Image();image.onload=function(){canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height)};image.src=data}}updatePreview()}).catch(function(e){if(load===artifactLoadRequest&&padAtRestore===currentPad&&tierAtRestore===currentTier&&artifactFieldRequest[ref.field_id]===fieldToken){if(!artifactFailedFields[ref.field_id]){artifactFailedFields[ref.field_id]=true;pendingArtifactReads++}say('添付を読み込めません: '+e.message)}}).finally(function(){finishArtifactField(ref.field_id,fieldToken)})})}
	function restoreRecord(record){currentRecordId=record.record_id||'';fieldValues=Object.assign({},record.payload||{});rawBody=fieldValues.body||'';document.querySelectorAll('[data-field],[data-action-field]').forEach(function(el){var key=el.dataset.field||el.dataset.actionField,value=fieldValues[key];if(typeof value==='string'&&el.type!=='file')el.value=value});Object.keys(fieldValues).forEach(function(key){var directField=adapter().fields.find(function(candidate){return candidate.id===key}),fieldId=directField?key:key.endsWith('_data')?key.slice(0,-5):key.replace(/_data_[0-9]+$/,'') ,field=directField||adapter().fields.find(function(candidate){return candidate.id===fieldId});if(!field||(!directField&&!(/_data(?:_[0-9]+)?$/).test(key)))return;var input=$('pad-field-'+fieldId);if(field.kind==='image'||field.kind==='file'||field.kind==='recording'){var preview=input&&$(input.id+'-preview');if(preview){preview.src=fieldValues[key];preview.hidden=false}}if(field.kind==='drawing'){var canvas=$('pad-field-'+fieldId);if(canvas){var image=new Image();image.onload=function(){canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height)};image.src=fieldValues[key]}}});$('title').value=record.title||'';$('body').value=adapter().body_mode==='freeform'?(fieldValues.body||''):(record.body||'');updatePreview();dirty=true;draftRevision++;say('履歴をコピーして編集できます');restoreArtifacts(record)}
function historyCard(r){var preview=String(r.body||'').replace(/\\s+/g,' ').trim().slice(0,90)||'保存済み記録',attachments=Array.isArray(r.artifact_refs)&&r.artifact_refs.length?' · 添付 '+r.artifact_refs.length+'件':'';return '<article class="record" data-record="'+esc(r.record_id)+'"><strong>'+esc(r.title||selected().label)+'</strong><small class="help">'+esc(preview+attachments)+'</small><time>'+new Date(r.created_at).toLocaleString('ja-JP',{dateStyle:'short',timeStyle:'short'})+'</time></article>'}
function wireHistory(){document.querySelectorAll('.record').forEach(function(x){x.onclick=function(){if(tierSwitching||saving||pendingArtifactReads>0){say('scope 切替、保存、または添付の読み込みが完了してから履歴を開いてください');return}var padAtClick=currentPad,tierAtClick=currentTier;api('/api/history/'+encodeURIComponent(x.dataset.record)+'?pad='+encodeURIComponent(padAtClick)+'&tier='+encodeURIComponent(tierAtClick)).then(function(r){if(padAtClick===currentPad&&tierAtClick===currentTier&&!tierSwitching)restoreRecord(r.record)})}})}
function loadHistory(reset){if(tierSwitching)return;var request=++historyRequest,padAtRequest=currentPad,tierAtRequest=currentTier;if(reset!==false){historyCursor='';$('history').innerHTML='<div class="empty">履歴を読み込んでいます…</div>'}var query='/api/history?pad='+encodeURIComponent(padAtRequest)+'&tier='+encodeURIComponent(tierAtRequest)+(historyCursor?'&cursor='+encodeURIComponent(historyCursor):'');api(query).then(function(x){if(request!==historyRequest||padAtRequest!==currentPad||tierAtRequest!==currentTier||tierSwitching)return;var rows=x.records||[];if(reset!==false)$('history').innerHTML='';if(rows.length)$('history').insertAdjacentHTML('beforeend',rows.map(historyCard).join(''));else if(reset!==false)$('history').innerHTML='<div class="empty">この pad の保存履歴はまだありません。</div>';historyCursor=x.next_cursor||'';$('history-more').hidden=!historyCursor;wireHistory()}).catch(function(e){if(request===historyRequest&&!tierSwitching)say(e.message)})}
function choose(){if(tierSwitching||saving||pendingActions>0){say('scope 切替または操作の完了を待ってください');return false}if(!dirty)return true;var answer=window.prompt('未保存の内容があります。保存 / 破棄 / キャンセル','キャンセル');if(answer==='破棄'){dirty=false;return true}if(answer==='保存'){$('save').click();return false}return false}
document.querySelectorAll('.pad').forEach(function(x){x.onclick=function(){if(tierSwitching||!choose())return;currentPad=x.dataset.pad;dirty=false;renderPad()}});$('tier-select').value=currentTier;$('tier-select').onchange=function(){var requested=this.value;if(tierSwitching||!choose()){this.value=lastTier;return}var previousTier=lastTier,request=++tierRequest;setScopeSwitching(true);api('/api/context?tier='+encodeURIComponent(requested)).then(function(x){if(request!==tierRequest)return;currentTier=requested;$('tenant').textContent=x.scope.tenant_slug||'public';$('tier').textContent=x.scope.tier;lastTier=requested;dirty=false;setScopeSwitching(false);renderPad()}).catch(function(e){if(request!==tierRequest)return;currentTier=previousTier;$('tier-select').value=previousTier;setScopeSwitching(false);say(e.message)})};$('body').addEventListener('input',function(){if(tierSwitching)return;dirty=true;draftRevision++;if(adapter().body_mode==='freeform')rawBody=$('body').value;updatePreview()});$('save').onclick=function(){if(saving||tierSwitching||pendingActions>0)return;if(pendingFileReads>0||pendingArtifactReads>0){say('添付を読み込み中…');return}var savePad=currentPad,saveTier=currentTier,saveRevision=draftRevision;saving=true;updatePreview();var body=$('body').value;if(!body.trim()){saving=false;say('内容を入力してください');return}var saveTitle=$('title').value,saveFields=fieldsFromDom();say('保存中…');api('/api/capture?tier='+encodeURIComponent(saveTier),{method:'POST',body:JSON.stringify({pad_id:savePad,tier:saveTier,title:saveTitle,body:body,fields:saveFields})}).then(function(x){saving=false;if(savePad!==currentPad||saveTier!==currentTier||saveRevision!==draftRevision){loadHistory();say('保存しました（現在の下書きは保持） · '+x.record.record_id);return}rawBody='';dirty=false;renderPad();say('保存しました · '+x.record.record_id)}).catch(function(e){saving=false;say('保存できません: '+e.message)});};$('clear').onclick=function(){if(saving||tierSwitching||pendingActions>0)return;fieldValues={};rawBody='';$('title').value='';$('body').value='';dirty=false;draftRevision++;renderPad();say('下書きを消去しました')};$('refresh').onclick=function(){if(tierSwitching)return;loadHistory(true)};var historyMore=document.createElement('button');historyMore.id='history-more';historyMore.className='secondary';historyMore.textContent='さらに読み込む';historyMore.hidden=true;$('history').after(historyMore);historyMore.onclick=function(){if(tierSwitching)return;loadHistory(false)};window.addEventListener('beforeunload',function(e){if(dirty){e.preventDefault();e.returnValue=''}});renderPad()})();</script>`;
}
