/**
 * system-capture-alias-ops.ts — capture ops exposed under system:* aliases.
 * Extracted from system-pipeline-core-helpers.ts to keep that module under
 * the max-file-lines ratchet.
 */
export const SYSTEM_ACTUATOR_CAPTURE_ALIAS_OPS = new Set<string>([
  'screenshot',
  'clipboard_read',
  'get_focused_input',
  'get_screen_size',
  'macos_automation_probe',
  'window_list',
  'chrome_tab_list',
  'read_file',
  'read_json',
  'probe',
  'probe_active_profile',
  'glob_files',
  'scan_directory',
  'pulse_status',
  'exec',
  'shell',
  'cli_health_check',
  'list_missions',
  'list_projects',
  'list_capabilities',
  'list_incidents',
  'list_knowledge',
  'list_running_apps',
  'list_input_devices',
  'list_displays',
  'list_media_devices',
  'list_tool_runtimes',
  'list_service_runtimes',
  'control_media_devices',
  'collect_artifacts',
  'resolve_path',
  'sample_traces',
  'vision_consult',
  'test_screen_stream',
  'test_screen_mp4_roundtrip',
  'test_camera_injection',
  'list',
]);
