import {
  activateApplication,
  detectFocusedInput,
  keystrokeText,
  pasteText,
  pressKey,
  pressKeyCode,
  toggleDictation,
  clickAt,
  rightClickAt,
  moveMouse,
  scrollAt,
  dragFrom,
  runAppleScript,
  getScreenSize,
  getWindowList,
  activateWindowByTitle,
  quitApplication,
  systemNotify,
  clipboardRead,
  clipboardWrite,
  takeScreenshot,
} from './os-automation.js';

import {
  listKnownAppCapabilities,
  listTerminalTargets,
  listChromeTabs,
  activateChromeTabByTitle,
  activateChromeTabByUrl,
  closeChromeTabByTitle,
  closeChromeTabByUrl,
  emptyFinderTrash,
  revealFinderPath,
  openFinderPath,
} from './os-automation.js';

export const osAutomationBridge = {
  activateApplication,
  detectFocusedInput,
  keystrokeText,
  pasteText,
  pressKey,
  pressKeyCode,
  toggleDictation,
  clickAt,
  rightClickAt,
  moveMouse,
  scrollAt,
  dragFrom,
  runAppleScript,
  getScreenSize,
  getWindowList,
  activateWindowByTitle,
  quitApplication,
  systemNotify,
  clipboardRead,
  clipboardWrite,
  takeScreenshot,
  listKnownAppCapabilities,
  listTerminalTargets,
  listChromeTabs,
  activateChromeTabByTitle,
  activateChromeTabByUrl,
  closeChromeTabByTitle,
  closeChromeTabByUrl,
  emptyFinderTrash,
  revealFinderPath,
  openFinderPath,
} as const;

export type OsAutomationBridge = typeof osAutomationBridge;
