import { describe, expect, it } from 'vitest';
import { readJson } from '@agent/core/foundation';
import { pathResolver } from '@agent/core/path-resolver';
import {
  REACHABILITY_REPORT_PATH,
  type RoleAssumptionReachabilityReport,
} from './analyze_role_assumptions.js';

/**
 * RN-03: role-assumption-policy.json must grant every role the call-level
 * analysis reaches, so code that adds an assumption breaks CI instead of
 * failing in production with [ROLE_ASSUMPTION_DENIED]. The report is
 * regenerated by `node --import ./scripts/ts-loader.mjs
 * scripts/analyze_role_assumptions.ts`; the `role-assumption-reachability` CI
 * gate (`--check`) fails when it is stale against the code.
 */
interface Policy {
  shared_core_roles: { roles: string[] };
  system_roles: Record<string, { may_assume: string[] }>;
}

const report = readJson<RoleAssumptionReachabilityReport>(
  pathResolver.rootResolve(REACHABILITY_REPORT_PATH)
);
const policy = readJson<Policy>(
  pathResolver.rootResolve('knowledge/product/governance/role-assumption-policy.json')
);

/**
 * System roles whose grants RN-03 narrowed on the report's evidence. Their
 * narrowing is only sound while the analysis can prove unreachability, so a
 * new any-role site or an inheriting child process must force a re-review.
 */
const NARROWED_SYSTEM_ROLES = ['oauth_callback_surface', 'surface_runtime'];

function allowedFor(systemRole: string): Set<string> {
  return new Set([
    systemRole,
    ...policy.shared_core_roles.roles,
    ...(policy.system_roles[systemRole]?.may_assume ?? []),
  ]);
}

describe('RN-03 role assumption policy covers the reachability report', () => {
  it('grants every reachable role to its system role', () => {
    const missing: string[] = [];
    for (const [systemRole, entry] of Object.entries(report.system_roles)) {
      const allowed = allowedFor(systemRole);
      for (const [role, reach] of Object.entries(entry.reachable_roles)) {
        if (!allowed.has(role)) {
          missing.push(`${systemRole} -> ${role} via ${reach.example_path.join(' -> ')}`);
        }
      }
    }
    expect(missing).toEqual([]);
  });

  it('analyses exactly the system roles the policy governs', () => {
    expect(Object.keys(report.system_roles).sort()).toEqual(
      Object.keys(policy.system_roles).sort()
    );
  });

  it('analyses every SYSTEM_ROLE a package script launches', () => {
    const scripts = readJson<{ scripts: Record<string, string> }>(
      pathResolver.rootResolve('package.json')
    ).scripts;
    const launched = Object.values(scripts).flatMap((command) =>
      [...command.matchAll(/\bSYSTEM_ROLE=([a-z0-9_]+)/g)].map((match) => match[1])
    );
    expect(launched.length).toBeGreaterThan(0);
    for (const systemRole of launched) {
      expect(Object.keys(report.system_roles)).toContain(systemRole);
    }
  });

  it('keeps every narrowed system role fully resolved (S2)', () => {
    for (const systemRole of NARROWED_SYSTEM_ROLES) {
      const entry = report.system_roles[systemRole];
      expect(entry, systemRole).toBeDefined();
      expect(entry.unresolved_sites, `${systemRole}: any-role sites need a re-review`).toEqual([]);
      expect(
        entry.child_process_entries,
        `${systemRole}: children inheriting SYSTEM_ROLE need a re-review`
      ).toEqual([]);
    }
  });

  it('was generated against the current policy', () => {
    // policy_roles_not_reachable is derived from the policy: a policy edit
    // without regenerating the report shows up here.
    for (const [systemRole, entry] of Object.entries(report.system_roles)) {
      const expected =
        entry.unresolved_sites.length > 0
          ? []
          : [...allowedFor(systemRole)]
              .filter((role) => role !== systemRole && !entry.reachable_roles[role])
              .sort();
      expect(entry.policy_roles_not_reachable, systemRole).toEqual(expected);
    }
  });
});
