import { describe, expect, it } from 'vitest';
import { readTextFile } from '@agent/core/foundation';
import { pathResolver } from '@agent/core/path-resolver';
import {
  extractKyberionTokenBlock,
  extractKyberionUiTokenBlock,
  KB_UI_STATUS_TONES_PLACEHOLDER,
  KB_UI_TOKEN_BLOCK_END,
  KB_UI_TOKEN_BLOCK_START,
  KYBERION_UI_STYLESHEET_SOURCE,
  concatKyberionUiStylesheetSources,
  listKyberionUiStylesheetSources,
  readKyberionDesignTokens,
  renderKyberionDesignTokenBlock,
  renderKyberionTailwindColorsBlock,
  renderKyberionUiStylesheet,
  renderKyberionUiTokenBlock,
  replaceTokenBlock,
  replaceUiTokenBlock,
  updateThemesJson,
} from './design-token-utils.js';

describe('canonical design-token generation', () => {
  it('renders semantic tokens for automatic and explicit themes', () => {
    const block = renderKyberionDesignTokenBlock(readKyberionDesignTokens());
    expect(block).toContain('--kb-surface:');
    expect(block).toContain('--kb-border:');
    expect(block).toContain('--kb-success:');
    expect(block).toContain('--kb-danger:');
    expect(block).toContain("[data-theme='light']");
    expect(block).toContain("[data-theme='dark']");
    expect(block).not.toContain('--kb-border: 1px solid');
  });

  it('maps semantic tokens into Tailwind and replaces legacy explicit-theme blocks', () => {
    const block = renderKyberionDesignTokenBlock(readKyberionDesignTokens());
    const tailwind = renderKyberionTailwindColorsBlock();
    expect(tailwind).toContain('success: "var(--kb-success)"');
    expect(tailwind).toContain('danger: "var(--kb-danger)"');

    const legacy = [
      ':root {',
      '  --kb-bg-main: #fff;',
      '}',
      '',
      '@media (prefers-color-scheme: dark) {',
      '  :root {',
      '    --kb-bg-main: #000;',
      '  }',
      '}',
      '',
      "[data-theme='light'] {",
      '  --kb-bg-main: #fff;',
      '}',
      '',
      "[data-theme='dark'] {",
      '  --kb-bg-main: #000;',
      '}',
      '',
      'body { color: var(--kb-text-primary); }',
    ].join('\n');
    const replaced = replaceTokenBlock(legacy, block);
    expect(replaced.match(/\[data-theme='light'\]/gu)).toHaveLength(1);
    expect(replaced).toContain('body { color: var(--kb-text-primary); }');
  });

  it('rejects a non-object themes root and ignores an array themes value', () => {
    const tokens = readKyberionDesignTokens();
    expect(() => updateThemesJson('[]', tokens)).toThrow('root must be a JSON object');
    const output = updateThemesJson('{"themes":["malformed"]}', tokens);
    expect(JSON.parse(output).themes['0']).toBeUndefined();
    expect(JSON.parse(output).themes['kyberion-standard']).toBeDefined();
  });

  it('rejects dangerous JSON keys before updating themes', () => {
    expect(() =>
      updateThemesJson('{"themes":{"constructor":{"polluted":true}}}', readKyberionDesignTokens())
    ).toThrow('contains a dangerous JSON key');
  });
});

describe('UI token layer and component stylesheet (UI-02)', () => {
  it('renders light defaults with guarded dark overrides and density scales', () => {
    const block = renderKyberionUiTokenBlock(readKyberionDesignTokens());
    expect(block.startsWith(KB_UI_TOKEN_BLOCK_START)).toBe(true);
    expect(block.endsWith(KB_UI_TOKEN_BLOCK_END)).toBe(true);
    expect(block).toContain('--kb-ui-canvas:');
    expect(block).toContain('--kb-ui-danger-fg:');
    expect(block).toContain('--kb-ui-role-concierge:');
    expect(block).toContain(
      '@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {'
    );
    expect(block).toContain(':root[data-theme="dark"] {');
    expect(block).toContain('[data-density="compact"] {');
    expect(block).not.toContain('--kb-bg-main');
  });

  it('inserts the UI block after the legacy block once and replaces it idempotently', () => {
    const tokens = readKyberionDesignTokens();
    const legacy = renderKyberionDesignTokenBlock(tokens);
    const ui = renderKyberionUiTokenBlock(tokens);
    const source = `${legacy}\n\nbody { color: var(--kb-text-primary); }\n`;
    const once = replaceUiTokenBlock(source, ui);
    expect(once).toBe(`${legacy}\n\n${ui}\n\nbody { color: var(--kb-text-primary); }\n`);
    expect(replaceUiTokenBlock(once, ui)).toBe(once);
    expect(extractKyberionUiTokenBlock(once)).toBe(ui);
    expect(extractKyberionTokenBlock(once)).toBe(legacy);
    expect(() => replaceUiTokenBlock('body {}', ui)).toThrow('Failed to locate');
  });

  it('assembles the stylesheet with status tones generated from the catalog', () => {
    const css = renderKyberionUiStylesheet(
      `.kb-status-pill { color: var(--kb-ui-pill-fg); }\n${KB_UI_STATUS_TONES_PLACEHOLDER}\n`
    );
    expect(css.startsWith('/* GENERATED by scripts/generate_design_tokens.ts')).toBe(true);
    expect(css).not.toContain(KB_UI_STATUS_TONES_PLACEHOLDER);
    expect(css).toContain('.kb-status-pill[data-status="failed"]');
    expect(css).toContain('.kb-status-pill[data-status="n/a"]');
    expect(css).toContain('--kb-ui-pill-fg: var(--kb-ui-danger-fg);');
    expect(() => renderKyberionUiStylesheet('.kb-x {}')).toThrow('must contain');
  });

  it('stamps the base stylesheet first, then every kyberion-ui.<part>.source.css', () => {
    const sources = listKyberionUiStylesheetSources();
    expect(sources[0]).toBe(KYBERION_UI_STYLESHEET_SOURCE);
    expect(sources).toContain('knowledge/public/design-patterns/web/kyberion-ui.charts.source.css');
    expect([...sources.slice(1)].sort()).toEqual(sources.slice(1));
    const joined = concatKyberionUiStylesheetSources((relativePath) => `/* ${relativePath} */`);
    expect(joined.indexOf('kyberion-ui.source.css')).toBeLessThan(joined.indexOf('.charts.'));
  });

  it('keeps the authored component stylesheet free of literal colors', () => {
    const source = concatKyberionUiStylesheetSources((relativePath) =>
      readTextFile(pathResolver.rootResolve(relativePath))
    );
    expect(source.match(/#[0-9a-f]{3,8}\b|\brgba?\s*\(|\bhsla?\s*\(/giu)).toBeNull();
    expect(source).not.toMatch(/gradient\(|backdrop-filter|blur\(/u);
  });
});
