/** EG-11: one-time cleanup mission. Dry-run is the default; apply is an
 * explicitly approved, soft-delete-only operation with an evidence receipt. */
import * as path from 'node:path';
import {
  computeApprovalPayloadHash,
  createApprovalRequest,
  listApprovalRequests,
  loadApprovalRequest,
  missionEvidenceDir,
  pathResolver,
  safeExistsSync,
  safeMkdir,
  safeMoveSync,
  safeReaddir,
  safeStat,
  safeWriteFile,
  listProjectRecords,
  validateHumanFinalDecision,
  withExecutionContext,
  type ApprovalRequestRecord,
} from '@agent/core';
import { defineScript, isDirectScript, ScriptExitError } from './lib/harness.js';

export const CLEANUP_APPROVAL_CHANNEL = 'terminal';
export const CLEANUP_EFFECT_BINDING = 'entity-governance-cleanup:soft-delete';

export interface CleanupFinding {
  kind: string;
  path: string;
  reason: string;
  action: 'retain' | 'soft_delete' | 'move_to_product_evolution' | 'adjudicate';
}

export interface CleanupReceipt {
  mission_id: string;
  mode: 'dry-run' | 'apply';
  approved_by?: string;
  approval_request_id?: string;
  generated_at: string;
  findings: CleanupFinding[];
  moved: Array<{ from: string; to: string }>;
  receipt_path?: string;
}

export interface OpenCleanupApprovalResult {
  missionId: string;
  created: boolean;
  requestId?: string;
  payloadHash?: string;
  findings: CleanupFinding[];
  reason?: string;
}

function dirs(root: string): string[] {
  if (!safeExistsSync(root)) return [];
  return safeReaddir(root).filter((entry) => {
    try {
      return safeStat(path.join(root, entry)).isDirectory();
    } catch {
      return false;
    }
  });
}

export function collectCleanupFindings(rootDir = pathResolver.rootDir()): CleanupFinding[] {
  const findings: CleanupFinding[] = [];
  const registeredProjectIds =
    path.resolve(rootDir) === path.resolve(pathResolver.rootDir())
      ? new Set(listProjectRecords().map((record) => record.project_id))
      : new Set<string>();
  const missionsRoot = path.join(rootDir, 'active/missions');
  for (const entry of dirs(missionsRoot)) {
    if (!['personal', 'confidential', 'public', 'ephemeral'].includes(entry)) {
      findings.push({
        kind: 'mission.non_tier_root',
        path: `active/missions/${entry}`,
        reason: 'mission is outside the governed tier tree',
        action: 'soft_delete',
      });
    }
  }
  for (const tier of ['personal', 'confidential', 'public']) {
    for (const entry of dirs(path.join(missionsRoot, tier))) {
      if (entry.startsWith('--') || entry === 'HELP' || entry === 'ID') {
        findings.push({
          kind: 'mission.invalid_id',
          path: `active/missions/${tier}/${entry}`,
          reason: 'flag-like mission id was generated by a CLI argument path',
          action: 'soft_delete',
        });
      }
    }
  }
  const projectRoot = path.join(rootDir, 'active/projects');
  for (const tier of ['personal', 'confidential', 'public']) {
    for (const tenantOrProject of dirs(path.join(projectRoot, tier))) {
      const scopedRoot = path.join(projectRoot, tier, tenantOrProject);
      for (const project of dirs(scopedRoot)) {
        if (project.startsWith('{{') || project.startsWith('MSN-')) {
          findings.push({
            kind: 'project.noncanonical_id',
            path: path.relative(rootDir, path.join(scopedRoot, project)).replaceAll(path.sep, '/'),
            reason: 'workspace name is a mission id or unresolved template, not a project id',
            action: 'soft_delete',
          });
        } else if (!registeredProjectIds.has(project)) {
          findings.push({
            kind: 'project.unregistered_workspace',
            path: path.relative(rootDir, path.join(scopedRoot, project)).replaceAll(path.sep, '/'),
            reason: 'workspace has no governed project registry record',
            action: 'soft_delete',
          });
        }
      }
    }
  }
  const legacyEvolutionRoot = path.join(rootDir, 'knowledge/evolution');
  for (const file of safeExistsSync(legacyEvolutionRoot) ? safeReaddir(legacyEvolutionRoot) : []) {
    if (file.startsWith('distill_')) {
      findings.push({
        kind: 'artifact.legacy_distill_root',
        path: `knowledge/evolution/${file}`,
        reason: 'distilled knowledge must be under knowledge/product/evolution/',
        action: 'adjudicate',
      });
    }
  }
  return findings.sort((a, b) => a.path.localeCompare(b.path));
}

export function buildCleanupApprovalPayload(
  missionId: string,
  findings: CleanupFinding[]
): Record<string, unknown> {
  return {
    mission_id: missionId.trim().toUpperCase(),
    findings: findings.map((finding) => ({ ...finding })),
    effect: CLEANUP_EFFECT_BINDING,
  };
}

export function computeCleanupApprovalPayloadHash(
  missionId: string,
  findings: CleanupFinding[]
): string {
  return computeApprovalPayloadHash(buildCleanupApprovalPayload(missionId, findings));
}

/** Open the EG-11 human approval without performing any cleanup. */
export function openCleanupApproval(input: {
  missionId: string;
  requestedBy?: string;
  rootDir?: string;
}): OpenCleanupApprovalResult {
  const missionId = input.missionId.trim().toUpperCase();
  const findings = collectCleanupFindings(input.rootDir || pathResolver.rootDir());
  const payloadHash = computeCleanupApprovalPayloadHash(missionId, findings);
  const existing = listApprovalRequests({
    storageChannels: [CLEANUP_APPROVAL_CHANNEL],
    kind: 'mission_gate',
    status: 'pending',
  }).find((record) => record.source?.missionId?.toUpperCase() === missionId);

  if (existing) {
    if (existing.accountability?.payloadHash === payloadHash) {
      return { missionId, created: false, requestId: existing.id, payloadHash, findings };
    }
    return {
      missionId,
      created: false,
      requestId: existing.id,
      payloadHash,
      findings,
      reason:
        `A pending EG-11 approval (${existing.id}) is bound to a different findings set. ` +
        'Cancel it before requesting approval for the changed cleanup scope.',
    };
  }

  const record = createApprovalRequest('mission_controller', {
    channel: CLEANUP_APPROVAL_CHANNEL,
    storageChannel: CLEANUP_APPROVAL_CHANNEL,
    threadTs: missionId,
    correlationId: `entity-governance-cleanup-${missionId}`,
    requestedBy: input.requestedBy || 'entity-governance-controller',
    kind: 'mission_gate',
    draft: {
      title: `EG-11 cleanup approval: ${missionId}`,
      summary: 'Approve the reviewed entity-governance cleanup findings.',
      details: JSON.stringify(findings, null, 2),
      severity: 'high',
    },
    source: { missionId },
    requestedByContext: {
      surface: 'terminal',
      actorId: input.requestedBy || 'entity-governance-controller',
      actorRole: 'mission_controller',
      missionId,
    },
    justification: {
      reason: 'EG-11 one-time cleanup of findings produced by the governed checker.',
      impactSummary: 'Only recoverable archive moves and governed evolution moves are permitted.',
      requestedEffects: [CLEANUP_EFFECT_BINDING],
    },
    risk: {
      level: 'critical',
      restartScope: 'manual',
      requiresStrongAuth: true,
      policyId: 'EG-11',
    },
    workflow: {
      workflowId: `eg-11-${missionId}`,
      mode: 'all_required',
      requiredRoles: ['sovereign'],
      stages: [],
      approvals: [{ role: 'sovereign', status: 'pending' }],
    },
    accountability: {
      finalDecision: 'human_only',
      payloadHash,
      effectBinding: CLEANUP_EFFECT_BINDING,
    },
  });

  return { missionId, created: true, requestId: record.id, payloadHash, findings };
}

function assertCleanupApproval(
  approvalRequestId: string,
  missionId: string,
  findings: CleanupFinding[]
): ApprovalRequestRecord {
  const approval = loadApprovalRequest(CLEANUP_APPROVAL_CHANNEL, approvalRequestId);
  const humanApproval = approval?.workflow?.approvals?.find(
    (entry) =>
      entry.status === 'approved' && entry.decidedByType === 'human' && entry.authenticated === true
  );
  if (!approval || approval.kind !== 'mission_gate' || approval.status !== 'approved') {
    throw new Error(
      `[POLICY_VIOLATION] EG-11 requires an approved mission_gate request: ${approvalRequestId}`
    );
  }
  if (approval.source?.missionId?.toUpperCase() !== missionId.trim().toUpperCase()) {
    throw new Error('[POLICY_VIOLATION] EG-11 approval is bound to a different mission');
  }
  if (approval.accountability?.effectBinding !== CLEANUP_EFFECT_BINDING) {
    throw new Error('[POLICY_VIOLATION] EG-11 approval is not bound to the cleanup effect');
  }
  if (
    approval.accountability?.payloadHash !== computeCleanupApprovalPayloadHash(missionId, findings)
  ) {
    throw new Error('[POLICY_VIOLATION] EG-11 approval is bound to a different findings set');
  }
  if (!humanApproval) {
    throw new Error('[POLICY_VIOLATION] EG-11 requires an authenticated human workflow approval');
  }
  validateHumanFinalDecision({
    accountability: approval.accountability,
    decidedByType: humanApproval.decidedByType,
    authenticated: humanApproval.authenticated,
    authMethod: humanApproval.authMethod,
    payloadHash: humanApproval.payloadHash,
    effectBinding: humanApproval.effectBinding,
  });
  return approval;
}

export function runCleanup(input: {
  missionId: string;
  apply?: boolean;
  approvalRequestId?: string;
  rootDir?: string;
}): CleanupReceipt {
  const rootDir = input.rootDir || pathResolver.rootDir();
  const findings = collectCleanupFindings(rootDir);
  const approval = input.apply
    ? input.approvalRequestId
      ? assertCleanupApproval(input.approvalRequestId, input.missionId, findings)
      : (() => {
          throw new Error('--approval-request-id is required with --apply');
        })()
    : undefined;
  const moved: CleanupReceipt['moved'] = [];
  const receipt: CleanupReceipt = {
    mission_id: input.missionId,
    mode: input.apply ? 'apply' : 'dry-run',
    ...(approval?.decidedBy ? { approved_by: approval.decidedBy } : {}),
    ...(approval ? { approval_request_id: approval.id } : {}),
    generated_at: new Date().toISOString(),
    findings,
    moved,
  };
  if (input.apply) {
    const trashRoot = path.join(rootDir, 'active/archive/.trash', `eg-${Date.now().toString(36)}`);
    // The lifecycle role owns the cleanup ceremony, while the explicit
    // sovereign persona is required for the recoverable archive root. Keep
    // both identities visible to secure-io; do not bypass the policy gate.
    withExecutionContext(
      'mission_controller',
      () => {
        safeMkdir(trashRoot, { recursive: true });
        for (const finding of findings.filter((entry) => entry.action === 'soft_delete')) {
          const source = path.join(rootDir, finding.path);
          if (!safeExistsSync(source)) continue;
          const destination = path.join(trashRoot, finding.path);
          safeMkdir(path.dirname(destination), { recursive: true });
          safeMoveSync(source, destination);
          moved.push({
            from: finding.path,
            to: path.relative(rootDir, destination).replaceAll(path.sep, '/'),
          });
        }
        for (const finding of findings.filter(
          (entry) => entry.action === 'adjudicate' && entry.kind === 'artifact.legacy_distill_root'
        )) {
          const source = path.join(rootDir, finding.path);
          if (!safeExistsSync(source)) continue;
          const destination = path.join(
            rootDir,
            'knowledge/product/evolution',
            path.basename(source)
          );
          if (safeExistsSync(destination)) {
            throw new Error(
              `Refusing to overwrite existing evolution artifact: ${path.relative(rootDir, destination)}`
            );
          }
          safeMkdir(path.dirname(destination), { recursive: true });
          safeMoveSync(source, destination);
          moved.push({
            from: finding.path,
            to: path.relative(rootDir, destination).replaceAll(path.sep, '/'),
          });
        }
        const evidenceDir =
          (path.resolve(rootDir) === path.resolve(pathResolver.rootDir())
            ? missionEvidenceDir(input.missionId)
            : undefined) ||
          path.join(rootDir, 'active/missions/confidential', input.missionId, 'evidence');
        safeMkdir(evidenceDir, { recursive: true });
        const receiptPath = path.join(evidenceDir, 'entity-governance-cleanup-receipt.json');
        receipt.receipt_path = path.relative(rootDir, receiptPath).replaceAll(path.sep, '/');
        safeWriteFile(receiptPath, JSON.stringify(receipt, null, 2));
      },
      'sovereign'
    );
  } else {
    const receiptPath = pathResolver.sharedTmp(
      path.join('entity-governance-cleanup', input.missionId, 'dry-run-receipt.json')
    );
    safeMkdir(path.dirname(receiptPath), { recursive: true });
    receipt.receipt_path = path.relative(rootDir, receiptPath).replaceAll(path.sep, '/');
    safeWriteFile(receiptPath, JSON.stringify(receipt, null, 2));
  }
  return receipt;
}

export function main(argv: string[] = []): void {
  const missionIndex = argv.indexOf('--mission-id');
  const missionId = missionIndex >= 0 ? argv[missionIndex + 1] : 'MSN-EG-20260809B';
  const apply = argv.includes('--apply');
  const requestApproval = argv.includes('--request-approval');
  const approvalIndex = argv.indexOf('--approval-request-id');
  const approvalRequestId = approvalIndex >= 0 ? argv[approvalIndex + 1] : undefined;
  const requestedByIndex = argv.indexOf('--requested-by');
  const requestedBy = requestedByIndex >= 0 ? argv[requestedByIndex + 1] : undefined;
  if (requestApproval) {
    const result = openCleanupApproval({ missionId, ...(requestedBy ? { requestedBy } : {}) });
    console.log(JSON.stringify(result, null, 2));
    if (result.reason) throw new ScriptExitError(1, '', true);
    return;
  }
  const receipt = runCleanup({ missionId, apply, approvalRequestId });
  console.log(JSON.stringify(receipt, null, 2));
}

export const runEntityGovernanceCleanup = defineScript({
  name: 'entity:cleanup',
  flags: [],
  run: ({ argv }) => main(argv),
});

if (
  isDirectScript(import.meta.url, 'entity_governance_cleanup.ts') ||
  isDirectScript(import.meta.url, 'entity_governance_cleanup.js')
)
  void runEntityGovernanceCleanup();
