/** EG-11: one-time cleanup mission. Dry-run is the default; apply is an
 * explicitly approved, soft-delete-only operation with an evidence receipt. */
import * as path from 'node:path';
import {
  missionEvidenceDir,
  pathResolver,
  safeExistsSync,
  safeMkdir,
  safeMoveSync,
  safeReaddir,
  safeStat,
  safeWriteFile,
  listProjectRecords,
  withExecutionContext,
} from '@agent/core';

export interface CleanupFinding {
  kind: string;
  path: string;
  reason: string;
  action: 'retain' | 'soft_delete' | 'move_to_product_evolution' | 'adjudicate';
}

export interface CleanupReceipt {
  mission_id: string;
  mode: 'dry-run' | 'apply';
  approved_by?: string;
  generated_at: string;
  findings: CleanupFinding[];
  moved: Array<{ from: string; to: string }>;
  receipt_path?: string;
}

function dirs(root: string): string[] {
  if (!safeExistsSync(root)) return [];
  return safeReaddir(root).filter((entry) => {
    try {
      return safeStat(path.join(root, entry)).isDirectory();
    } catch {
      return false;
    }
  });
}

export function collectCleanupFindings(rootDir = pathResolver.rootDir()): CleanupFinding[] {
  const findings: CleanupFinding[] = [];
  const registeredProjectIds =
    path.resolve(rootDir) === path.resolve(pathResolver.rootDir())
      ? new Set(listProjectRecords().map((record) => record.project_id))
      : new Set<string>();
  const missionsRoot = path.join(rootDir, 'active/missions');
  for (const entry of dirs(missionsRoot)) {
    if (!['personal', 'confidential', 'public', 'ephemeral'].includes(entry)) {
      findings.push({
        kind: 'mission.non_tier_root',
        path: `active/missions/${entry}`,
        reason: 'mission is outside the governed tier tree',
        action: 'soft_delete',
      });
    }
  }
  for (const tier of ['personal', 'confidential', 'public']) {
    for (const entry of dirs(path.join(missionsRoot, tier))) {
      if (entry.startsWith('--') || entry === 'HELP' || entry === 'ID') {
        findings.push({
          kind: 'mission.invalid_id',
          path: `active/missions/${tier}/${entry}`,
          reason: 'flag-like mission id was generated by a CLI argument path',
          action: 'soft_delete',
        });
      }
    }
  }
  const projectRoot = path.join(rootDir, 'active/projects');
  for (const tier of ['personal', 'confidential', 'public']) {
    for (const tenantOrProject of dirs(path.join(projectRoot, tier))) {
      const scopedRoot = path.join(projectRoot, tier, tenantOrProject);
      for (const project of dirs(scopedRoot)) {
        if (project.startsWith('{{') || project.startsWith('MSN-')) {
          findings.push({
            kind: 'project.noncanonical_id',
            path: path.relative(rootDir, path.join(scopedRoot, project)).replaceAll(path.sep, '/'),
            reason: 'workspace name is a mission id or unresolved template, not a project id',
            action: 'soft_delete',
          });
        } else if (!registeredProjectIds.has(project)) {
          findings.push({
            kind: 'project.unregistered_workspace',
            path: path.relative(rootDir, path.join(scopedRoot, project)).replaceAll(path.sep, '/'),
            reason: 'workspace has no governed project registry record',
            action: 'soft_delete',
          });
        }
      }
    }
  }
  const legacyEvolutionRoot = path.join(rootDir, 'knowledge/evolution');
  for (const file of safeExistsSync(legacyEvolutionRoot) ? safeReaddir(legacyEvolutionRoot) : []) {
    if (file.startsWith('distill_')) {
      findings.push({
        kind: 'artifact.legacy_distill_root',
        path: `knowledge/evolution/${file}`,
        reason: 'distilled knowledge must be under knowledge/product/evolution/',
        action: 'adjudicate',
      });
    }
  }
  return findings.sort((a, b) => a.path.localeCompare(b.path));
}

export function runCleanup(input: {
  missionId: string;
  apply?: boolean;
  approvedBy?: string;
  rootDir?: string;
}): CleanupReceipt {
  if (input.apply && !input.approvedBy?.trim())
    throw new Error('--approved-by is required with --apply');
  const rootDir = input.rootDir || pathResolver.rootDir();
  const findings = collectCleanupFindings(rootDir);
  const moved: CleanupReceipt['moved'] = [];
  const receipt: CleanupReceipt = {
    mission_id: input.missionId,
    mode: input.apply ? 'apply' : 'dry-run',
    ...(input.approvedBy ? { approved_by: input.approvedBy } : {}),
    generated_at: new Date().toISOString(),
    findings,
    moved,
  };
  if (input.apply) {
    const trashRoot = path.join(rootDir, 'active/archive/.trash', `eg-${Date.now().toString(36)}`);
    // The lifecycle role owns the cleanup ceremony, while the explicit
    // sovereign persona is required for the recoverable archive root. Keep
    // both identities visible to secure-io; do not bypass the policy gate.
    withExecutionContext(
      'mission_controller',
      () => {
        safeMkdir(trashRoot, { recursive: true });
        for (const finding of findings.filter((entry) => entry.action === 'soft_delete')) {
          const source = path.join(rootDir, finding.path);
          if (!safeExistsSync(source)) continue;
          const destination = path.join(trashRoot, finding.path);
          safeMkdir(path.dirname(destination), { recursive: true });
          safeMoveSync(source, destination);
          moved.push({
            from: finding.path,
            to: path.relative(rootDir, destination).replaceAll(path.sep, '/'),
          });
        }
        for (const finding of findings.filter(
          (entry) => entry.action === 'adjudicate' && entry.kind === 'artifact.legacy_distill_root'
        )) {
          const source = path.join(rootDir, finding.path);
          if (!safeExistsSync(source)) continue;
          const destination = path.join(
            rootDir,
            'knowledge/product/evolution',
            path.basename(source)
          );
          if (safeExistsSync(destination)) {
            throw new Error(
              `Refusing to overwrite existing evolution artifact: ${path.relative(rootDir, destination)}`
            );
          }
          safeMkdir(path.dirname(destination), { recursive: true });
          safeMoveSync(source, destination);
          moved.push({
            from: finding.path,
            to: path.relative(rootDir, destination).replaceAll(path.sep, '/'),
          });
        }
        const evidenceDir =
          missionEvidenceDir(input.missionId) ||
          path.join(rootDir, 'active/missions/confidential', input.missionId, 'evidence');
        safeMkdir(evidenceDir, { recursive: true });
        const receiptPath = path.join(evidenceDir, 'entity-governance-cleanup-receipt.json');
        receipt.receipt_path = path.relative(rootDir, receiptPath).replaceAll(path.sep, '/');
        safeWriteFile(receiptPath, JSON.stringify(receipt, null, 2));
      },
      'sovereign'
    );
  } else {
    const receiptPath = pathResolver.sharedTmp(
      path.join('entity-governance-cleanup', input.missionId, 'dry-run-receipt.json')
    );
    safeMkdir(path.dirname(receiptPath), { recursive: true });
    receipt.receipt_path = path.relative(rootDir, receiptPath).replaceAll(path.sep, '/');
    safeWriteFile(receiptPath, JSON.stringify(receipt, null, 2));
  }
  return receipt;
}

export function main(argv = process.argv.slice(2)): void {
  const missionIndex = argv.indexOf('--mission-id');
  const approvalIndex = argv.indexOf('--approved-by');
  const missionId = missionIndex >= 0 ? argv[missionIndex + 1] : 'MSN-EG-20260809B';
  const apply = argv.includes('--apply');
  const approvedBy = approvalIndex >= 0 ? argv[approvalIndex + 1] : undefined;
  const receipt = runCleanup({ missionId, apply, approvedBy });
  console.log(JSON.stringify(receipt, null, 2));
}

if (
  process.argv[1]?.endsWith('entity_governance_cleanup.ts') ||
  process.argv[1]?.endsWith('entity_governance_cleanup.js')
)
  main();
