#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { compileFromFile } = require('json-schema-to-typescript');
const { logger } = require('../libs/core/core.cjs');

const schemasDir = path.resolve(__dirname, '../schemas');
const typesDir = path.resolve(__dirname, '../libs/core/src/types');

if (!fs.existsSync(typesDir)) {
  fs.mkdirSync(typesDir, { recursive: true });
}

async function generate() {
  if (!fs.existsSync(schemasDir)) {
    logger.info('No schemas directory found.');
    return;
  }

  const files = fs.readdirSync(schemasDir).filter((f) => f.endsWith('.schema.json'));
  let count = 0;

  for (const file of files) {
    const name = path.basename(file, '.schema.json');
    const tsFile = path.join(typesDir, `${name}.ts`);

    try {
      const ts = await compileFromFile(path.join(schemasDir, file), {
        bannerComment: `/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run \`npm run generate:types\` to regenerate this file.
 */`,
        style: { singleQuote: true },
      });
      fs.writeFileSync(tsFile, ts);
      logger.success(`Generated types for ${name}`);
      count++;
    } catch (err) {
      logger.error(`Failed to generate types for ${name}: ${err.message}`);
    }
  }

  // Create index.ts
  if (count > 0) {
    const indexContent = files
      .map((f) => {
        const name = path.basename(f, '.schema.json');
        return `export * from './${name}';`;
      })
      .join('\\n');
    fs.writeFileSync(path.join(typesDir, 'index.ts'), indexContent + '\\n');
    logger.success('Generated types/index.ts');
  }
}

generate();
