import * as path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { pathResolver } from '@agent/core/path-resolver';
import { safeExistsSync, safeReadFile, safeRmSync } from '@agent/core/secure-io';
import { renderProjectOs, runGenerateProjectOs } from './generate_project_os.js';

const OUTPUT_RELATIVE_PATH = 'active/shared/tmp/project-os-generator-test';
const OUTPUT_PATH = pathResolver.rootResolve(OUTPUT_RELATIVE_PATH);

describe('generate_project_os', () => {
  afterEach(() => {
    safeRmSync(OUTPUT_PATH, { recursive: true, force: true });
    process.exitCode = undefined;
  });

  it('uses the foundation text reader for blueprint source files', () => {
    const source = String(
      safeReadFile(pathResolver.rootResolve('scripts/generate_project_os.ts'), {
        encoding: 'utf8',
      }) || ''
    );

    expect(source).toContain("readTextFile, slugify } from '@agent/core/foundation'");
    expect(source).not.toContain('safeReadFile(sourcePath');
  });

  it('renders deterministic files without writing during planning', () => {
    const files = renderProjectOs([
      '--',
      '--name',
      'Sample Project',
      '--out',
      OUTPUT_RELATIVE_PATH,
    ]);

    expect(files.length).toBeGreaterThan(1);
    expect(files.some((file) => file.path === path.join(OUTPUT_PATH, 'README.md'))).toBe(true);
    expect(files.every((file) => file.path.startsWith(`${OUTPUT_PATH}${path.sep}`))).toBe(true);
    expect(files.find((file) => file.path.endsWith('README.md'))?.content).toContain(
      '<!-- Generated by project-os:init -->'
    );
    expect(files.find((file) => file.path.endsWith('README.md'))?.content).not.toMatch(
      /Generated: \d{4}-\d{2}-\d{2}/u
    );
    expect(files.find((file) => file.path.endsWith('project-charter.md'))?.content).toContain(
      'Source blueprint: knowledge/public/templates/blueprints/project-charter.md'
    );
    expect(safeExistsSync(OUTPUT_PATH)).toBe(false);
  });

  it('writes dynamic outputs and rechecks them through the shared generator', async () => {
    const args = ['--', '--name', 'Sample Project', '--out', OUTPUT_RELATIVE_PATH, '--quiet'];
    const generated = await runGenerateProjectOs(args);

    expect(generated?.changed.length).toBeGreaterThan(1);
    expect(safeExistsSync(path.join(OUTPUT_PATH, 'README.md'))).toBe(true);

    const checked = await runGenerateProjectOs([...args, '--check']);

    expect(checked?.changed).toEqual([]);
    expect(
      String(safeReadFile(path.join(OUTPUT_PATH, 'README.md'), { encoding: 'utf8' }))
    ).toContain('# Sample Project Project Operating System');
    expect(process.exitCode).toBeUndefined();
  });

  it('rejects an output directory outside the repository', () => {
    expect(() =>
      renderProjectOs(['--', '--name', 'Sample Project', '--out', '/tmp/project-os'])
    ).toThrow('[RESOURCE_PATH_SCOPE]');
  });
});
