const fs = require('fs');
const path = require('path');
const { metrics } = require('../libs/core/metrics.cjs');

const rootDir = path.resolve(__dirname, '..');
const indexFile = path.join(rootDir, 'knowledge/orchestration/global_skill_index.json');
const outputFile = path.join(rootDir, 'SKILLS_GUIDE.md');

function generate() {
  if (!fs.existsSync(indexFile)) return;
  const index = JSON.parse(fs.readFileSync(indexFile, 'utf8'));
  const skills = index.s || index.skills;
  const total = index.t || index.total_skills;

  // Load historical performance data
  const history = metrics.reportFromHistory();
  const metricsMap = new Map();
  history.skills.forEach((s) => metricsMap.set(s.skill, s));

  let md = '# Gemini Skills Ecosystem Guide\n\n';
  md += `Total Skills: ${total} (Implemented: ${skills.filter((s) => (s.s || s.status) === 'impl').length})\n`;
  md += `Last updated: ${new Date().toISOString().split('T')[0].replace(/-/g, '/')}\n\n`;
  md +=
    'This guide is a domain-driven catalog of the ecosystem. Skills are organized into Namespaces for better governance and accountability.\n\n';

  // Grouping logic
  const groups = {};
  skills.forEach((skill) => {
    const skillPath = skill.path || skill.n;
    const parts = skillPath.split('/');
    const category = parts.length > 1 ? parts[1] : 'General';
    if (!groups[category]) groups[category] = [];
    groups[category].push(skill);
  });

  const categoryDescriptions = {
    core: 'Fundamental orchestrators and self-evolution mechanisms.',
    engineering: 'Development, implementation, and architectural refactoring tools.',
    audit: 'Security, quality, and compliance scanning based on IPA/FISC standards.',
    connector: 'Enterprise tool integrations (Jira, Slack, Box).',
    media: 'Professional document extraction and media asset generation.',
    intelligence: 'Knowledge harvesting and 3-tier memory management.',
    ux: 'Human-centric UI/UX auditing and voice interface control.',
    business: 'Strategy, financial modeling, and executive reporting.',
    utilities: 'Shared helpers, background daemons, and general utilities.',
  };

  Object.keys(groups)
    .sort()
    .forEach((cat) => {
      md += `## 📂 ${cat.toUpperCase()}\n`;
      md += `> ${categoryDescriptions[cat] || 'General purpose skills.'}\n\n`;
      md += '| Skill | Description | Score | Avg Time | Usage |\n';
      md += '| :--- | :--- | :--- | :--- | :--- |\n';

      groups[cat]
        .sort((a, b) => (a.n || a.name).localeCompare(b.n || b.name))
        .forEach((skill) => {
          const name = skill.n || skill.name;
          const desc = skill.d || skill.description;
          const usage = `\`npm run cli -- run ${name}\``;
          const m = metricsMap.get(name);

          let scoreStr = 'N/A';
          let timeStr = '-';

          if (m) {
            const TIME_BASE = 5000;
            const MEM_BASE = 200;
            const timeImpact = Math.min(50, (m.avgMs / TIME_BASE) * 50);
            const memImpact = m.peakHeapMB ? Math.min(50, (m.peakHeapMB / MEM_BASE) * 50) : 0;
            const score = Math.max(0, Math.round(100 - (timeImpact + memImpact)));
            scoreStr = score + (score < 70 ? ' ⚠️' : ' ✅');
            timeStr = m.avgMs + 'ms';
          }

          md += `| **${name}** | ${desc} | ${scoreStr} | ${timeStr} | ${usage} |\n`;
        });
      md += '\n';
    });

  md += '---\n*Generated by Ecosystem Architect Tool | Based on Hierarchical Namespace Model v1.0*';

  fs.writeFileSync(outputFile, md);
  console.log(`[SUCCESS] Guide re-generated at ${outputFile}`);
}

generate();
