import * as path from 'node:path';
import { compileFromFile } from 'json-schema-to-typescript';

type SafeWriteFn = (filePath: string, data: string | Buffer, options?: Record<string, unknown>) => void;

interface GenerationTarget {
  schemaPath: string;
  outputPath: string;
}

const targets: GenerationTarget[] = [
  {
    schemaPath: 'schemas/bridge-request.schema.json',
    outputPath: 'libs/core/src/types/bridge-request.ts',
  },
  {
    schemaPath: 'schemas/diagram-adf.schema.json',
    outputPath: 'libs/core/src/types/diagram-adf.ts',
  },
  {
    schemaPath: 'schemas/mission-contract.schema.json',
    outputPath: 'libs/core/src/types/mission-contract.ts',
  },
  {
    schemaPath: 'schemas/skill-input.schema.json',
    outputPath: 'libs/core/src/types/skill-input.ts',
  },
  {
    schemaPath: 'schemas/skill-output.schema.json',
    outputPath: 'libs/core/src/types/skill-output.ts',
  },
  {
    schemaPath: 'knowledge/public/schemas/architecture-adf.schema.json',
    outputPath: 'libs/core/src/types/architecture-adf.ts',
  },
];

async function main(): Promise<void> {
  const secureIoModule = await import('../libs/core/secure-io.js');
  const safeWriteFile = ((secureIoModule as any).safeWriteFile ||
    (secureIoModule as any).default?.safeWriteFile) as SafeWriteFn | undefined;

  if (!safeWriteFile) {
    throw new Error('secure-io safeWriteFile export not found');
  }

  for (const target of targets) {
    const schemaPath = path.resolve(process.cwd(), target.schemaPath);
    const outputPath = path.resolve(process.cwd(), target.outputPath);
    const compiled = await compileFromFile(schemaPath, {
      bannerComment:
        '/* tslint:disable */\n' +
        '/* eslint-disable */\n' +
        '/**\n' +
        ' * This file was automatically generated by json-schema-to-typescript.\n' +
        ' * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n' +
        ' * and run `pnpm generate:types` to regenerate this file.\n' +
        ' */',
      style: {
        semi: true,
        singleQuote: true,
      },
    });
    safeWriteFile(outputPath, compiled);
    console.log(`[generate:types] ${target.outputPath}`);
  }
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
