const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const indexFile = path.join(rootDir, 'knowledge/orchestration/global_skill_index.json');
const outputFile = path.join(rootDir, 'SKILLS_GUIDE.md');

function generate() {
    if (!fs.existsSync(indexFile)) return;
    const index = JSON.parse(fs.readFileSync(indexFile, 'utf8'));
    
    let md = '# Gemini Skills Ecosystem Guide\n\n';
    md += 'Total Skills: ' + index.total_skills + '\n';
    md += 'Last updated: ' + new Date().toLocaleDateString() + '\n\n';
    md += 'This guide is automatically generated from the monorepo source.\n\n';

    md += '## Available Skills\n\n';
    md += '| Skill | Description | Usage |\n';
    md += '| :--- | :--- | :--- |\n';

    index.skills.sort((a, b) => a.name.localeCompare(b.name)).forEach(skill => {
        const usage = '`npm run cli -- execute ' + skill.name + '`';
        md += '| **' + skill.name + '** | ' + skill.description + ' | ' + usage + ' |\n';
    });

    md += '\n---\n*Generated by Ecosystem Architect Tool*';
    
    fs.writeFileSync(outputFile, md);
    console.log('[SUCCESS] Guide generated at ' + outputFile);
}

generate();