/** Generate artifact vocabulary directly from its canonical schema. */
import { compile } from 'json-schema-to-typescript';
import { readJson } from '@agent/core/foundation';
import { pathResolver } from '@agent/core/path-resolver';
import { defineGenerator, isDirectScript } from './lib/harness.js';

export function createArtifactKindGenerator(
  schemaPath = pathResolver.knowledge('product/schemas/artifact-kind.schema.json'),
  outputPath = pathResolver.rootResolve('libs/core/workforce/artifact-kind.generated.ts')
) {
  return defineGenerator({
    id: 'artifact-kinds',
    outputs: [outputPath],
    render() {
      return [renderArtifactKinds(schemaPath, outputPath)];
    },
  });
}

function renderArtifactKinds(schemaPath: string, outputPath: string) {
  const schema = readJson<{ enum?: unknown }>(schemaPath);
  if (
    !Array.isArray(schema.enum) ||
    !schema.enum.length ||
    schema.enum.some((kind) => typeof kind !== 'string' || !kind.trim()) ||
    new Set(schema.enum).size !== schema.enum.length
  ) {
    throw new Error('Artifact kind schema must contain a nonempty unique string enum');
  }
  const kinds = [...schema.enum].sort();
  const content = [
    '// Generated by pnpm kyberion generate artifact-kinds. Do not edit.',
    'export const ARTIFACT_KINDS = [',
    ...kinds.map((kind) => '  ' + JSON.stringify(kind) + ','),
    '] as const;',
    'export type ArtifactKind = (typeof ARTIFACT_KINDS)[number];',
    '',
  ].join('\n');
  return { path: outputPath, content };
}

const intentOutput = pathResolver.rootResolve('libs/core/intent/standard-intents.generated.ts');
const workPolicyOutput = pathResolver.rootResolve('libs/core/workforce/work-policy.generated.ts');
const artifactOutput = pathResolver.rootResolve('libs/core/workforce/artifact-kind.generated.ts');
export const main = defineGenerator({
  id: 'artifact-kinds',
  outputs: [artifactOutput, intentOutput, workPolicyOutput],
  async render() {
    const artifact = renderArtifactKinds(
      pathResolver.knowledge('product/schemas/artifact-kind.schema.json'),
      artifactOutput
    );
    const schema = readJson<any>(
      pathResolver.knowledge('product/schemas/standard-intents.schema.json')
    );
    const content = await compile(
      { ...schema, title: 'StandardIntentCatalog' },
      'StandardIntentCatalog',
      {
        bannerComment: '// Generated by pnpm kyberion generate artifact-kinds. Do not edit.',
        additionalProperties: false,
      }
    );
    const aliases = [
      'export type StandardIntentDefinition = StandardIntentCatalog["intents"][number];',
      ...Object.entries({
        Category: 'category',
        Target: 'target',
        Action: 'action',
        ExecutionShape: 'execution_shape',
        MissionClass: 'mission_class',
        RiskProfile: 'risk_profile',
      }).map(
        ([name, field]) =>
          'export type StandardIntent' +
          name +
          ' = StandardIntentDefinition[' +
          JSON.stringify(field) +
          '];'
      ),
      'export type StandardIntentResolution = NonNullable<StandardIntentDefinition["resolution"]>;',
      'export type StandardIntentPipelineStep = NonNullable<StandardIntentDefinition["pipeline"]>[number];',
      '',
    ].join('\n');
    const workPolicy = readJson<any>(
      pathResolver.knowledge('product/schemas/work-policy.schema.json')
    );
    const policyContent = await compile(
      { ...workPolicy, title: 'WorkPolicyFile' },
      'WorkPolicyFile',
      {
        bannerComment: '// Generated by pnpm kyberion generate artifact-kinds. Do not edit.',
        additionalProperties: false,
      }
    );
    return [
      artifact,
      { path: intentOutput, content: content + '\n' + aliases },
      { path: workPolicyOutput, content: policyContent },
    ];
  },
});
if (
  isDirectScript(import.meta.url, 'generate_artifact_kinds.ts') ||
  isDirectScript(import.meta.url, 'generate_artifact_kinds.js')
)
  void main();
