import * as path from 'node:path';
import { loadProjectOperatingSystemArtifactMap } from '@agent/core/project-management';
import { pathResolver } from '@agent/core/path-resolver';
import { assertSafeRepositoryPath, safeExistsSync, safeLstat } from '@agent/core/secure-io';
import { readTextFile, slugify } from '@agent/core/foundation';
import {
  defineGenerator,
  isDirectScript,
  type GeneratedFile,
  type ScriptContext,
} from './lib/harness.js';

const BLUEPRINT_BY_ARTIFACT: Record<string, string> = {
  'project-charter': 'project-charter.md',
  'business-impact-analysis': 'business-impact-analysis.md',
  'stakeholder-communication-register': 'stakeholder-communication-register.md',
  'requirements-definition': 'requirements-definition.md',
  'slo-sli-definition': 'slo-sli-definition.md',
  'information-asset-registry': 'information-asset-registry.md',
  'basic-design': 'basic-design.md',
  'architecture-design': 'architecture-design.md',
  'detailed-design': 'detailed-design.md',
  'operational-design': 'operational-design.md',
  'data-flow-lifecycle-map': 'data-flow-lifecycle-map.md',
  'operation-runbook': 'operation-runbook.md',
  'environment-setup-guide': 'environment-setup-guide.md',
  'project-management-plan': 'project-management-plan.md',
  'mission-ledger': 'mission-ledger.md',
  'raid-log': 'raid-log.md',
  'issue-log': 'issue-log.md',
  'change-control-ledger': 'change-control-ledger.md',
  'gate-review-packet': 'gate-review-packet.md',
  'test-plan': 'test-plan.md',
  'test-validation-report': 'test-validation-report.md',
  'security-audit-report': 'security-audit-report.md',
  'cutover-migration-plan': 'cutover-migration-plan.md',
  'user-manual-faq': 'user-manual-faq.md',
  'incident-report': 'incident-report.md',
  'mission-closure-report': 'mission-closure-report.md',
};

const PHASE_DIR_BY_NAME: Record<string, string> = {
  initiate: '01_initiate',
  define: '02_define',
  design: '03_design',
  build: '04_control',
  validate: '05_validate',
  transfer_run: '06_transfer_run',
};

function renderProjectReadme(
  projectName: string,
  lifecycle: ReturnType<typeof loadProjectOperatingSystemArtifactMap>['lifecycle']
): string {
  const lines = [
    `# ${projectName} Project Operating System`,
    '',
    '<!-- Generated by project-os:init -->',
    '',
    '## Structure',
    '',
  ];

  for (const phase of lifecycle) {
    const phaseDir = PHASE_DIR_BY_NAME[phase.phase] || phase.phase;
    lines.push(`- ${phaseDir}`);
    for (const artifact of phase.required) {
      const fileName = BLUEPRINT_BY_ARTIFACT[artifact];
      if (!fileName) continue;
      lines.push(`  - ${path.posix.join(phaseDir, fileName)}`);
    }
  }

  lines.push(
    '',
    '## Notes',
    '',
    '- Instantiate placeholders for this project.',
    '- Link requirements, design, test, and gate evidence explicitly.'
  );
  return `${lines.join('\n')}\n`;
}

interface ProjectOsArguments {
  projectName: string;
  targetDir: string;
}

function readOptionValue(
  argv: readonly string[],
  index: number,
  option: string,
  aliases: readonly string[]
): { value?: string; nextIndex: number; matched: boolean } {
  const arg = argv[index];
  const names = [option, ...aliases];
  const inlineName = names.find((name) => arg.startsWith(`${name}=`));
  if (inlineName) {
    return { value: arg.slice(inlineName.length + 1), nextIndex: index, matched: true };
  }
  if (!names.includes(arg)) return { nextIndex: index, matched: false };
  const value = argv[index + 1];
  if (!value || value.startsWith('-')) {
    throw new Error(`Missing value for ${option}`);
  }
  return { value, nextIndex: index + 1, matched: true };
}

function parseProjectOsArguments(argv: readonly string[]): ProjectOsArguments {
  let projectName: string | undefined;
  let outputPath: string | undefined;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (
      arg === '--' ||
      arg === '--json' ||
      arg === '--dry-run' ||
      arg === '--check' ||
      arg === '--quiet'
    )
      continue;

    const name = readOptionValue(argv, index, '--name', ['-n']);
    if (name.matched) {
      projectName = name.value;
      index = name.nextIndex;
      continue;
    }

    const out = readOptionValue(argv, index, '--out', ['-o']);
    if (out.matched) {
      outputPath = out.value;
      index = out.nextIndex;
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  const normalizedName = projectName?.trim();
  if (!normalizedName) throw new Error('Missing required argument: --name');

  const slug = slugify(normalizedName, { fallback: 'project-os' });
  const targetDir = outputPath
    ? assertSafeRepositoryPath(pathResolver.rootResolve(outputPath), { allowMissingLeaf: true })
    : pathResolver.sharedTmp(path.join('project-os', slug));
  return { projectName: normalizedName, targetDir };
}

function renderInstantiatedBlueprint(
  projectName: string,
  sourceBlueprint: string,
  content: string
): string {
  return [
    `<!-- Generated by project-os:init for ${projectName} -->`,
    `<!-- Source blueprint: ${sourceBlueprint} -->`,
    '',
    `> Project: ${projectName}`,
    '',
    content,
    '',
  ].join('\n');
}

export function renderProjectOs(argv: readonly string[]): GeneratedFile[] {
  const { projectName, targetDir } = parseProjectOsArguments(argv);
  const artifactMap = loadProjectOperatingSystemArtifactMap();
  const blueprintsRoot = pathResolver.knowledge('public/templates/blueprints');
  const files: GeneratedFile[] = [];

  for (const phase of artifactMap.lifecycle) {
    const phaseDirName = PHASE_DIR_BY_NAME[phase.phase] || phase.phase;
    const phaseDir = path.join(targetDir, phaseDirName);

    for (const artifact of phase.required) {
      const blueprintName = BLUEPRINT_BY_ARTIFACT[artifact];
      if (!blueprintName) continue;

      const sourcePath = path.join(blueprintsRoot, blueprintName);
      if (!safeExistsSync(sourcePath) || !safeLstat(sourcePath).isFile()) continue;

      const targetPath = path.join(phaseDir, blueprintName);
      const content = readTextFile(sourcePath);
      const sourceReference = path
        .relative(pathResolver.rootDir(), sourcePath)
        .split(path.sep)
        .join('/');
      files.push({
        path: targetPath,
        content: renderInstantiatedBlueprint(projectName, sourceReference, content),
      });
    }
  }

  const readmePath = path.join(targetDir, 'README.md');
  files.push({
    path: readmePath,
    content: renderProjectReadme(projectName, artifactMap.lifecycle),
  });
  return files;
}

export const runGenerateProjectOs = defineGenerator({
  id: 'project-os',
  outputs: (_context, files) => files.map((file) => file.path),
  render: (context: ScriptContext) => renderProjectOs(context.argv),
});

if (
  isDirectScript(import.meta.url, 'generate_project_os.ts') ||
  isDirectScript(import.meta.url, 'generate_project_os.js')
)
  void runGenerateProjectOs();
