const fs = require('fs');
const path = require('path');
const { metrics } = require('./lib/metrics.cjs');

const rootDir = path.resolve(__dirname, '..');
const indexFile = path.join(rootDir, 'knowledge/orchestration/global_skill_index.json');
const outputFile = path.join(rootDir, 'SKILLS_GUIDE.md');

function generate() {
  if (!fs.existsSync(indexFile)) return;
  const index = JSON.parse(fs.readFileSync(indexFile, 'utf8'));

  // Load historical performance data
  const history = metrics.reportFromHistory();
  const metricsMap = new Map();
  history.skills.forEach((s) => metricsMap.set(s.skill, s));

  let md = '# Gemini Skills Ecosystem Guide\n\n';
  md +=
    'Total Skills: ' +
    index.total_skills +
    ' (Active: ' +
    index.skills.filter((s) => s.status === 'implemented').length +
    ')\n';
  md += 'Last updated: ' + new Date().toLocaleDateString() + '\n\n';
  md +=
    'This guide is automatically generated. Efficiency scores are calculated from historical execution data (Latency vs Memory).\n\n';

  md += '## Available Skills\n\n';
  md += '| Skill | Description | Score | Avg Time | Usage |\n';
  md += '| :--- | :--- | :--- | :--- | :--- |\n';

  index.skills
    .sort((a, b) => a.name.localeCompare(b.name))
    .forEach((skill) => {
      const usage = '`npm run cli -- execute ' + skill.name + '`';
      const m = metricsMap.get(skill.name);

      let scoreStr = 'N/A';
      let timeStr = '-';

      if (m) {
        // Re-calculate score if not in history object
        const TIME_BASE = 5000;
        const MEM_BASE = 200;
        const timeImpact = Math.min(50, (m.avgMs / TIME_BASE) * 50);
        // MetricsCollector stores peakHeapMB but reportFromHistory might lack it depending on run
        const memImpact = m.peakHeapMB ? Math.min(50, (m.peakHeapMB / MEM_BASE) * 50) : 0;
        const score = Math.max(0, Math.round(100 - (timeImpact + memImpact)));

        scoreStr = score + (score < 70 ? ' ⚠️' : ' ✅');
        timeStr = m.avgMs + 'ms';
      }

      md +=
        '| **' +
        skill.name +
        '** | ' +
        skill.description +
        ' | ' +
        scoreStr +
        ' | ' +
        timeStr +
        ' | ' +
        usage +
        ' |\n';
    });

  md += '\n---\n*Generated by Ecosystem Architect Tool*';

  fs.writeFileSync(outputFile, md);
  console.log('[SUCCESS] Guide generated with performance data at ' + outputFile);
}

generate();
