import * as fs from 'node:fs';
import * as path from 'node:path';
import { metrics } from '@agent/core/metrics';
import { safeWriteFile, safeReadFile } from '@agent/core';

const rootDir = process.cwd();
const indexFile = path.join(rootDir, 'knowledge/orchestration/global_skill_index.json');
const outputFile = path.join(rootDir, 'SKILLS_GUIDE.md');

interface SkillEntry {
  n: string; // name
  d: string; // description
  s: 'impl' | 'plan'; // status
  path: string;
  [key: string]: any;
}

interface SkillIndex {
  t: number; // total
  s: SkillEntry[]; // skills
}

function generate(): void {
  if (!fs.existsSync(indexFile)) return;
  const indexRaw = safeReadFile(indexFile, 'utf8') as string;
  const index: SkillIndex = JSON.parse(indexRaw);
  const skills = index.s;
  const total = index.t;

  // Load historical performance data
  const history = metrics.reportFromHistory();
  const metricsMap = new Map<string, any>();
  history.skills.forEach((s: any) => metricsMap.set(s.skill, s));

  let md = '# Gemini Skills Ecosystem Guide\n\n';
  md += `Total Skills: ${total} (Implemented: ${skills.filter((s) => s.s === 'impl').length})\n`;
  md += `Last updated: ${new Date().toISOString().split('T')[0].replace(/-/g, '/')}\n\n`;
  md +=
    'This guide is a domain-driven catalog of the ecosystem. Skills are organized into Namespaces for better governance and accountability.\n\n';

  // Grouping logic
  const groups: Record<string, SkillEntry[]> = {};
  skills.forEach((skill) => {
    const skillPath = skill.path;
    const parts = skillPath.split('/');
    const category = parts.length > 1 ? parts[1] : 'General';
    if (!groups[category]) groups[category] = [];
    groups[category].push(skill);
  });

  const categoryDescriptions: Record<string, string> = {
    core: 'Fundamental orchestrators and self-evolution mechanisms.',
    engineering: 'Development, implementation, and architectural refactoring tools.',
    audit: 'Security, quality, and compliance scanning based on IPA/FISC standards.',
    connector: 'Enterprise tool integrations (Jira, Slack, Box).',
    media: 'Professional document extraction and media asset generation.',
    intelligence: 'Knowledge harvesting and 3-tier memory management.',
    ux: 'Human-centric UI/UX auditing and voice interface control.',
    business: 'Strategy, financial modeling, and executive reporting.',
    utilities: 'Shared helpers, background daemons, and general utilities.',
  };

  Object.keys(groups)
    .sort()
    .forEach((cat) => {
      md += `## 📂 ${cat.toUpperCase()}\n`;
      md += `> ${categoryDescriptions[cat] || 'General purpose skills.'}\n\n`;
      md += '| Skill | Description | Score | Avg Time | Usage |\n';
      md += '| :--- | :--- | :--- | :--- | :--- |\n';

      groups[cat]
        .sort((a, b) => a.n.localeCompare(b.n))
        .forEach((skill) => {
          const name = skill.n;
          const desc = skill.d;
          const usage = `\`npm run cli -- run ${name}\``;
          const m = metricsMap.get(name);

          let scoreStr = 'N/A';
          let timeStr = '-';

          if (m) {
            const TIME_BASE = 5000;
            const MEM_BASE = 200;
            const timeImpact = Math.min(50, (m.avgMs / TIME_BASE) * 50);
            const memImpact = m.peakHeapMB ? Math.min(50, (m.peakHeapMB / MEM_BASE) * 50) : 0;
            const score = Math.max(0, Math.round(100 - (timeImpact + memImpact)));
            scoreStr = score + (score < 70 ? ' ⚠️' : ' ✅');
            timeStr = m.avgMs + 'ms';
          }

          md += `| **${name}** | ${desc} | ${scoreStr} | ${timeStr} | ${usage} |\n`;
        });
      md += '\n';
    });

  md += '---\n*Generated by Ecosystem Architect Tool | Based on Hierarchical Namespace Model v1.0*';

  safeWriteFile(outputFile, md);
  console.log(`[SUCCESS] Guide re-generated at ${outputFile}`);
}

generate();
