import * as fs from 'node:fs';
import * as path from 'node:path';
import { compileFromFile } from 'json-schema-to-typescript';
import { logger } from '@agent/core/core';
import { safeWriteFile } from '@agent/core';

const rootDir = process.cwd();
const schemasDir = path.join(rootDir, 'schemas');
const typesDir = path.join(rootDir, 'libs/core/src/types');

async function generate(): Promise<void> {
  if (!fs.existsSync(typesDir)) {
    fs.mkdirSync(typesDir, { recursive: true });
  }

  if (!fs.existsSync(schemasDir)) {
    logger.info('No schemas directory found.');
    return;
  }

  const files = fs.readdirSync(schemasDir).filter((f) => f.endsWith('.schema.json'));
  let count = 0;

  for (const file of files) {
    const name = path.basename(file, '.schema.json');
    const tsFile = path.join(typesDir, `${name}.ts`);

    try {
      const ts = await compileFromFile(path.join(schemasDir, file), {
        bannerComment: `/* tslint:disable */
        /* eslint-disable */
        /**
        * This file was automatically generated by json-schema-to-typescript.
        * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
        * and run \\\`npm run generate:types\\\` to regenerate this file.
        */`,

        style: { singleQuote: true },
      });
      safeWriteFile(tsFile, ts);
      logger.success(`Generated types for ${name}`);
      count++;
    } catch (err: any) {
      logger.error(`Failed to generate types for ${name}: ${err.message}`);
    }
  }

  // Create index.ts
  if (count > 0) {
    const indexContent = files
      .map((f) => {
        const name = path.basename(f, '.schema.json');
        return `export * from './${name}';`;
      })
      .join('\n');
    safeWriteFile(path.join(typesDir, 'index.ts'), indexContent + '\n');
    logger.success('Generated types/index.ts');
  }
}

generate().catch(err => {
  console.error(err);
  process.exit(1);
});
