import * as path from 'node:path';
import {
  createStandardYargs,
  pathResolver,
  safeExistsSync,
  safeMkdir,
  safeReadFile,
  safeWriteFile,
} from '@agent/core';
import { readJsonFile } from './refactor/cli-input.js';

type ArtifactMap = {
  lifecycle: Array<{
    phase: string;
    required: string[];
  }>;
};

const BLUEPRINT_BY_ARTIFACT: Record<string, string> = {
  'project-charter': 'project-charter.md',
  'business-impact-analysis': 'business-impact-analysis.md',
  'stakeholder-communication-register': 'stakeholder-communication-register.md',
  'requirements-definition': 'requirements-definition.md',
  'slo-sli-definition': 'slo-sli-definition.md',
  'information-asset-registry': 'information-asset-registry.md',
  'basic-design': 'basic-design.md',
  'architecture-design': 'architecture-design.md',
  'detailed-design': 'detailed-design.md',
  'operational-design': 'operational-design.md',
  'data-flow-lifecycle-map': 'data-flow-lifecycle-map.md',
  'operation-runbook': 'operation-runbook.md',
  'environment-setup-guide': 'environment-setup-guide.md',
  'project-management-plan': 'project-management-plan.md',
  'mission-ledger': 'mission-ledger.md',
  'raid-log': 'raid-log.md',
  'issue-log': 'issue-log.md',
  'change-control-ledger': 'change-control-ledger.md',
  'gate-review-packet': 'gate-review-packet.md',
  'test-plan': 'test-plan.md',
  'test-validation-report': 'test-validation-report.md',
  'security-audit-report': 'security-audit-report.md',
  'cutover-migration-plan': 'cutover-migration-plan.md',
  'user-manual-faq': 'user-manual-faq.md',
  'incident-report': 'incident-report.md',
  'mission-closure-report': 'mission-closure-report.md',
};

const PHASE_DIR_BY_NAME: Record<string, string> = {
  initiate: '01_initiate',
  define: '02_define',
  design: '03_design',
  build: '04_control',
  validate: '05_validate',
  transfer_run: '06_transfer_run',
};

function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'project-os';
}

function renderProjectReadme(projectName: string, targetDir: string, lifecycle: ArtifactMap['lifecycle']): string {
  const lines = [
    `# ${projectName} Project Operating System`,
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Structure',
    '',
  ];

  for (const phase of lifecycle) {
    const phaseDir = PHASE_DIR_BY_NAME[phase.phase] || phase.phase;
    lines.push(`- ${phaseDir}`);
    for (const artifact of phase.required) {
      const fileName = BLUEPRINT_BY_ARTIFACT[artifact];
      if (!fileName) continue;
      lines.push(`  - ${path.join(phaseDir, fileName)}`);
    }
  }

  lines.push('', '## Notes', '', '- Instantiate placeholders for this project.', '- Link requirements, design, test, and gate evidence explicitly.');
  return `${lines.join('\n')}\n`;
}

function renderInstantiatedBlueprint(projectName: string, sourceBlueprint: string, content: string): string {
  return [
    `<!-- Generated by project-os:init for ${projectName} -->`,
    `<!-- Source blueprint: ${sourceBlueprint} -->`,
    '',
    `> Project: ${projectName}`,
    '',
    content,
    '',
  ].join('\n');
}

async function main() {
  const argv = await createStandardYargs()
    .option('name', {
      alias: 'n',
      type: 'string',
      demandOption: true,
      description: 'Project name used to instantiate the Project Operating System scaffold',
    })
    .option('out', {
      alias: 'o',
      type: 'string',
      description: 'Target directory for the generated Project Operating System scaffold',
    })
    .parseSync();

  const projectName = String(argv.name).trim();
  const slug = slugify(projectName);
  const targetDir = argv.out
    ? pathResolver.rootResolve(String(argv.out))
    : pathResolver.sharedTmp(path.join('project-os', slug));

  const artifactMapPath = pathResolver.knowledge('public/orchestration/project-operating-system-artifact-map.json');
  const artifactMap = readJsonFile<ArtifactMap>(artifactMapPath);
  const blueprintsRoot = pathResolver.knowledge('public/templates/blueprints');

  safeMkdir(targetDir, { recursive: true });

  for (const phase of artifactMap.lifecycle) {
    const phaseDirName = PHASE_DIR_BY_NAME[phase.phase] || phase.phase;
    const phaseDir = path.join(targetDir, phaseDirName);
    safeMkdir(phaseDir, { recursive: true });

    for (const artifact of phase.required) {
      const blueprintName = BLUEPRINT_BY_ARTIFACT[artifact];
      if (!blueprintName) continue;

      const sourcePath = path.join(blueprintsRoot, blueprintName);
      if (!safeExistsSync(sourcePath)) continue;

      const targetPath = path.join(phaseDir, blueprintName);
      const content = safeReadFile(sourcePath, { encoding: 'utf8' }) as string;
      safeWriteFile(targetPath, renderInstantiatedBlueprint(projectName, sourcePath, content));
    }
  }

  const readmePath = path.join(targetDir, 'README.md');
  safeWriteFile(readmePath, renderProjectReadme(projectName, targetDir, artifactMap.lifecycle));

  process.stdout.write(`${path.relative(pathResolver.rootDir(), targetDir)}\n`);
}

main().catch((err) => {
  process.stderr.write(`${err.message}\n`);
  process.exit(1);
});
