/**
 * Post-build step of @agent/core: write `dist/package.json` (scope marker) and
 * the `#imports` shims it points at.
 *
 * Why: for every `.js` module it resolves, Node (v22+) calls
 * `getPackageScopeConfig`, which re-deserializes the nearest package.json and
 * spreads it, so its lazy `exports` getter JSON-parses the whole exports
 * string again. `libs/core/package.json` carries ~1,800 subpath exports
 * (~290KB), so every `dist/*.js` load re-parsed 290KB. A small
 * `dist/package.json` makes `dist/` its own package scope with only what dist
 * modules need: `"type": "module"` and the `#imports` map (an earlier attempt
 * without `imports` broke `#repository-path-boundary` in dist modules).
 *
 * `imports` targets must stay inside the scope, so each one is a one-line shim
 * in dist that re-exports the single real module in `libs/core/` (one module
 * instance whichever path loads it). External consumers still resolve
 * `@agent/core/*` through the full exports map in `libs/core/package.json`.
 *
 * Kill switch: `KYBERION_CORE_DIST_SCOPE=0` removes the marker and shims
 * instead (Node then falls back to `libs/core/package.json`, the old behaviour).
 *
 * Bootstrap constraint: runs as the last step of the @agent/core build
 * (`libs/core/package.json` "build"), where the core stack it would need for
 * secure-io is the very output being written; it uses `node:fs` on
 * `libs/core/dist/` only (listed in tests/fixtures/governance-import-baseline.json).
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CORE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'libs', 'core');

const DEFAULT_EXPORT_PATTERN =
  /(^|\n)\s*export\s+default\b|export\s*\{[^}]*\b(?:as\s+)?default\b[^}]*\}/u;

function isScopeOff(env) {
  return ['0', 'false', 'off'].includes(
    String(env.KYBERION_CORE_DIST_SCOPE ?? '')
      .trim()
      .toLowerCase()
  );
}

/**
 * The dist scope manifest derived from libs/core/package.json. `readTarget(file)`
 * returns a target module's text, so its shim also re-exports `default` when the
 * target has one (`export *` never forwards a default export).
 */
export function buildDistScope(corePackage, readTarget = () => '') {
  const imports = {};
  const shims = [];
  for (const [key, target] of Object.entries(corePackage.imports ?? {})) {
    if (typeof target !== 'string' || !target.startsWith('./') || !target.endsWith('.mjs')) {
      throw new Error(
        `[CORE_DIST_SCOPE_UNSUPPORTED_IMPORT] ${key} -> ${JSON.stringify(target)} — only "./<file>.mjs" targets can be shimmed | next: extend scripts/write_core_dist_scope.mjs`
      );
    }
    const file = target.slice(2);
    imports[key] = `./${file}`;
    const hasDefault = DEFAULT_EXPORT_PATTERN.test(readTarget(file));
    shims.push({
      file,
      body: `export * from '../${file}';\n${hasDefault ? `export { default } from '../${file}';\n` : ''}`,
    });
  }
  return {
    manifest: {
      private: true,
      type: corePackage.type ?? 'module',
      description:
        'Generated by scripts/write_core_dist_scope.mjs. Package scope for dist/ so Node does not re-parse the 290KB exports map of libs/core/package.json for every dist module. Do not edit.',
      imports,
    },
    shims,
  };
}

function loadExpected(coreDir) {
  const corePackage = JSON.parse(readFileSync(join(coreDir, 'package.json'), 'utf8'));
  return buildDistScope(corePackage, (file) => {
    try {
      return readFileSync(join(coreDir, file), 'utf8');
    } catch {
      return '';
    }
  });
}

export function writeDistScope({ coreDir = CORE_DIR, env = process.env } = {}) {
  const distDir = join(coreDir, 'dist');
  const { manifest, shims } = loadExpected(coreDir);
  if (isScopeOff(env)) {
    rmSync(join(distDir, 'package.json'), { force: true });
    for (const shim of shims) rmSync(join(distDir, shim.file), { force: true });
    return { written: false, distDir };
  }
  if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });
  for (const shim of shims) writeFileSync(join(distDir, shim.file), shim.body);
  writeFileSync(join(distDir, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  return { written: true, distDir };
}

/**
 * Staleness check: the dist scope must match what the current
 * libs/core/package.json would generate. A dist built before an `#imports`
 * change would otherwise resolve the old map (or none). No dist/ → nothing to check.
 */
export function findDistScopeDrift({ coreDir = CORE_DIR, env = process.env } = {}) {
  const distDir = join(coreDir, 'dist');
  if (!existsSync(distDir)) return [];
  const { manifest, shims } = loadExpected(coreDir);
  const manifestPath = join(distDir, 'package.json');
  if (isScopeOff(env)) {
    return existsSync(manifestPath)
      ? ['dist/package.json exists although KYBERION_CORE_DIST_SCOPE=0']
      : [];
  }
  if (!existsSync(manifestPath)) {
    return ['dist/package.json is missing — run `pnpm --filter @agent/core run build`'];
  }
  const drift = [];
  let actual;
  try {
    actual = JSON.parse(readFileSync(manifestPath, 'utf8'));
  } catch {
    return ['dist/package.json is not valid JSON — rebuild @agent/core'];
  }
  if (actual.type !== manifest.type) {
    drift.push(
      `dist/package.json type ${JSON.stringify(actual.type)} ≠ ${JSON.stringify(manifest.type)}`
    );
  }
  const expectedImports = JSON.stringify(manifest.imports);
  const actualImports = JSON.stringify(actual.imports ?? {});
  if (expectedImports !== actualImports) {
    drift.push(
      `dist/package.json imports ${actualImports} ≠ libs/core/package.json imports ${expectedImports}`
    );
  }
  for (const shim of shims) {
    const shimPath = join(distDir, shim.file);
    let body = null;
    try {
      body = readFileSync(shimPath, 'utf8');
    } catch {
      /* missing */
    }
    if (body !== shim.body)
      drift.push(`dist/${shim.file} is ${body === null ? 'missing' : 'stale'}`);
  }
  return drift.map((line) => `${line} — rebuild with \`pnpm --filter @agent/core run build\``);
}

// import.meta.main (Node >= 24.2) instead of comparing argv[1] with this
// file's path: that comparison silently skipped the write under a symlinked
// checkout. Only a direct run acts (an import, e.g. from a test, never writes);
// the build passes --run explicitly, --check reports drift with exit code 1.
if (import.meta.main) {
  const cliArgs = process.argv.slice(2);
  if (cliArgs.includes('--check')) {
    const drift = findDistScopeDrift();
    for (const line of drift) process.stderr.write(`[core-dist-scope] ${line}\n`);
    process.exitCode = drift.length > 0 ? 1 : 0;
  } else if (cliArgs.includes('--run')) {
    writeDistScope();
  } else {
    process.stderr.write('usage: node scripts/write_core_dist_scope.mjs --run | --check\n');
    process.exitCode = 2;
  }
}
