/**
 * Post-build step of @agent/core: write `dist/package.json` (scope marker) and
 * the `#imports` shims it points at.
 *
 * Why: for every `.js` module it resolves, Node (v22+) calls
 * `getPackageScopeConfig`, which re-deserializes the nearest package.json and
 * spreads it, so its lazy `exports` getter JSON-parses the whole exports
 * string again. `libs/core/package.json` carries ~1,800 subpath exports
 * (~290KB), so every `dist/*.js` load re-parsed 290KB. A small
 * `dist/package.json` makes `dist/` its own package scope with only what dist
 * modules need: `"type": "module"` and the `#imports` map (an earlier attempt
 * without `imports` broke `#repository-path-boundary` in dist modules).
 *
 * `imports` targets must stay inside the scope, so each one is a one-line shim
 * in dist that re-exports the single real module in `libs/core/` (one module
 * instance whichever path loads it). External consumers still resolve
 * `@agent/core/*` through the full exports map in `libs/core/package.json`.
 *
 * Kill switch: `KYBERION_CORE_DIST_SCOPE=0` removes the marker and shims
 * instead (Node then falls back to `libs/core/package.json`, the old behaviour).
 *
 * Bootstrap constraint: runs as the last step of the @agent/core build
 * (`libs/core/package.json` "build"), where the core stack it would need for
 * secure-io is the very output being written; it uses `node:fs` on
 * `libs/core/dist/` only (listed in tests/fixtures/governance-import-baseline.json).
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CORE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'libs', 'core');

/** The dist scope manifest derived from libs/core/package.json. */
export function buildDistScope(corePackage) {
  const imports = {};
  const shims = [];
  for (const [key, target] of Object.entries(corePackage.imports ?? {})) {
    if (typeof target !== 'string' || !target.startsWith('./') || !target.endsWith('.mjs')) {
      throw new Error(
        `[CORE_DIST_SCOPE_UNSUPPORTED_IMPORT] ${key} -> ${JSON.stringify(target)} — only "./<file>.mjs" targets can be shimmed | next: extend scripts/write_core_dist_scope.mjs`
      );
    }
    const file = target.slice(2);
    imports[key] = `./${file}`;
    shims.push({ file, body: `export * from '../${file}';\n` });
  }
  return {
    manifest: {
      private: true,
      type: corePackage.type ?? 'module',
      description:
        'Generated by scripts/write_core_dist_scope.mjs. Package scope for dist/ so Node does not re-parse the 290KB exports map of libs/core/package.json for every dist module. Do not edit.',
      imports,
    },
    shims,
  };
}

export function writeDistScope({ coreDir = CORE_DIR, env = process.env } = {}) {
  const distDir = join(coreDir, 'dist');
  const corePackage = JSON.parse(readFileSync(join(coreDir, 'package.json'), 'utf8'));
  const { manifest, shims } = buildDistScope(corePackage);
  const off = ['0', 'false', 'off'].includes(String(env.KYBERION_CORE_DIST_SCOPE ?? '').trim());
  if (off) {
    rmSync(join(distDir, 'package.json'), { force: true });
    for (const shim of shims) rmSync(join(distDir, shim.file), { force: true });
    return { written: false, distDir };
  }
  if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });
  for (const shim of shims) writeFileSync(join(distDir, shim.file), shim.body);
  writeFileSync(join(distDir, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  return { written: true, distDir };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeDistScope();
}
