"""
Kyberion Kokoro-82M TTS Bridge.

Usage (stdin JSON):
  echo '{"action":"generate","params":{...}}' | python3 kokoro_tts_bridge.py
"""

import sys
import json
import os
import contextlib
import zipfile
import tempfile
from pathlib import Path

# Suppress stdout print leaks from raw libraries (preventing JSON parse errors in TypeScript caller)
@contextlib.contextmanager
def suppress_stdout():
    original_stdout = sys.stdout
    sys.stdout = sys.stderr
    try:
        yield
    finally:
        sys.stdout = original_stdout


def _ensure_unidic_lite():
    try:
        import unidic_lite  # noqa: F401
        return
    except ImportError:
        pass

    # Hardcoded known paths from pip cache to avoid slow walk
    candidates = [
        '/Users/famao/Library/Caches/pip/wheels/38/c7/24/76251bdf69bc016a9a7a9e334df5de2b2a8c3d69956d6d4590/unidic_lite-1.0.8-py3-none-any.whl',
        '/Users/famao/Library/Caches/pip/wheels/ea/5d/c1/cf8cf037f3ad5b88ce8cbfbe4df855b5502fb81363690d56e7/unidic_lite-1.0.8-py3-none-any.whl'
    ]
    
    wheel_path = None
    for path in candidates:
        if os.path.exists(path):
            wheel_path = path
            break

    if not wheel_path:
        # Fallback to walk search
        for root, dirs, files in os.walk('/Users/famao'):
            if any(p in root for p in ['.git', 'node_modules', 'dist', '.venv', 'Library/Containers', 'Library/Application Support']):
                continue
            for file in files:
                if 'unidic_lite' in file and file.endswith('.whl'):
                    wheel_path = os.path.join(root, file)
                    break
            if wheel_path:
                break

    if not wheel_path:
        sys.stderr.write("[KOKORO_BRIDGE] unidic-lite wheel not found\n")
        return

    # Extract to a temp directory
    temp_dir = os.path.join(tempfile.gettempdir(), 'unidic_lite_extracted')
    if not os.path.exists(temp_dir):
        os.makedirs(temp_dir, exist_ok=True)
        try:
            with zipfile.ZipFile(wheel_path, 'r') as zip_ref:
                zip_ref.extractall(temp_dir)
            sys.stderr.write(f"[KOKORO_BRIDGE] Dynamically extracted unidic-lite to {temp_dir}\n")
        except Exception as e:
            sys.stderr.write(f"[KOKORO_BRIDGE] Failed to extract wheel: {e}\n")
            
    if temp_dir not in sys.path:
        sys.path.insert(0, temp_dir)


# Run dynamic dependency loading first
_ensure_unidic_lite()


def _check_health() -> dict:
    try:
        with suppress_stdout():
            import kokoro  # noqa: F401
            import soundfile  # noqa: F401
        return {"status": "ok", "model": "hexgrad/Kokoro-82M"}
    except ImportError as e:
        return {
            "status": "unavailable",
            "error": str(e),
            "install_hint": "pip install kokoro soundfile",
        }


def _generate(params: dict) -> dict:
    text = str(params.get("text") or "").strip()
    if not text:
        return {"status": "error", "error": "params.text is required"}

    output_path = str(params.get("output_path") or "").strip()
    if not output_path:
        return {"status": "error", "error": "params.output_path is required"}

    lang_code = str(params.get("lang_code") or "ja").strip()
    # Kokoro uses 'j' for Japanese, 'a' for American English
    kokoro_lang = "j" if lang_code.startswith("ja") else "a"
    
    # Default voices: jf_alpha (Japanese female), af_heart (English female)
    default_voice = "jf_alpha" if kokoro_lang == "j" else "af_heart"
    voice = str(params.get("voice") or default_voice).strip()

    try:
        with suppress_stdout():
            import soundfile as sf
            from kokoro import KPipeline

            pipeline = KPipeline(lang_code=kokoro_lang)
            generator = pipeline(text, voice=voice)
            
            # Extract and write the first audio segment
            audio_data = None
            for gs, ps, audio in generator:
                if audio is not None:
                    audio_data = audio
                    break
            
            if audio_data is None:
                raise Exception("No audio generated by Kokoro pipeline")

            out = Path(output_path)
            out.parent.mkdir(parents=True, exist_ok=True)
            sf.write(str(out), audio_data, 24000)

    except Exception as exc:
        return {"status": "error", "error": str(exc)}

    return {
        "status": "success",
        "output_path": str(output_path),
        "model": "hexgrad/Kokoro-82M",
        "mode": "tts",
    }


def main() -> None:
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({"status": "error", "error": "No input on stdin"}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(json.dumps({"status": "error", "error": f"Invalid JSON: {exc}"}))
        sys.exit(1)

    action = payload.get("action")
    params = payload.get("params") or {}

    if action == "health":
        result = _check_health()
    elif action == "generate":
        result = _generate(params)
    else:
        result = {"status": "error", "error": f"Unknown action: {action!r}"}

    # Only output JSON on clean stdout
    print(json.dumps(result))


if __name__ == "__main__":
    main()
