"""
Kyberion Kokoro-82M TTS Bridge.

Usage (stdin JSON):
  echo '{"action":"generate","params":{...}}' | python3 kokoro_tts_bridge.py
"""

import sys
import json
import contextlib
from pathlib import Path

# Suppress stdout print leaks from raw libraries (preventing JSON parse errors in TypeScript caller)
@contextlib.contextmanager
def suppress_stdout():
    original_stdout = sys.stdout
    sys.stdout = sys.stderr
    try:
        yield
    finally:
        sys.stdout = original_stdout


def _check_health() -> dict:
    try:
        with suppress_stdout():
            import kokoro  # noqa: F401
            import soundfile  # noqa: F401
        return {"status": "ok", "model": "hexgrad/Kokoro-82M"}
    except ImportError as e:
        return {
            "status": "unavailable",
            "error": str(e),
            "install_hint": "Install kokoro and soundfile into the runtime selected by KYBERION_PYTHON_BIN / KYBERION_PYTHON.",
        }


def _configure_japanese_dictionary() -> None:
    """Use the small redistributable dictionary when unidic has no data."""
    try:
        import unidic
        import unidic_lite

        if not Path(unidic.DICDIR, "mecabrc").exists():
            unidic.DICDIR = unidic_lite.DICDIR
    except ImportError:
        # English Kokoro does not need MeCab; Japanese generation reports the
        # actionable dependency error from the upstream package if unavailable.
        return


def _generate(params: dict) -> dict:
    text = str(params.get("text") or "").strip()
    if not text:
        return {"status": "error", "error": "params.text is required"}

    output_path = str(params.get("output_path") or "").strip()
    if not output_path:
        return {"status": "error", "error": "params.output_path is required"}

    lang_code = str(params.get("lang_code") or "ja").strip()
    # Kokoro uses 'j' for Japanese, 'a' for American English
    kokoro_lang = "j" if lang_code.startswith("ja") else "a"
    
    # Default voices: jf_alpha (Japanese female), af_heart (English female)
    default_voice = "jf_alpha" if kokoro_lang == "j" else "af_heart"
    voice = str(params.get("voice") or default_voice).strip()

    try:
        with suppress_stdout():
            import soundfile as sf
            from kokoro import KPipeline

            if kokoro_lang == "j":
                _configure_japanese_dictionary()
            pipeline = KPipeline(lang_code=kokoro_lang)
            generator = pipeline(text, voice=voice)
            
            # Kokoro streams one or more segments; concatenate them all so
            # long replies are not silently truncated to the first chunk.
            audio_segments = []
            for gs, ps, audio in generator:
                if audio is not None:
                    audio_segments.append(audio)

            if not audio_segments:
                raise Exception("No audio generated by Kokoro pipeline")

            import numpy as np
            audio_data = np.concatenate(audio_segments)

            out = Path(output_path)
            out.parent.mkdir(parents=True, exist_ok=True)
            sf.write(str(out), audio_data, 24000)

    except Exception as exc:
        return {"status": "error", "error": str(exc)}

    return {
        "status": "success",
        "output_path": str(output_path),
        "model": "hexgrad/Kokoro-82M",
        "mode": "tts",
    }


def main() -> None:
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({"status": "error", "error": "No input on stdin"}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(json.dumps({"status": "error", "error": f"Invalid JSON: {exc}"}))
        sys.exit(1)

    action = payload.get("action")
    params = payload.get("params") or {}

    if action == "health":
        result = _check_health()
    elif action == "generate":
        result = _generate(params)
    else:
        result = {"status": "error", "error": f"Unknown action: {action!r}"}

    # Only output JSON on clean stdout
    print(json.dumps(result))


if __name__ == "__main__":
    main()
