"""
Kyberion Kokoro TTS Bridge — Ultra-lightweight TTS via Kokoro-82M.

Usage (stdin JSON):
  echo '{"action":"generate","params":{...}}' | python3 kokoro_tts_bridge.py

Supported actions:
  generate   — TTS audio generation
  health     — check kokoro and soundfile installation
"""

import sys
import json
from pathlib import Path


def _check_health() -> dict:
    try:
        import kokoro  # noqa: F401
        import soundfile  # noqa: F401
        return {"status": "ok", "model": "Kokoro-82M"}
    except ImportError as e:
        return {
            "status": "unavailable",
            "error": f"Required packages not installed: {e}",
            "install_hint": "pip install kokoro soundfile",
        }


def _generate(params: dict) -> dict:
    text = str(params.get("text") or "").strip()
    if not text:
        return {"status": "error", "error": "params.text is required"}

    output_path = str(params.get("output_path") or "").strip()
    if not output_path:
        return {"status": "error", "error": "params.output_path is required"}

    voice = str(params.get("voice") or "").strip() or "jf_alpha"
    language = str(params.get("language") or "").strip().lower() or "ja"
    speed = float(params.get("speed", 1.0))

    try:
        from kokoro import KPipeline
        import soundfile as sf
        import numpy as np
    except ImportError:
        return {
            "status": "error",
            "error": "kokoro, soundfile, or numpy not installed — run: pip install kokoro soundfile numpy",
            "install_hint": "pip install kokoro soundfile numpy",
        }

    # Map language code
    # 'a' for American English, 'b' for British English, 'j' for Japanese, 'c' for Chinese, etc.
    lang_code = 'j'
    if language in ['en', 'en-us', 'en-gb', 'a', 'b']:
        lang_code = 'a'
        if 'gb' in language or language == 'b':
            lang_code = 'b'
    elif language in ['ja', 'ja-jp', 'j']:
        lang_code = 'j'
    elif language in ['zh', 'zh-cn', 'c']:
        lang_code = 'c'
    else:
        lang_code = language[0] if len(language) == 1 else 'a'

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    try:
        pipeline = KPipeline(lang_code=lang_code)
        generator = pipeline(text, voice=voice, speed=speed, split_pattern=r'\n+')
        
        audio_segments = []
        for _, _, audio in generator:
            if audio is not None and len(audio) > 0:
                audio_segments.append(audio)
        
        if not audio_segments:
            return {"status": "error", "error": "No audio was generated by the pipeline"}
            
        combined_audio = np.concatenate(audio_segments)
        sf.write(str(out), combined_audio, 24000)
    except Exception as exc:
        return {"status": "error", "error": str(exc)}

    if not out.exists() or out.stat().st_size == 0:
        return {"status": "error", "error": f"Output file was not created or is empty: {out}"}

    return {
        "status": "success",
        "output_path": str(out),
        "model": "Kokoro-82M",
        "voice": voice,
        "language": language,
    }


def main() -> None:
    raw = sys.stdin.read().strip()
    if not raw:
        print(json.dumps({"status": "error", "error": "No input on stdin"}))
        sys.exit(1)

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(json.dumps({"status": "error", "error": f"Invalid JSON: {exc}"}))
        sys.exit(1)

    action = payload.get("action")
    params = payload.get("params") or {}

    if action == "health":
        result = _check_health()
    elif action == "generate":
        result = _generate(params)
    else:
        result = {"status": "error", "error": f"Unknown action: {action!r}"}

    print(json.dumps(result))


if __name__ == "__main__":
    main()
