/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Governed use-case contract for moving from a points portal advertiser page to a merchant landing page without reservation confirmation, payment execution, credential export, or session handoff export.
 */
export interface PointsPortalClickoutUseCase {
  kind: 'points-portal-clickout-usecase';
  usecase_id: string;
  mode: 'simulation' | 'assisted_booking';
  points_portal: SiteRef;
  merchant: SiteRef;
  auth_strategy: AuthStrategy;
  portal_detail_url: string;
  clickout: Clickout;
  landing_match: LandingMatch;
  /**
   * @minItems 1
   */
  blocked_actions: {
    [k: string]: unknown;
  } & [
    (
      | 'reservation_confirmation'
      | 'payment_execution'
      | 'cancellation'
      | 'profile_mutation'
      | 'credential_export'
      | 'session_handoff_export'
      | 'session_handoff_import'
      | 'new_site_login'
    ),
    ...(
      | 'reservation_confirmation'
      | 'payment_execution'
      | 'cancellation'
      | 'profile_mutation'
      | 'credential_export'
      | 'session_handoff_export'
      | 'session_handoff_import'
      | 'new_site_login'
    )[],
  ];
  /**
   * @minItems 1
   */
  evidence_required: {
    [k: string]: unknown;
  } & [
    (
      | 'portal_name'
      | 'merchant_page'
      | 'reward_rate'
      | 'terms_snapshot'
      | 'timestamp'
      | 'portal_detail_screenshot'
      | 'clickout_confirmation'
      | 'tabs_before_clickout'
      | 'tabs_after_landing'
      | 'merchant_landing_snapshot'
      | 'merchant_landing_screenshot'
      | 'network_after_landing'
      | 'exported_adf'
      | 'tracking_warning'
    ),
    ...(
      | 'portal_name'
      | 'merchant_page'
      | 'reward_rate'
      | 'terms_snapshot'
      | 'timestamp'
      | 'portal_detail_screenshot'
      | 'clickout_confirmation'
      | 'tabs_before_clickout'
      | 'tabs_after_landing'
      | 'merchant_landing_snapshot'
      | 'merchant_landing_screenshot'
      | 'network_after_landing'
      | 'exported_adf'
      | 'tracking_warning'
    )[],
  ];
  success_criteria: SuccessCriteria;
  artifact_policy: ArtifactPolicy;
  preflight: Preflight;
  notes?: string;
}
export interface SiteRef {
  id: string;
  display_name: string;
  account_ref?: string;
}
export interface AuthStrategy {
  type: 'dedicated_browser_profile' | 'manual_login' | 'cdp_existing_browser';
  browser_profile_ref?: string;
  approval_required: true;
  notes?: string;
}
export interface Clickout {
  selector: string;
  selector_strategy?: 'css' | 'role' | 'text';
  button_text_hint?: string;
  operator_confirmation_required: true;
}
export interface LandingMatch {
  url_includes: string;
  title_includes?: string;
}
export interface SuccessCriteria {
  landing_url_includes: string;
  landing_title_includes?: string;
  handoff_export_absent: true;
  blocked_actions_not_executed: true;
  merchant_landing_captured: true;
}
export interface ArtifactPolicy {
  forbid_session_handoff_export: true;
  /**
   * @minItems 1
   */
  allowed_artifact_roots: [
    'active/shared/tmp/browser' | 'active/shared/runtime/browser',
    ...('active/shared/tmp/browser' | 'active/shared/runtime/browser')[],
  ];
  retain_browser_profile: boolean;
  delete_continue_files: boolean;
}
export interface Preflight {
  require_clickout_selector: true;
  require_landing_match: true;
  require_blocked_actions: true;
  /**
   * @minItems 1
   */
  deny_ops: [
    (
      | 'export_session_handoff'
      | 'import_session_handoff'
      | 'payment_execution'
      | 'reservation_confirmation'
      | 'profile_mutation'
    ),
    ...(
      | 'export_session_handoff'
      | 'import_session_handoff'
      | 'payment_execution'
      | 'reservation_confirmation'
      | 'profile_mutation'
    )[],
  ];
}
