/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface ProposalBrief {
  kind: 'proposal-brief';
  title: string;
  client: string;
  objective: string;
  document_profile?: string;
  layout_template_id?: string;
  render_target?: string;
  locale?: string;
  audience: string[];
  story: {
    core_message: string;
    chapters: string[];
    tone?: string;
    closing_cta?: string;
  };
  evidence?: {
    title: string;
    point: string;
  }[];
  required_sections?: string[];
}
