/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * High-level planning contract for leisure or business travel before it is compiled into executable ADF.
 */
export interface TravelPlanningBrief {
  kind: 'travel-planning-brief';
  destination: string;
  dates: DateRange;
  /**
   * @minItems 1
   */
  travelers: [Traveler, ...Traveler[]];
  occasion?: string;
  planning_goal: string;
  preferences?: {
    pace?: 'relaxed' | 'balanced' | 'dense';
    mood?: string[];
    food?: string[];
    weather_risk_tolerance?: 'low' | 'medium' | 'high';
    avoid?: string[];
    [k: string]: unknown;
  };
  constraints: {
    no_booking_without_approval: true;
    no_payment_without_approval: true;
    avoid_closed_facilities?: boolean;
    include_weather_backup?: boolean;
    require_evidence_for_dynamic_facts?: boolean;
    max_budget?: {
      amount: number;
      currency: string;
    };
    [k: string]: unknown;
  };
  booking_profile_ref?: string;
  approval_required_for?: (
    | 'login'
    | 'points_portal_redirect'
    | 'reservation_hold'
    | 'booking_confirmation'
    | 'payment'
    | 'cancellation'
    | 'profile_mutation'
    | 'personal_data_storage'
  )[];
  source_policy?: {
    freshness?: 'same_day' | 'within_24h' | 'within_7d' | 'stable_sources_ok';
    evidence_required?: boolean;
    preferred_source_types?: (
      'official' | 'primary' | 'reputable_secondary' | 'operator_supplied'
    )[];
  };
  /**
   * @minItems 1
   */
  desired_output: [
    (
      | 'recommended_itinerary'
      | 'ranked_candidates'
      | 'backup_plan'
      | 'booking_priority'
      | 'birthday_touchpoints'
      | 'budget_summary'
      | 'source_summary'
      | 'approval_preview'
    ),
    ...(
      | 'recommended_itinerary'
      | 'ranked_candidates'
      | 'backup_plan'
      | 'booking_priority'
      | 'birthday_touchpoints'
      | 'budget_summary'
      | 'source_summary'
      | 'approval_preview'
    )[],
  ];
}
export interface DateRange {
  start: string;
  end: string;
}
export interface Traveler {
  role: 'user' | 'spouse' | 'partner' | 'friend' | 'family' | 'child' | 'colleague' | 'other';
  birthday?: string;
  relationship_note?: string;
  sensitivity?: 'personal' | 'confidential' | 'public';
}
