/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface ActuatorPipelineBundle {
  kind: 'actuator-pipeline-bundle';
  archetype_id: string;
  status: 'ready' | 'clarification_required';
  summary?: string;
  missing_inputs?: string[];
  jobs: {
    id: string;
    title: string;
    actuator: string;
    template_path: string;
    recommended_procedure?: string;
    parameter_overrides?: {
      [k: string]: unknown;
    };
    outputs?: string[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
