/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface ActuatorResolutionPlan {
  kind: 'actuator-resolution-plan';
  archetype_id: string;
  summary?: string;
  phases: {
    id: string;
    title: string;
    actuators: string[];
    artifacts?: string[];
    exit_criteria?: string[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
