/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Renderer-neutral architecture graph contract for infrastructure, platform, and system diagrams.
 */
export interface KyberionArchitectureDescriptionFormatADF {
  version?: string;
  title?: string;
  /**
   * Primary cloud or platform provider, for example aws, azure, gcp, kubernetes.
   */
  provider?: string;
  render_hints?: {
    engine?: 'drawio' | 'mermaid' | 'd2' | 'html';
    direction?: 'TB' | 'BT' | 'LR' | 'RL';
    theme?: string;
    /**
     * Named icon pack such as aws-architecture.
     */
    icon_pack?: string;
    group_by?: 'provider' | 'boundary' | 'group' | 'network_zone' | 'none';
    [k: string]: unknown;
  };
  nodes: {
    id: string;
    /**
     * Logical resource type, for example aws_instance, aws_vpc, browser, service.
     */
    type: string;
    name: string;
    /**
     * Resource-specific provider override.
     */
    provider?: string;
    /**
     * Human-readable technology label, for example EC2, RDS PostgreSQL, ALB.
     */
    technology?: string;
    /**
     * Explicit key for icon resolution when it differs from type.
     */
    icon_key?: string;
    /**
     * ID of the container node.
     */
    parent?: string;
    /**
     * Renderer-neutral grouping label such as application, data, public-tier.
     */
    group?: string;
    /**
     * Boundary name such as vpc, subnet, account, region, cluster.
     */
    boundary?: string;
    network_zone?: 'public' | 'private' | 'isolated' | 'dmz' | 'shared';
    tags?: string[];
    metadata?: {
      [k: string]: unknown;
    };
    render_hints?: {
      container?: boolean;
      preferred_width?: number;
      preferred_height?: number;
      label_position?: 'top' | 'bottom' | 'center';
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  edges: {
    from: string;
    to: string;
    label?: string;
    /**
     * Connection protocol, for example HTTPS, TCP, JDBC.
     */
    protocol?: string;
    port?: string | number;
    direction?: 'uni' | 'bi' | 'none';
    metadata?: {
      [k: string]: unknown;
    };
    render_hints?: {
      style?: 'solid' | 'dashed' | 'dotted';
      emphasis?: 'low' | 'normal' | 'high';
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
