/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface DeliveryPack {
  kind: 'delivery-pack';
  pack_id: string;
  summary: string;
  main_artifact_id?: string;
  request_text?: string;
  conversation_summary?: string;
  recommended_next_action?: string;
  artifacts_by_role?: {
    primary?: string[];
    specification?: string[];
    evidence?: string[];
    [k: string]: unknown;
  };
  artifacts: {
    id: string;
    kind: string;
    path: string;
    description?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
