/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface DocumentBrief {
  kind: 'document-brief';
  artifact_family: 'document' | 'presentation' | 'spreadsheet' | 'diagram';
  document_type: string;
  document_profile: string;
  render_target: 'pdf' | 'pptx' | 'docx' | 'xlsx' | 'svg' | 'drawio' | 'mmd' | 'd2';
  locale?: string;
  layout_template_id?: string;
  payload: {
    [k: string]: unknown;
  };
}
