/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface GuidedCoordinationBrief {
  kind: 'guided-coordination-brief';
  request_text: string;
  coordination_kind:
    | 'meeting'
    | 'presentation'
    | 'narrated_video'
    | 'booking'
    | 'travel'
    | 'schedule'
    | 'onboarding'
    | 'proposal'
    | 'decision_support'
    | 'service_operation'
    | 'general';
  objective: string;
  domain_overlay_id: string;
  audience_or_counterpart?: string;
  approval_boundary?: string;
  missing_inputs: string[];
  expected_outputs: string[];
  suggested_target_actuators: string[];
  suggested_deliverables: string[];
  preference_profile_refs?: string[];
  service_binding_refs?: string[];
  assumptions?: string[];
  clarification_questions?: {
    id: string;
    question: string;
    reason: string;
    default_assumption?: string;
    impact?: string;
    [k: string]: unknown;
  }[];
  recommended_next_step?: string;
  [k: string]: unknown;
}
