/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Engine-neutral contract for text-to-image generation requests.
 */
export interface KyberionImageGenerationADF {
  kind: 'image-generation-adf';
  version: string;
  intent?: string;
  prompt: string;
  negative_prompt?: string;
  canvas: {
    width: number;
    height: number;
    [k: string]: unknown;
  };
  style?: {
    mood?: string[];
    camera?: string[];
    render_traits?: string[];
    [k: string]: unknown;
  };
  engine?: {
    provider?: string;
    model_family?: string;
    checkpoint?: string;
    steps?: number;
    cfg_scale?: number;
    sampler_name?: string;
    scheduler?: string;
    seed?: number;
    [k: string]: unknown;
  };
  output: {
    format: 'png' | 'jpg' | 'jpeg' | 'webp';
    filename_prefix?: string;
    target_path?: string;
    await_completion?: boolean;
    timeout_ms?: number;
    poll_interval_ms?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
