/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface MobileAppProfile {
  app_id: string;
  platform: 'android' | 'ios';
  title?: string;
  package_name: string;
  launch?: {
    component?: string;
    bundle_id?: string;
    app_path?: string;
  };
  selectors: {
    login?: {
      email?: Selector;
      password?: Selector;
      submit?: Selector;
    };
    passkey?: {
      trigger?: Selector;
    };
  };
  webview?: {
    entry_url?: string;
    allowed_origins?: string[];
    session_handoff?: {
      target_url?: string;
      browser_session_id?: string;
      prefer_persistent_context?: boolean;
    };
    runtime_export?: {
      format?: 'json';
      android_device_path?: string;
      ios_container_relative_path?: string;
    };
  };
}
export interface Selector {
  text?: string;
  resource_id?: string;
  class_name?: string;
  package_name?: string;
}
