/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface MobileAppProfileIndex {
  version?: string;
  profiles: {
    id: string;
    platform: 'android' | 'ios';
    title: string;
    path: string;
    description: string;
    tags?: string[];
  }[];
}
