/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Engine-neutral contract for lyric-driven or instrumental music generation requests.
 */
export interface KyberionMusicGenerationADF {
  kind: 'music-generation-adf';
  version: string;
  intent?: string;
  style: {
    genre: string;
    mood?: string[];
    vocal?: {
      presence?: boolean;
      gender?: 'female' | 'male' | 'duet' | 'mixed' | 'unspecified';
      language?: string;
      tone?: string[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  composition: {
    duration_sec: number;
    bpm?: number;
    time_signature?: string;
    key?: string;
    structure?: string[];
    [k: string]: unknown;
  };
  lyrics?: {
    mode?: 'provided' | 'instrumental' | 'assisted' | 'generate';
    text?: string;
    [k: string]: unknown;
  };
  arrangement?: {
    instruments?: string[];
    mix_traits?: string[];
    [k: string]: unknown;
  };
  engine?: {
    provider?: string;
    model_family?: string;
    profile?: 'turbo' | 'base' | 'sft';
    cfg_scale?: number;
    temperature?: number;
    top_p?: number;
    top_k?: number;
    min_p?: number;
    seed?: number;
    generate_audio_codes?: boolean;
    models?: {
      unet_name?: string;
      clip_name1?: string;
      clip_name2?: string;
      vae_name?: string;
    };
    [k: string]: unknown;
  };
  output: {
    format: 'mp3' | 'wav' | 'flac';
    filename_prefix?: string;
    target_path?: string;
    await_completion?: boolean;
    timeout_ms?: number;
    poll_interval_ms?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
