/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface SystemStatusBrief {
  kind: 'system-status-brief';
  request_text: string;
  scope: 'system' | 'surfaces' | 'actuators' | 'projects' | 'missions';
  focus_areas: string[];
  recommended_sources?: string[];
  [k: string]: unknown;
}
