/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface TestCaseADF {
  kind: 'test-case-adf';
  app_id: string;
  cases: {
    case_id: string;
    title: string;
    objective: string;
    steps: string[];
    expected: string[];
    automation_backend?: 'browser' | 'android' | 'ios';
  }[];
}
