/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface UIFlowADF {
  kind: 'ui-flow-adf';
  app_id: string;
  platform: 'browser' | 'android' | 'ios';
  entry_state?: string;
  states: {
    id: string;
    kind: 'route' | 'screen' | 'debug';
    path: string;
    guard?: string;
    selectors?: {
      [k: string]: unknown;
    };
  }[];
  transitions: {
    id: string;
    from: string;
    to: string;
    action: string;
    guard?: string;
    expected?: string;
  }[];
}
