/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Contract for video generation requests. Supports named workflow templates and embedded templates with typed parameters.
 */
export interface KyberionVideoGenerationADF {
  kind: 'video-generation-adf';
  version: string;
  intent?: string;
  prompt: string;
  negative_prompt?: string;
  composition: {
    duration_sec: number;
    fps?: number;
    aspect_ratio?: string;
    [k: string]: unknown;
  };
  engine: {
    provider: string;
    workflow_template: 'embedded' | 'basic_text_clip';
    base_workflow?: {
      [k: string]: unknown;
    };
    seed?: number;
    [k: string]: unknown;
  };
  output: {
    format: 'mp4' | 'mov' | 'webm' | 'gif';
    filename_prefix?: string;
    target_path?: string;
    await_completion?: boolean;
    timeout_ms?: number;
    poll_interval_ms?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
