/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface WebViewSessionHandoff {
  kind: 'webview-session-handoff';
  target_url: string;
  origin?: string;
  browser_session_id?: string;
  prefer_persistent_context?: boolean;
  cookies?: {
    [k: string]: unknown;
  }[];
  local_storage?: {
    [k: string]: string;
  };
  session_storage?: {
    [k: string]: string;
  };
  headers?: {
    [k: string]: string;
  };
  source?: {
    platform?: 'android' | 'ios' | 'browser';
    app_id?: string;
  };
}
