#!/usr/bin/env bash
# Register the Kyberion Browser Bridge native messaging host for Chrome/Chromium.
#
# Usage:
#   tools/adf-replay-extension/native-host/install.sh <CHROME_EXTENSION_ID>
#
# Find the extension ID at chrome://extensions (Developer mode → the unpacked
# "Kyberion Browser Bridge" card). Re-run after rebuilding or if the ID changes.
#
# Architecture note (macOS): Chrome spawns native messaging hosts with TCC
# responsibility DISCLAIMED, so the host is judged by its own executable
# identity — not Chrome's — and Chrome's own disk grants do NOT apply. We
# therefore install a small stub under the user's home (a TCC-free location for
# the spawn itself) that exec's node in-place; the ONLY identity that needs a
# disk grant (Full Disk Access, or an external-volume grant) is the node
# binary. If the repo lives on an external volume, grant node Full Disk Access:
#   System Settings → Privacy & Security → Full Disk Access → “+” → ⌘⇧G →
#   the node path printed at the end of this script.
set -euo pipefail

EXT_ID="${1:-}"
if [[ ! "$EXT_ID" =~ ^[a-p]{32}$ ]]; then
  echo "Usage: $0 <chrome-extension-id>  (copy the 32-character ID from chrome://extensions)" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
HOST_NAME="com.kyberion.browser_bridge"
HOST_JS="$REPO_ROOT/dist/scripts/browser_bridge_host.js"
STUB_DIR="$HOME/Library/Application Support/Kyberion"
STUB="$STUB_DIR/browser-bridge-launch.sh"

# Preconditions ---------------------------------------------------------------
if [ ! -f "$HOST_JS" ]; then
  echo "Host not built: $HOST_JS missing. Run 'pnpm build' (or 'npx tsc') first." >&2
  exit 1
fi
NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "node not found on PATH; install Node or activate your version manager." >&2
  exit 1
fi

# Stub launcher (home dir — see architecture note above) -----------------------
mkdir -p "$STUB_DIR"
cat > "$STUB" <<EOF
#!/bin/bash
# Kyberion Browser Bridge — generated by install.sh; do not edit (re-run install.sh).
# Chrome disclaims TCC responsibility for native hosts, so this process is
# judged by its own executable identity. We exec node in-place (same pid, no
# reads from the repo volume before exec) so only the node binary needs a disk
# grant. Diagnostics: ~/Library/Logs/kyberion-browser-bridge.log
LOG="\$HOME/Library/Logs/kyberion-browser-bridge.log"
mkdir -p "\$(dirname "\$LOG")" 2>/dev/null || true
echo "\$(date '+%Y-%m-%dT%H:%M:%S%z') pid=\$\$ stub started" >> "\$LOG" 2>/dev/null
NODE_BIN="$NODE_BIN"
if [ ! -x "\$NODE_BIN" ]; then
  echo "\$(date '+%Y-%m-%dT%H:%M:%S%z') pid=\$\$ FATAL: node missing at \$NODE_BIN — re-run install.sh" >> "\$LOG" 2>/dev/null
  exit 1
fi
# Reasoning backend may shell out to the claude CLI — Chrome starts us with a
# minimal PATH, so add the usual CLI locations.
export PATH="/opt/homebrew/bin:/usr/local/bin:\$HOME/.local/bin:\$PATH"
export KYBERION_ROOT="$REPO_ROOT"
cd "\$HOME"
exec "\$NODE_BIN" "$HOST_JS" 2>> "\$LOG"
EOF
chmod +x "$STUB"

# Manifest --------------------------------------------------------------------
MANIFEST=$(cat <<EOF
{
  "name": "$HOST_NAME",
  "description": "Kyberion Browser Bridge native messaging host",
  "path": "$STUB",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
EOF
)

# Install into every Chrome/Chromium profile dir that exists -------------------
TARGET_DIRS=(
  "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
  "$HOME/Library/Application Support/Google/Chrome Beta/NativeMessagingHosts"
  "$HOME/Library/Application Support/Google/Chrome Canary/NativeMessagingHosts"
  "$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
  "$HOME/.config/google-chrome/NativeMessagingHosts"
  "$HOME/.config/chromium/NativeMessagingHosts"
)

installed=0
for dir in "${TARGET_DIRS[@]}"; do
  parent="$(dirname "$dir")"
  if [ -d "$parent" ]; then
    mkdir -p "$dir"
    printf '%s\n' "$MANIFEST" > "$dir/$HOST_NAME.json"
    echo "installed → $dir/$HOST_NAME.json"
    installed=1
  fi
done

if [ "$installed" -eq 0 ]; then
  echo "No Chrome/Chromium profile directory found. Is the browser installed for this user?" >&2
  exit 1
fi

echo "node:      $NODE_BIN"
echo "stub:      $STUB"
echo "extension: $EXT_ID"
echo ""
echo "If the repo is on an external volume, grant the node binary Full Disk"
echo "Access (System Settings → Privacy & Security → Full Disk Access → + →"
echo "⌘⇧G → $NODE_BIN), or the host will die with 'Operation not permitted'."
echo "Done. Retry from the extension (no Chrome restart needed)."
