/*
 * Kyberion UI — vanilla DOM renderer for the A2UI `kyberion-base` catalog
 * (UI-04, SURFACE_UI_UNIFICATION_PLAN_2026-09-23 §5).
 *
 * Dependency-free ES module (plain JS + JSDoc, no build step). Static
 * surfaces (presence-studio, computer-surface) serve this file as-is and
 * import it with `<script type="module">`.
 *
 * Contract: it emits exactly the markup `kyberion-ui.css` styles
 * (knowledge/public/design-patterns/web/kyberion-ui.source.css is the source
 * of truth). The React renderer in `libs/shared-ui/src` must emit the same
 * classes, BEM elements and data attributes.
 *
 * Safety rules:
 *   - DOM is built with createElement / textContent only — never innerHTML.
 *   - hrefs are allow-listed (relative, http, https, mailto, tel); anything
 *     else (javascript:, data:, vbscript:, ...) is dropped.
 *   - Actions are never evaluated; they are handed to `onAction`.
 */
/* global document, window */
// UI-01b charts & visualisation: geometry lives in ./charts.js (shared with React).
import { KB_CHART_TYPES, layoutChart } from './charts.js';
// UI-01c settings & forms: renderers + pure helpers live in ./forms.js (shared with React).
import { createFormRenderers } from './forms.js';

// ---------------------------------------------------------------------------
// Vocabulary (single place) — keys only; text comes from the vocabulary catalog
// ---------------------------------------------------------------------------
//
// UI-01d (SURFACE_UI_UNIFICATION_PLAN_2026-09-23 §3.1): every renderer-default
// string (status labels, empty/loading text, trend words, ...) is a `ui:*` key
// of knowledge/product/orchestration/user-facing-vocabulary.json. Callers pass
// the locale's bundle (`{ locale, messages }` — `getUiMessageBundle(locale)` in
// @agent/core, or a static surface's `/shared-ui/messages/<locale>.json`); a
// key it lacks falls back to the generated default-locale block below, then to
// the key itself. Resolution never throws.

// GENERATED-UI-MESSAGES:BEGIN
// Generated by scripts/generate_vocabulary_types.ts from the `ui` domain of
// knowledge/product/orchestration/user-facing-vocabulary.json — do not edit.
/** The vocabulary catalog default locale (the language of the fallback bundle). */
export const KB_UI_DEFAULT_LOCALE = 'en';
/**
 * Built-in fallback bundle: every `ui:*` message in the default locale. Used
 * for a key the caller-supplied bundle lacks; never the primary source.
 * @type {Readonly<Record<string, string>>}
 */
export const KB_UI_DEFAULT_MESSAGES = Object.freeze({
  'ui:avatar_cancel': 'Cancel',
  'ui:avatar_current_alt': 'Current picture',
  'ui:avatar_empty': 'No picture',
  'ui:avatar_preview_alt': 'New picture preview (square crop)',
  'ui:avatar_remove': 'Remove',
  'ui:avatar_take': 'Take photo',
  'ui:avatar_upload': 'Upload photo',
  'ui:avatar_use': 'Use this photo',
  'ui:camera_cancel': 'Cancel',
  'ui:camera_choose_file': 'Choose a photo',
  'ui:camera_denied': 'Camera access was blocked. Choose a photo instead.',
  'ui:camera_live_label': 'Camera preview',
  'ui:camera_preview_alt': 'Captured photo preview',
  'ui:camera_retake': 'Retake',
  'ui:camera_start': 'Start camera',
  'ui:camera_starting': 'Starting camera…',
  'ui:camera_take': 'Take photo',
  'ui:camera_unavailable': "The camera isn't available here. Choose a photo instead.",
  'ui:camera_use': 'Use this photo',
  'ui:chart_empty': 'No data to chart',
  'ui:chart_labelled': '{title}. {summary}',
  'ui:chart_legend': 'Legend',
  'ui:chart_no_value': 'No value',
  'ui:chart_other': 'Other',
  'ui:chart_scale_high': 'High',
  'ui:chart_scale_low': 'Low',
  'ui:chart_summary_bar':
    'Bar chart: {categories} categories, {series} series, values from {min} to {max}.',
  'ui:chart_summary_donut':
    'Donut chart: {count} parts totalling {total}; the largest is {top} ({share}).',
  'ui:chart_summary_flow':
    'Flow diagram: {nodes} steps in {stages} stages with {edges} connections.',
  'ui:chart_summary_heatmap':
    'Heatmap: {rows} rows by {columns} columns, values from {min} to {max}.',
  'ui:chart_summary_line':
    'Line chart: {series} series over {points} points, values from {min} to {max}.',
  'ui:chart_summary_meter': '{value} of {max} ({percent})',
  'ui:chart_summary_sequence':
    'Sequence diagram: {messages} messages between {participants} participants.',
  'ui:chart_summary_sparkline':
    'Trend of {count} points from {first} to {last} (low {min}, high {max}).',
  'ui:chart_table_category': 'Category',
  'ui:chart_table_from': 'From',
  'ui:chart_table_message': 'Message',
  'ui:chart_table_next': 'Leads to',
  'ui:chart_table_point': 'Point',
  'ui:chart_table_series': 'Series',
  'ui:chart_table_share': 'Share',
  'ui:chart_table_stage': 'Stage',
  'ui:chart_table_status': 'Status',
  'ui:chart_table_step': 'Step',
  'ui:chart_table_time': 'Time',
  'ui:chart_table_to': 'To',
  'ui:chart_table_value': 'Value',
  'ui:chart_total': 'Total',
  'ui:disclosure_summary': 'Details',
  'ui:field_required': 'Required',
  'ui:file_cancel': 'Cancel upload of {file}',
  'ui:file_drop_accept': 'Accepted: {types}',
  'ui:file_drop_added': 'Files added: {count}',
  'ui:file_drop_browse': 'Choose files',
  'ui:file_drop_browse_single': 'Choose a file',
  'ui:file_drop_max_files': 'Up to {count} files',
  'ui:file_drop_max_size': 'Up to {size} each',
  'ui:file_drop_prompt': 'Drag files here or paste',
  'ui:file_drop_prompt_single': 'Drag a file here or paste',
  'ui:file_drop_reject_count': 'Only {count} files can be added',
  'ui:file_drop_reject_size': '{file} is larger than {size}',
  'ui:file_drop_reject_type': "{file} isn't an accepted file type",
  'ui:file_list_label': 'Selected files',
  'ui:file_remove': 'Remove {file}',
  'ui:file_status_done': 'Uploaded',
  'ui:file_status_error': 'Failed',
  'ui:file_status_queued': 'Waiting',
  'ui:file_status_uploading': 'Uploading',
  'ui:integration_connected': 'Connected',
  'ui:integration_disconnected': 'Not connected',
  'ui:integration_error': 'Connection error',
  'ui:integration_needs_reauth': 'Reconnect needed',
  'ui:meter_state_danger': 'Over the limit',
  'ui:meter_state_success': 'Within range',
  'ui:meter_state_warning': 'Near the limit',
  'ui:metric_trend_down': 'Down',
  'ui:metric_trend_flat': 'No change',
  'ui:metric_trend_up': 'Up',
  'ui:nav_label': 'Navigation',
  'ui:save_bar_clean': 'No changes',
  'ui:save_bar_dirty': 'You have unsaved changes',
  'ui:save_bar_discard': 'Discard',
  'ui:save_bar_error': "Couldn't save your changes. Try again.",
  'ui:save_bar_label': 'Unsaved changes',
  'ui:save_bar_save': 'Save',
  'ui:save_bar_saved': 'All changes saved',
  'ui:save_bar_saving': 'Saving…',
  'ui:secret_cancel': 'Cancel',
  'ui:secret_configured': 'Set · ••••{last4}',
  'ui:secret_configured_plain': 'Set',
  'ui:secret_hide': 'Hide',
  'ui:secret_not_configured': 'Not set',
  'ui:secret_paste': 'Paste',
  'ui:secret_paste_unavailable': 'Paste with Ctrl+V or ⌘V',
  'ui:secret_remove': 'Remove',
  'ui:secret_replace': 'Replace',
  'ui:secret_save': 'Save',
  'ui:secret_show': 'Show',
  'ui:secret_submitted': 'Sent. The value is not kept on this page.',
  'ui:select_placeholder': 'Select…',
  'ui:skeleton_loading': 'Loading',
  'ui:status_active': 'Active',
  'ui:status_archived': 'Archived',
  'ui:status_available': 'Available',
  'ui:status_blocked': 'Needs attention',
  'ui:status_busy': 'Busy',
  'ui:status_completed': 'Completed',
  'ui:status_connected': 'Connected',
  'ui:status_connecting': 'Connecting',
  'ui:status_connection_degraded': 'Connection degraded',
  'ui:status_connection_offline': 'Disconnected',
  'ui:status_connection_ready': 'Connected',
  'ui:status_degraded': 'Degraded',
  'ui:status_disconnected': 'Disconnected',
  'ui:status_distilling': 'Distilling lessons',
  'ui:status_done': 'Done',
  'ui:status_error': 'Error',
  'ui:status_failed': 'Failed',
  'ui:status_fallback': 'Fallback',
  'ui:status_fully_automatable': 'Ready to run',
  'ui:status_missing': 'Not set up',
  'ui:status_missing_runtime_prerequisites': 'Missing runtime prerequisites',
  'ui:status_mission_blocked': 'Stopped',
  'ui:status_mission_done': 'Done',
  'ui:status_needs_assets': 'Needs external assets',
  'ui:status_needs_clarification': 'Needs clarification',
  'ui:status_needs_external_assets': 'Needs external assets',
  'ui:status_needs_runtime_prerequisites': 'Missing runtime prerequisites',
  'ui:status_needs_setup': 'Setup required',
  'ui:status_not_applicable': 'Not required',
  'ui:status_offline': 'Offline',
  'ui:status_paused': 'Paused',
  'ui:status_pending': 'Pending',
  'ui:status_planned': 'Planned',
  'ui:status_provider_missing': 'Not installed',
  'ui:status_provider_ready': 'Available',
  'ui:status_provider_unavailable': 'Error',
  'ui:status_readiness_ready': 'Ready to run',
  'ui:status_ready': 'Ready',
  'ui:status_recovered': 'Recovered',
  'ui:status_review': 'In review',
  'ui:status_running': 'Running',
  'ui:status_stale': 'Slow to respond',
  'ui:status_stopped': 'Stopped',
  'ui:status_unavailable': 'Unavailable',
  'ui:status_working': 'Working',
  'ui:table_empty': 'No data',
  'ui:tabs_label': 'Views',
  'ui:text_count': '{count} / {max}',
  'ui:unknown_component': 'Unsupported component: {type}',
  'ui:value_no': 'No',
  'ui:value_yes': 'Yes',
});
// GENERATED-UI-MESSAGES:END

/**
 * Message key for each canonical status (a2ui-catalog.ts KB_STATUS_VALUES).
 * @type {Readonly<Record<string, string>>}
 */
export const KB_STATUS_MESSAGE_KEYS = Object.freeze({
  active: 'ui:status_active',
  archived: 'ui:status_archived',
  available: 'ui:status_available',
  blocked: 'ui:status_blocked',
  busy: 'ui:status_busy',
  completed: 'ui:status_completed',
  connected: 'ui:status_connected',
  connecting: 'ui:status_connecting',
  degraded: 'ui:status_degraded',
  disconnected: 'ui:status_disconnected',
  distilling: 'ui:status_distilling',
  done: 'ui:status_done',
  error: 'ui:status_error',
  failed: 'ui:status_failed',
  fallback: 'ui:status_fallback',
  fully_automatable: 'ui:status_fully_automatable',
  missing: 'ui:status_missing',
  missing_runtime_prerequisites: 'ui:status_missing_runtime_prerequisites',
  'n/a': 'ui:status_not_applicable',
  needs_assets: 'ui:status_needs_assets',
  needs_clarification: 'ui:status_needs_clarification',
  needs_external_assets: 'ui:status_needs_external_assets',
  needs_runtime_prerequisites: 'ui:status_needs_runtime_prerequisites',
  needs_setup: 'ui:status_needs_setup',
  offline: 'ui:status_offline',
  paused: 'ui:status_paused',
  pending: 'ui:status_pending',
  planned: 'ui:status_planned',
  ready: 'ui:status_ready',
  recovered: 'ui:status_recovered',
  review: 'ui:status_review',
  running: 'ui:status_running',
  stale: 'ui:status_stale',
  stopped: 'ui:status_stopped',
  unavailable: 'ui:status_unavailable',
  working: 'ui:status_working',
});

/**
 * Domain-specific wording (`ui:status-pill.domain`), where the vocabulary
 * words a status differently from the default above.
 * @type {Readonly<Record<string, Readonly<Record<string, string>>>>}
 */
export const KB_STATUS_DOMAIN_MESSAGE_KEYS = Object.freeze({
  readiness: Object.freeze({ ready: 'ui:status_readiness_ready' }),
  connection: Object.freeze({
    ready: 'ui:status_connection_ready',
    degraded: 'ui:status_connection_degraded',
    offline: 'ui:status_connection_offline',
  }),
  provider: Object.freeze({
    ready: 'ui:status_provider_ready',
    missing: 'ui:status_provider_missing',
    unavailable: 'ui:status_provider_unavailable',
  }),
  mission: Object.freeze({ blocked: 'ui:status_mission_blocked', done: 'ui:status_mission_done' }),
  progress: Object.freeze({}),
  runtime: Object.freeze({}),
});

/**
 * Keys of the remaining renderer-default strings.
 * @type {Readonly<Record<string, string>>}
 */
export const KB_UI_MESSAGE_KEYS = Object.freeze({
  tableEmpty: 'ui:table_empty',
  skeletonLoading: 'ui:skeleton_loading',
  unknownComponent: 'ui:unknown_component',
  valueYes: 'ui:value_yes',
  valueNo: 'ui:value_no',
  disclosureSummary: 'ui:disclosure_summary',
  navLabel: 'ui:nav_label',
  tabsLabel: 'ui:tabs_label',
  trendUp: 'ui:metric_trend_up',
  trendDown: 'ui:metric_trend_down',
  trendFlat: 'ui:metric_trend_flat',
});

const hasOwn = (object, key) => Object.prototype.hasOwnProperty.call(object, key);

/** Replace `{name}` placeholders with `params[name]`; unknown names stay as-is. */
function interpolate(template, params) {
  if (!isRecord(params)) return template;
  return template.replace(/\{([A-Za-z0-9_]+)\}/g, (match, name) =>
    hasOwn(params, name) && params[name] !== undefined && params[name] !== null
      ? String(params[name])
      : match
  );
}

/**
 * Build the translate function the renderers use. Order: a caller `t` (its
 * result wins when it is a non-empty string other than the key), then the
 * caller's `messages` bundle, then the generated default-locale block, then
 * the key itself. Never throws.
 * @param {{ messages?: Record<string, string>, t?: (key: string, params?: Record<string, unknown>) => string }} [options]
 * @returns {(key: string, params?: Record<string, unknown>) => string}
 */
export function createTranslator(options = {}) {
  const messages = isRecord(options && options.messages) ? options.messages : null;
  const custom = options && typeof options.t === 'function' ? options.t : null;
  return function translate(key, params) {
    if (custom) {
      try {
        const text = custom(key, params);
        if (typeof text === 'string' && text && text !== key) return text;
      } catch {
        // fall through to the bundle
      }
    }
    let template = key;
    if (messages && hasOwn(messages, key) && typeof messages[key] === 'string' && messages[key]) {
      template = messages[key];
    } else if (hasOwn(KB_UI_DEFAULT_MESSAGES, key)) {
      template = KB_UI_DEFAULT_MESSAGES[key];
    }
    return interpolate(template, params);
  };
}

const defaultTranslate = createTranslator();

/** Message key of a status label (domain wording first); null for non-canonical values. */
export function statusMessageKey(status, domain) {
  const byDomain =
    typeof domain === 'string' && hasOwn(KB_STATUS_DOMAIN_MESSAGE_KEYS, domain)
      ? KB_STATUS_DOMAIN_MESSAGE_KEYS[domain]
      : null;
  if (byDomain && hasOwn(byDomain, status)) return byDomain[status];
  return typeof status === 'string' && hasOwn(KB_STATUS_MESSAGE_KEYS, status)
    ? KB_STATUS_MESSAGE_KEYS[status]
    : null;
}

/**
 * Resolve the visible label of a status pill: explicit `label`, else the
 * vocabulary label through `translate`, else the raw status.
 */
export function statusLabel(status, domain, label, translate = defaultTranslate) {
  if (typeof label === 'string' && label.trim()) return label;
  const key = statusMessageKey(status, domain);
  return key ? translate(key) : String(status ?? '');
}

/** Legacy protocol types rendered as catalog components (a2ui-catalog.ts KYBERION_BASE_ALIASES). */
export const KB_ALIASES = Object.freeze({
  text: 'ui:text',
  button: 'ui:button',
  card: 'ui:section',
  container: 'ui:stack',
});

/**
 * 24x24 stroke icons (`ui:nav-rail` items' `icon` prop, `ui:metric` trend
 * arrows). Unknown names render no icon. Path data only — this is the single
 * source the React renderer builds `<path>` elements from (`icons.tsx`).
 * @type {Readonly<Record<string, readonly string[]>>}
 */
export const KB_ICON_PATHS = Object.freeze({
  home: ['M3 11l9-7 9 7', 'M5 10v10h14V10', 'M10 20v-6h4v6'],
  inbox: ['M3 13h5l2 3h4l2-3h5', 'M5 5h14l2 8v6H3v-6z'],
  check: ['M20 6L9 17l-5-5'],
  approval: ['M9 12l2 2 4-4', 'M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z'],
  mission: ['M4 20V4', 'M4 4h12l-2 4 2 4H4'],
  chart: ['M4 20V10', 'M10 20V4', 'M16 20v-7', 'M3 20h18'],
  list: ['M8 6h13', 'M8 12h13', 'M8 18h13', 'M3 6h.01', 'M3 12h.01', 'M3 18h.01'],
  clock: ['M12 7v5l3 2', 'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z'],
  chat: ['M4 5h16v11H9l-5 4z'],
  search: ['M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14z', 'M20 20l-4-4'],
  folder: ['M3 6h6l2 2h10v11H3z'],
  user: ['M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8z', 'M4 21c1-4 4-6 8-6s7 2 8 6'],
  settings: [
    'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z',
    'M19 12l2-1-1-3-2 .2-1.4-1.4.2-2-3-1-1 2h-2l-1-2-3 1 .2 2L6.6 8.2 4.6 8l-1 3 2 1v0l-2 1 1 3 2-.2 1.4 1.4-.2 2 3 1 1-2h2l1 2 3-1-.2-2 1.4-1.4 2 .2 1-3z',
  ],
  help: [
    'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z',
    'M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.6',
    'M12 17h.01',
  ],
  shield: ['M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z'],
  bell: ['M6 16V11a6 6 0 1 1 12 0v5l2 2H4z', 'M10 21h4'],
  book: ['M4 5a2 2 0 0 1 2-2h14v16H6a2 2 0 0 0-2 2z', 'M4 19V5'],
  'arrow-up': ['M12 19V5m-6 6 6-6 6 6'],
  'arrow-down': ['M12 5v14m-6-6 6 6 6-6'],
  'arrow-right': ['M5 12h14m-6-6 6 6-6 6'],
});

/** `ui:metric` trend arrow icon and its accessible word per `trend` value. */
const TREND_ICONS = Object.freeze({ up: 'arrow-up', down: 'arrow-down', flat: 'arrow-right' });
const TREND_MESSAGE_KEYS = Object.freeze({
  up: KB_UI_MESSAGE_KEYS.trendUp,
  down: KB_UI_MESSAGE_KEYS.trendDown,
  flat: KB_UI_MESSAGE_KEYS.trendFlat,
});

const SVG_NS = 'http://www.w3.org/2000/svg';
// Single source for `safeHref` — the React renderer re-exports this
// implementation (`safety.ts`) instead of keeping its own copy.
const SAFE_SCHEMES = new Set(['http:', 'https:', 'mailto:', 'tel:']);
// eslint-disable-next-line no-control-regex
const CONTROL_CHARS = /[\u0000-\u001f\u007f]/;
const SCHEME_PREFIX = /^([a-z][a-z0-9+.-]*):/i;
const WIDTH_PATTERN = /^(auto|[0-9]{1,4}(px|rem|ch|%))$/;
const MAX_DEPTH = 32;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Return a navigable href, or null when it is empty, contains a control
 * character, is protocol-relative (`//host`, backslash tricks) or uses a
 * scheme outside the allow-list (javascript:, data:, vbscript:, file:, ...).
 * Allowed schemes: http(s), mailto, tel; same-origin paths / fragments /
 * queries pass through unchanged.
 * @param {unknown} value
 * @returns {string | null}
 */
export function safeHref(value) {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > 2048 || CONTROL_CHARS.test(trimmed)) return null;
  const lower = trimmed.toLowerCase();
  if (lower.startsWith('//') || lower.startsWith('/\\') || lower.startsWith('\\')) return null;
  const scheme = SCHEME_PREFIX.exec(lower);
  if (scheme) return SAFE_SCHEMES.has(`${scheme[1]}:`) ? trimmed : null;
  return trimmed;
}

function str(value) {
  if (value === null || value === undefined) return '';
  return String(value);
}

function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function el(ctx, tag, className, text) {
  const node = ctx.doc.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined && text !== null && text !== '') node.textContent = str(text);
  return node;
}

function setData(node, name, value) {
  if (value === undefined || value === null || value === '') return;
  node.setAttribute(`data-${name}`, str(value));
}

/** Resolve a component type (or legacy alias) to its `ui:*` type; null when unknown. */
export function resolveType(type) {
  if (typeof type !== 'string') return null;
  if (type.startsWith('ui:') && Object.prototype.hasOwnProperty.call(RENDERERS, type)) return type;
  return Object.prototype.hasOwnProperty.call(KB_ALIASES, type) ? KB_ALIASES[type] : null;
}

function normalizeAction(action) {
  if (typeof action === 'string' && action) return { id: action };
  if (isRecord(action) && typeof action.id === 'string' && action.id) {
    return isRecord(action.payload)
      ? { id: action.id, payload: action.payload }
      : { id: action.id };
  }
  return null;
}

/**
 * Bare `<svg>` for an icon name (no wrapper element); null for unknown names.
 * Callers that need a wrapper (e.g. `.kb-nav-rail__icon`) add it themselves.
 * Decorative (`aria-hidden`) unless `label` is given, which makes it an
 * `role="img"` with that accessible name.
 */
function icon(ctx, name, size, label) {
  const paths =
    typeof name === 'string' && Object.prototype.hasOwnProperty.call(KB_ICON_PATHS, name)
      ? KB_ICON_PATHS[name]
      : null;
  if (!paths) return null;
  const svg = ctx.doc.createElementNS(SVG_NS, 'svg');
  const dimension = String(size || 18);
  svg.setAttribute('viewBox', '0 0 24 24');
  svg.setAttribute('width', dimension);
  svg.setAttribute('height', dimension);
  svg.setAttribute('fill', 'none');
  svg.setAttribute('stroke', 'currentColor');
  svg.setAttribute('stroke-width', '1.8');
  svg.setAttribute('stroke-linecap', 'round');
  svg.setAttribute('stroke-linejoin', 'round');
  if (label) {
    svg.setAttribute('role', 'img');
    svg.setAttribute('aria-label', str(label));
  } else {
    svg.setAttribute('aria-hidden', 'true');
  }
  svg.setAttribute('focusable', 'false');
  for (const d of paths) {
    const path = ctx.doc.createElementNS(SVG_NS, 'path');
    path.setAttribute('d', d);
    svg.appendChild(path);
  }
  return svg;
}

/**
 * Render a `KbActionRef` / `ui:button` as `a.kb-btn` (href) or
 * `button.kb-btn` (action). Returns null when neither target is given.
 * An unsafe or disabled href keeps the visual as a non-navigating
 * `a[aria-disabled][role=link]` rather than disappearing.
 */
function actionButton(ctx, ref, defaultVariant, source) {
  if (!isRecord(ref)) return null;
  const label = str(ref.label ?? ref.text);
  if (!label) return null;
  const variant = ['primary', 'secondary', 'danger', 'ghost'].includes(ref.variant)
    ? ref.variant
    : defaultVariant;
  const className = `kb-btn kb-btn--${variant}`;
  const disabled = ref.disabled === true;
  const action = normalizeAction(ref.action);
  if (action) {
    const button = el(ctx, 'button', className, label);
    button.setAttribute('type', 'button');
    setData(button, 'action-id', action.id);
    if (disabled) button.disabled = true;
    button.addEventListener('click', () => {
      if (typeof ctx.onAction === 'function') ctx.onAction(action, source);
    });
    return button;
  }
  if (ref.href === undefined) return null;
  const href = safeHref(ref.href);
  const link = el(ctx, 'a', className, label);
  if (href && !disabled) {
    link.setAttribute('href', href);
    return link;
  }
  // Unsafe or disabled link: keep the visual, drop the navigation target.
  link.setAttribute('aria-disabled', 'true');
  link.setAttribute('role', 'link');
  link.setAttribute('aria-label', label);
  return link;
}

function appendActions(ctx, container, refs, defaultVariant, source) {
  if (!Array.isArray(refs)) return 0;
  let count = 0;
  for (const ref of refs) {
    const node = actionButton(ctx, ref, defaultVariant, source);
    if (node) {
      container.appendChild(node);
      count += 1;
    }
  }
  return count;
}

function statusPill(ctx, status, domain, label) {
  const pill = el(ctx, 'span', 'kb-status-pill');
  setData(pill, 'status', status);
  setData(pill, 'domain', domain);
  const glyph = el(ctx, 'span', 'kb-status-pill__icon');
  glyph.setAttribute('aria-hidden', 'true');
  pill.appendChild(glyph);
  pill.appendChild(
    el(ctx, 'span', 'kb-status-pill__label', statusLabel(status, domain, label, ctx.t))
  );
  return pill;
}

function isStatusValue(value) {
  return typeof value === 'string' && hasOwn(KB_STATUS_MESSAGE_KEYS, value);
}

function appendChildren(ctx, parent, component, depth) {
  const ids = Array.isArray(component.children) ? component.children : [];
  for (const id of ids) {
    const child = renderById(ctx, id, depth + 1);
    if (child) parent.appendChild(child);
  }
}

function renderById(ctx, id, depth) {
  if (typeof id !== 'string' || !ctx.lookup || depth > MAX_DEPTH) return null;
  if (ctx.visiting.has(id)) return null; // cycle guard
  const component = ctx.lookup.get(id);
  if (!component) return null;
  ctx.visiting.add(id);
  try {
    return renderWithDepth(component, ctx, depth);
  } finally {
    ctx.visiting.delete(id);
  }
}

// ---------------------------------------------------------------------------
// Per-type renderers: (ctx, props, component, depth) => Element | null
// ---------------------------------------------------------------------------

const RENDERERS = {
  'ui:app-shell'(ctx, p, c, depth) {
    const root = el(ctx, 'div', 'kb-app-shell');
    if (p.density === 'comfortable' || p.density === 'compact') setData(root, 'density', p.density);
    if (p.theme === 'light' || p.theme === 'dark') setData(root, 'theme', p.theme);
    setData(root, 'role', p.role);
    let nav = null;
    const main = el(ctx, 'main', 'kb-app-shell__main');
    const ids = Array.isArray(c.children) ? c.children : [];
    for (const id of ids) {
      const child = ctx.lookup && ctx.lookup.get(id);
      const node = renderById(ctx, id, depth + 1);
      if (!node) continue;
      if (child && resolveType(child.type) === 'ui:nav-rail' && !nav) {
        nav = el(ctx, 'div', 'kb-app-shell__nav');
        nav.appendChild(node);
      } else {
        main.appendChild(node);
      }
    }
    if (nav) root.appendChild(nav);
    root.appendChild(main);
    return root;
  },

  'ui:page-header'(ctx, p, c) {
    const root = el(ctx, 'header', 'kb-page-header');
    const titles = el(ctx, 'div', 'kb-page-header__titles');
    const title = el(ctx, 'h1', 'kb-page-header__title');
    title.appendChild(ctx.doc.createTextNode(str(p.title)));
    if (isRecord(p.role_badge) && p.role_badge.label) {
      title.appendChild(badge(ctx, p.role_badge));
    }
    titles.appendChild(title);
    if (p.subtitle) titles.appendChild(el(ctx, 'p', 'kb-page-header__subtitle', p.subtitle));
    root.appendChild(titles);
    const actions = el(ctx, 'div', 'kb-page-header__actions');
    if (appendActions(ctx, actions, p.actions, 'secondary', c) > 0) root.appendChild(actions);
    return root;
  },

  'ui:nav-rail'(ctx, p) {
    const root = el(ctx, 'nav', 'kb-nav-rail');
    root.setAttribute('aria-label', str(p.label) || ctx.t(KB_UI_MESSAGE_KEYS.navLabel));
    const list = navList(ctx, p.items);
    if (list) root.appendChild(list);
    const footerList = navList(ctx, p.footer_items);
    if (footerList) {
      const footer = el(ctx, 'div', 'kb-nav-rail__footer');
      footer.appendChild(footerList);
      root.appendChild(footer);
    }
    return root;
  },

  'ui:tabs'(ctx, p, c) {
    const items = Array.isArray(p.items) ? p.items.filter(isRecord) : [];
    const asLinks = items.some((item) => typeof item.href === 'string');
    const root = el(ctx, asLinks ? 'nav' : 'div', 'kb-tabs');
    setData(root, 'overflow', p.overflow === 'menu' ? 'menu' : 'wrap');
    if (!asLinks) root.setAttribute('role', 'tablist');
    root.setAttribute('aria-label', str(p.label) || ctx.t(KB_UI_MESSAGE_KEYS.tabsLabel));
    for (const item of items) {
      const active = p.active !== undefined && item.id === p.active;
      let tab;
      if (asLinks) {
        const href = safeHref(item.href);
        if (href) {
          tab = el(ctx, 'a', 'kb-tabs__tab');
          tab.setAttribute('href', href);
        } else {
          tab = el(ctx, 'span', 'kb-tabs__tab');
          tab.setAttribute('aria-disabled', 'true');
        }
        if (active) tab.setAttribute('aria-current', 'page');
      } else {
        tab = el(ctx, 'button', 'kb-tabs__tab');
        tab.setAttribute('type', 'button');
        tab.setAttribute('role', 'tab');
        tab.setAttribute('aria-selected', active ? 'true' : 'false');
        tab.addEventListener('click', () => {
          if (typeof ctx.onAction === 'function') {
            ctx.onAction({ id: 'tabs.select', payload: { tab: str(item.id) } }, c);
          }
        });
      }
      setData(tab, 'tab-id', item.id);
      tab.appendChild(ctx.doc.createTextNode(str(item.label)));
      if (typeof item.count === 'number')
        tab.appendChild(el(ctx, 'span', 'kb-tabs__count', item.count));
      root.appendChild(tab);
    }
    return root;
  },

  'ui:stack'(ctx, p, c, depth) {
    const root = el(ctx, 'div', 'kb-stack');
    setData(root, 'gap', p.gap);
    setData(root, 'direction', p.direction === 'horizontal' ? 'horizontal' : undefined);
    setData(root, 'align', p.align);
    if (p.wrap === true) setData(root, 'wrap', 'true');
    appendChildren(ctx, root, c, depth);
    return root;
  },

  'ui:grid'(ctx, p, c, depth) {
    const root = el(ctx, 'div', 'kb-grid');
    setData(root, 'gap', p.gap);
    if (Number.isInteger(p.columns) && p.columns >= 1 && p.columns <= 6)
      setData(root, 'columns', p.columns);
    setData(root, 'min-column-width', p.min_column_width);
    appendChildren(ctx, root, c, depth);
    return root;
  },

  'ui:section'(ctx, p, c, depth) {
    const root = el(ctx, 'section', 'kb-section');
    setData(root, 'tone', p.tone);
    const title = p.title ?? p.heading;
    const heading = el(ctx, 'div', 'kb-section__heading');
    if (title) heading.appendChild(el(ctx, 'h2', 'kb-section__title', title));
    if (p.description) heading.appendChild(el(ctx, 'p', 'kb-section__description', p.description));
    const actions = el(ctx, 'div', 'kb-section__actions');
    const actionCount = appendActions(ctx, actions, p.actions, 'secondary', c);
    if (heading.childNodes.length > 0 || actionCount > 0) {
      const header = el(ctx, 'header', 'kb-section__header');
      if (heading.childNodes.length > 0) header.appendChild(heading);
      if (actionCount > 0) header.appendChild(actions);
      root.appendChild(header);
    }
    appendChildren(ctx, root, c, depth);
    return root;
  },

  'ui:next-action'(ctx, p, c) {
    const state = p.state === 'loading' || p.state === 'empty' ? p.state : 'ready';
    const root = el(ctx, 'section', 'kb-next-action');
    setData(root, 'state', state);
    if (state === 'loading') root.setAttribute('aria-busy', 'true');
    const body = el(ctx, 'div', 'kb-next-action__body');
    if (p.eyebrow) body.appendChild(el(ctx, 'p', 'kb-next-action__eyebrow', p.eyebrow));
    body.appendChild(el(ctx, 'h2', 'kb-next-action__title', p.title));
    if (p.reason) body.appendChild(el(ctx, 'p', 'kb-next-action__reason', p.reason));
    root.appendChild(body);
    const actions = el(ctx, 'div', 'kb-next-action__actions');
    let count = 0;
    const primary = actionButton(ctx, p.primary, 'primary', c);
    if (primary) {
      actions.appendChild(primary);
      count += 1;
    }
    const secondary = actionButton(ctx, p.secondary, 'secondary', c);
    if (secondary) {
      actions.appendChild(secondary);
      count += 1;
    }
    if (count > 0) root.appendChild(actions);
    return root;
  },

  'ui:metric'(ctx, p) {
    const root = el(ctx, 'div', 'kb-metric');
    setData(root, 'tone', p.tone);
    const trendIcon = Object.prototype.hasOwnProperty.call(TREND_ICONS, p.trend)
      ? TREND_ICONS[p.trend]
      : undefined;
    setData(root, 'trend', trendIcon ? p.trend : undefined);
    root.appendChild(el(ctx, 'span', 'kb-metric__label', p.label));
    const value = el(ctx, 'span', 'kb-metric__value', p.value);
    if (p.unit) value.appendChild(el(ctx, 'span', 'kb-metric__unit', p.unit));
    root.appendChild(value);
    if (p.delta) {
      const delta = el(ctx, 'span', 'kb-metric__delta');
      const svg = trendIcon ? icon(ctx, trendIcon, 12, ctx.t(TREND_MESSAGE_KEYS[p.trend])) : null;
      if (svg) delta.appendChild(svg);
      delta.appendChild(ctx.doc.createTextNode(str(p.delta)));
      root.appendChild(delta);
    }
    if (p.description) root.appendChild(el(ctx, 'span', 'kb-metric__description', p.description));
    return root;
  },

  'ui:kv'(ctx, p) {
    const root = el(ctx, 'dl', 'kb-kv');
    for (const item of Array.isArray(p.items) ? p.items : []) {
      if (!isRecord(item)) continue;
      root.appendChild(el(ctx, 'dt', 'kb-kv__label', item.label));
      const value = el(ctx, 'dd', 'kb-kv__value', displayScalar(ctx, item.value));
      if (item.mono === true) setData(value, 'mono', 'true');
      root.appendChild(value);
    }
    return root;
  },

  'ui:table'(ctx, p) {
    const wrap = el(ctx, 'div', 'kb-table-wrap');
    const table = el(ctx, 'table', 'kb-table');
    if (p.caption) table.appendChild(el(ctx, 'caption', '', p.caption));
    const columns = (Array.isArray(p.columns) ? p.columns : []).filter(
      (col) => isRecord(col) && typeof col.key === 'string'
    );
    const thead = el(ctx, 'thead');
    const headRow = el(ctx, 'tr');
    for (const col of columns) {
      const th = el(ctx, 'th', '', col.label);
      th.setAttribute('scope', 'col');
      setData(th, 'align', col.align);
      if (typeof col.width === 'string' && WIDTH_PATTERN.test(col.width))
        th.style.width = col.width;
      headRow.appendChild(th);
    }
    thead.appendChild(headRow);
    table.appendChild(thead);
    const tbody = el(ctx, 'tbody');
    const rows = Array.isArray(p.rows) ? p.rows.filter(isRecord) : [];
    if (rows.length === 0) {
      const tr = el(ctx, 'tr');
      const td = el(ctx, 'td', 'kb-table__empty', p.empty || ctx.t(KB_UI_MESSAGE_KEYS.tableEmpty));
      td.setAttribute('colspan', String(Math.max(columns.length, 1)));
      tr.appendChild(td);
      tbody.appendChild(tr);
    }
    for (const row of rows) {
      const tr = el(ctx, 'tr');
      const href = p.row_href_key ? safeHref(row[p.row_href_key]) : null;
      if (href) {
        setData(tr, 'href', href);
        tr.tabIndex = 0;
        const go = () => {
          if (ctx.win && ctx.win.location) ctx.win.location.assign(href);
        };
        tr.addEventListener('click', go);
        tr.addEventListener('keydown', (event) => {
          if (event.key === 'Enter') go();
        });
      }
      for (const col of columns) {
        const td = el(ctx, 'td');
        setData(td, 'align', col.align);
        if (col.mono === true) setData(td, 'mono', 'true');
        const value = row[col.key];
        // Convention: a `status` / `*_status` column holding a canonical
        // status value renders as a status pill (icon + text).
        if ((col.key === 'status' || col.key.endsWith('_status')) && isStatusValue(value)) {
          td.appendChild(statusPill(ctx, value));
        } else {
          td.textContent = displayScalar(ctx, value);
        }
        tr.appendChild(td);
      }
      tbody.appendChild(tr);
    }
    table.appendChild(tbody);
    wrap.appendChild(table);
    return wrap;
  },

  'ui:list'(ctx, p) {
    const root = el(ctx, 'ul', 'kb-list');
    setData(root, 'variant', p.variant === 'timeline' ? 'timeline' : 'plain');
    for (const item of Array.isArray(p.items) ? p.items : []) {
      if (!isRecord(item)) continue;
      const li = el(ctx, 'li', 'kb-list__item');
      setData(li, 'status', item.status);
      const body = el(ctx, 'div', 'kb-list__body');
      const href = safeHref(item.href);
      const title = el(ctx, href ? 'a' : 'span', 'kb-list__title', item.title);
      if (href) title.setAttribute('href', href);
      body.appendChild(title);
      if (item.meta) body.appendChild(el(ctx, 'span', 'kb-list__meta', item.meta));
      li.appendChild(body);
      if (isStatusValue(item.status)) li.appendChild(statusPill(ctx, item.status));
      root.appendChild(li);
    }
    return root;
  },

  'ui:text'(ctx, p) {
    const variant = ['body', 'muted', 'caption', 'mono', 'title'].includes(p.variant)
      ? p.variant
      : 'body';
    return el(ctx, 'p', `kb-text kb-text--${variant}`, p.text ?? p.value ?? p.content ?? p.label);
  },

  'ui:status-pill'(ctx, p) {
    return statusPill(ctx, str(p.status), p.domain, p.label);
  },

  'ui:badge'(ctx, p) {
    return badge(ctx, p);
  },

  'ui:callout'(ctx, p, c) {
    const tone = ['info', 'success', 'warning', 'danger'].includes(p.tone) ? p.tone : 'info';
    const root = el(ctx, 'div', 'kb-callout');
    setData(root, 'tone', tone);
    root.setAttribute('role', tone === 'danger' ? 'alert' : 'note');
    const glyph = el(ctx, 'span', 'kb-callout__icon');
    glyph.setAttribute('aria-hidden', 'true');
    root.appendChild(glyph);
    const content = el(ctx, 'div', 'kb-callout__content');
    content.appendChild(el(ctx, 'p', 'kb-callout__title', p.title));
    if (p.body) content.appendChild(el(ctx, 'p', 'kb-callout__body', p.body));
    const action = actionButton(ctx, p.action, 'secondary', c);
    if (action) {
      const holder = el(ctx, 'div', 'kb-callout__action');
      holder.appendChild(action);
      content.appendChild(holder);
    }
    root.appendChild(content);
    return root;
  },

  'ui:empty-state'(ctx, p, c) {
    const root = el(ctx, 'div', 'kb-empty-state');
    root.appendChild(el(ctx, 'p', 'kb-empty-state__title', p.title));
    if (p.body) root.appendChild(el(ctx, 'p', 'kb-empty-state__body', p.body));
    const action = actionButton(ctx, p.action, 'primary', c);
    if (action) {
      const holder = el(ctx, 'div', 'kb-empty-state__action');
      holder.appendChild(action);
      root.appendChild(holder);
    }
    return root;
  },

  'ui:skeleton'(ctx, p) {
    const shape = p.shape === 'card' || p.shape === 'table' ? p.shape : 'text';
    const root = el(ctx, 'div', 'kb-skeleton');
    setData(root, 'shape', shape);
    root.setAttribute('role', 'status');
    root.setAttribute('aria-busy', 'true');
    root.setAttribute('aria-label', ctx.t(KB_UI_MESSAGE_KEYS.skeletonLoading));
    const lines = Number.isInteger(p.lines) ? Math.min(Math.max(p.lines, 1), 12) : 3;
    for (let index = 0; index < lines; index += 1) {
      const line = el(ctx, 'span', 'kb-skeleton__line');
      line.setAttribute('aria-hidden', 'true');
      root.appendChild(line);
    }
    return root;
  },

  'ui:button'(ctx, p, c) {
    return actionButton(ctx, p, 'secondary', c);
  },

  'ui:disclosure'(ctx, p, c, depth) {
    const root = el(ctx, 'details', 'kb-disclosure');
    if (p.open === true) root.open = true;
    root.appendChild(
      el(ctx, 'summary', '', p.summary || ctx.t(KB_UI_MESSAGE_KEYS.disclosureSummary))
    );
    const body = el(ctx, 'div', 'kb-disclosure__body');
    appendChildren(ctx, body, c, depth);
    root.appendChild(body);
    return root;
  },
};

// UI-01b: chart / visualisation types — `charts.js` lays out a vnode tree,
// built here with createElement / createElementNS (never innerHTML).
const SVG_TAGS = new Set(['svg', 'g', 'path', 'line', 'rect', 'circle', 'text', 'tspan', 'title']);

function buildVNode(ctx, node, inSvg) {
  if (!node) return null;
  if (typeof node.text === 'string') return ctx.doc.createTextNode(node.text);
  const svg = inSvg || node.tag === 'svg';
  const element =
    svg && SVG_TAGS.has(node.tag)
      ? ctx.doc.createElementNS(SVG_NS, node.tag)
      : ctx.doc.createElement(node.tag);
  for (const [name, value] of Object.entries(node.attrs || {})) element.setAttribute(name, value);
  for (const child of node.children || []) {
    const built = buildVNode(ctx, child, svg);
    if (built) element.appendChild(built);
  }
  return element;
}

// UI-01c settings & forms (catalog order: base types → forms → charts).
Object.assign(
  RENDERERS,
  createFormRenderers({
    el,
    setData,
    actionButton,
    statusPill,
    appendChildren,
    safeHref,
    iconPaths: KB_ICON_PATHS,
  })
);

for (const type of KB_CHART_TYPES) {
  RENDERERS[type] = (ctx, p) =>
    buildVNode(
      ctx,
      layoutChart(type, p, {
        t: ctx.t,
        locale: ctx.locale,
        statusLabel: (status) => statusLabel(status, undefined, undefined, ctx.t),
      }),
      false
    );
}

function badge(ctx, p) {
  const node = el(ctx, 'span', 'kb-badge', p.label);
  setData(node, 'tone', p.tone);
  setData(node, 'role', p.role);
  return node;
}

function navList(ctx, items) {
  if (!Array.isArray(items) || items.length === 0) return null;
  const list = el(ctx, 'ul', 'kb-nav-rail__list');
  for (const item of items) {
    if (!isRecord(item)) continue;
    const li = el(ctx, 'li');
    const href = safeHref(item.href);
    // A safe href is a real link; otherwise a non-interactive span (never an
    // `<a>` without a navigable target).
    const link = el(ctx, href ? 'a' : 'span', 'kb-nav-rail__item');
    if (href) link.setAttribute('href', href);
    setData(link, 'nav-id', item.id);
    if (item.active === true) {
      link.setAttribute('aria-current', 'page');
      setData(link, 'active', 'true');
    }
    const svg = icon(ctx, item.icon);
    if (svg) {
      const wrap = el(ctx, 'span', 'kb-nav-rail__icon');
      wrap.setAttribute('aria-hidden', 'true');
      wrap.appendChild(svg);
      link.appendChild(wrap);
    }
    const text = el(ctx, 'span', 'kb-nav-rail__text');
    text.appendChild(el(ctx, 'span', 'kb-nav-rail__label', item.label));
    if (item.hint) text.appendChild(el(ctx, 'span', 'kb-nav-rail__hint', item.hint));
    link.appendChild(text);
    li.appendChild(link);
    list.appendChild(li);
  }
  return list;
}

function displayScalar(ctx, value) {
  if (value === null || value === undefined || value === '') return '—';
  if (value === true) return ctx.t(KB_UI_MESSAGE_KEYS.valueYes);
  if (value === false) return ctx.t(KB_UI_MESSAGE_KEYS.valueNo);
  return str(value);
}

function debugWarning(ctx, type) {
  const root = el(ctx, 'div', 'kb-callout');
  setData(root, 'tone', 'warning');
  root.setAttribute('role', 'note');
  setData(root, 'unknown-type', type);
  const glyph = el(ctx, 'span', 'kb-callout__icon');
  glyph.setAttribute('aria-hidden', 'true');
  root.appendChild(glyph);
  const content = el(ctx, 'div', 'kb-callout__content');
  content.appendChild(
    el(
      ctx,
      'p',
      'kb-callout__title',
      ctx.t(KB_UI_MESSAGE_KEYS.unknownComponent, { type: str(type) })
    )
  );
  root.appendChild(content);
  return root;
}

function renderWithDepth(component, ctx, depth) {
  if (!isRecord(component)) return null;
  const type = resolveType(component.type);
  if (!type) return ctx.debug ? debugWarning(ctx, component.type) : null;
  const props = isRecord(component.props) ? component.props : {};
  return RENDERERS[type](ctx, props, component, depth);
}

function makeContext(options, doc, components) {
  const lookup = new Map();
  for (const component of Array.isArray(components) ? components : []) {
    if (isRecord(component) && typeof component.id === 'string')
      lookup.set(component.id, component);
  }
  return {
    doc,
    win: options.window ?? (typeof window !== 'undefined' ? window : undefined),
    onAction: options.onAction,
    debug: options.debug === true,
    locale:
      typeof options.locale === 'string' && options.locale ? options.locale : KB_UI_DEFAULT_LOCALE,
    t: createTranslator(options),
    lookup: options.lookup instanceof Map ? options.lookup : lookup,
    visiting: new Set(),
    // UI-01c: disposers (camera streams, object URLs) run on the next render / disposeA2UI.
    cleanups: [],
  };
}

function resolveDocument(options, container) {
  if (options && options.document) return options.document;
  if (container && container.ownerDocument) return container.ownerDocument;
  if (typeof document !== 'undefined') return document;
  throw new Error('kyberion-ui: no document available');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * @typedef {{ id: string, payload?: Record<string, unknown> }} KbAction
 * @typedef {{ id: string, type: string, props?: Record<string, unknown>, children?: string[] }} A2UIComponent
 * @typedef {{
 *   onAction?: (action: KbAction, component: A2UIComponent) => void,
 *   debug?: boolean,
 *   document?: Document,
 *   window?: Window,
 *   lookup?: Map<string, A2UIComponent>,
 *   locale?: string,
 *   messages?: Record<string, string>,
 *   t?: (key: string, params?: Record<string, unknown>) => string,
 * }} RenderOptions
 */

/**
 * Render one component (and, through `options.lookup`, its children) to a
 * DOM element. Returns null for unknown types (a warning callout when
 * `debug: true`).
 * @param {A2UIComponent} component
 * @param {RenderOptions} [options]
 * @returns {Element | null}
 */
export function renderComponent(component, options = {}) {
  const ctx = makeContext(options, resolveDocument(options, null), []);
  return renderWithDepth(component, ctx, 0);
}

/**
 * Replace `container`'s content with the rendered A2UI component list. The
 * list is flat (children reference ids). With `rootId`, only that subtree is
 * rendered; otherwise every component no other component references, in
 * list order.
 * @param {Element} container
 * @param {A2UIComponent[]} components
 * @param {RenderOptions & { rootId?: string }} [options]
 * @returns {Element}
 */
export function renderA2UI(container, components, options = {}) {
  const ctx = makeContext(options, resolveDocument(options, container), components);
  const list = Array.isArray(components) ? components.filter(isRecord) : [];
  let roots;
  if (typeof options.rootId === 'string') {
    roots = [options.rootId];
  } else {
    const referenced = new Set();
    for (const component of list) {
      if (Array.isArray(component.children))
        for (const id of component.children) referenced.add(id);
    }
    roots = list
      .filter((component) => !referenced.has(component.id))
      .map((component) => component.id);
  }
  const fragment = ctx.doc.createDocumentFragment();
  for (const id of roots) {
    const node = renderById(ctx, id, 0);
    if (node) fragment.appendChild(node);
  }
  disposeA2UI(container);
  while (container.firstChild) container.removeChild(container.firstChild);
  container.appendChild(fragment);
  if (ctx.cleanups.length > 0) RENDER_CLEANUPS.set(container, ctx.cleanups);
  return container;
}

const RENDER_CLEANUPS = new WeakMap();

/**
 * UI-01c: release what the last `renderA2UI` into `container` holds (stop
 * camera tracks, revoke object URLs). Runs automatically before a re-render;
 * call it when removing the container. Never throws.
 * @param {Element} container
 */
export function disposeA2UI(container) {
  const cleanups = container ? RENDER_CLEANUPS.get(container) : undefined;
  if (!cleanups) return;
  RENDER_CLEANUPS.delete(container);
  for (const cleanup of cleanups) {
    try {
      cleanup();
    } catch {
      // best effort
    }
  }
}

export const KB_RENDERED_TYPES = Object.freeze(Object.keys(RENDERERS));
