/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface ActuatorExecutionBrief {
  kind: 'actuator-execution-brief';
  request_text: string;
  archetype_id: string;
  confidence?: number;
  summary?: string;
  user_facing_summary?: string;
  normalized_scope?: string[];
  target_actuators: string[];
  deliverables: string[];
  missing_inputs: string[];
  service_binding_refs?: string[];
  assumptions?: string[];
  clarification_questions?: {
    id: string;
    question: string;
    reason: string;
    default_assumption?: string;
    impact?: string;
    [k: string]: unknown;
  }[];
  readiness?: 'fully_automatable' | 'needs_clarification' | 'needs_external_asset' | 'blocked_by_runtime';
  readiness_reason?: string;
  llm_touchpoints?: {
    stage: string;
    purpose: string;
    output_contract: string;
    [k: string]: unknown;
  }[];
  recommended_next_step?: string;
  [k: string]: unknown;
}
