/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Personal or organizational booking preferences for login method selection, payment policy, points-portal routing, and approval gates. Secrets must be referenced, not embedded.
 */
export interface BookingPreferenceProfile {
  kind: 'booking-preference-profile';
  profile_id: string;
  scope?: 'personal_travel' | 'business_travel' | 'restaurant' | 'hotel' | 'default';
  security_boundaries: {
    forbid_inline_secrets: true;
    /**
     * @minItems 1
     */
    approval_required_for: [
      (
        | 'new_site_login'
        | 'points_portal_redirect'
        | 'reservation_hold'
        | 'booking_confirmation'
        | 'payment_execution'
        | 'cancellation'
        | 'profile_mutation'
        | 'credential_use'
      ),
      ...(
        | 'new_site_login'
        | 'points_portal_redirect'
        | 'reservation_hold'
        | 'booking_confirmation'
        | 'payment_execution'
        | 'cancellation'
        | 'profile_mutation'
        | 'credential_use'
      )[],
    ];
  };
  /**
   * @minItems 1
   */
  preferred_booking_sites: [BookingSite, ...BookingSite[]];
  login_methods?: LoginMethod[];
  payment_policy: PaymentPolicy;
  points_portal_policy?: PointsPortalPolicy;
  site_selection_policy?: SiteSelectionPolicy;
  receipt_policy?: {
    required?: boolean;
    default_usage?: 'personal' | 'business' | 'mixed';
    recipient_ref?: string;
  };
}
export interface BookingSite {
  site: string;
  priority: number;
  categories?: (
    | 'hotel'
    | 'restaurant'
    | 'flight'
    | 'rail'
    | 'activity'
    | 'package'
    | 'shopping'
    | 'medical'
    | 'subscription'
    | 'home_service'
    | 'family'
    | 'gifts'
  )[];
  reason?: string;
  prefer_official_when_equal?: boolean;
}
export interface LoginMethod {
  site: string;
  preferred_method:
    | 'email'
    | 'google'
    | 'apple'
    | 'line'
    | 'rakuten_id'
    | 'hotel_member_id'
    | 'restaurant_account'
    | 'manual'
    | 'none';
  credential_ref?: string;
  approval_required?: boolean;
  notes?: string;
}
export interface PaymentPolicy {
  prefer: (
    | 'onsite_payment'
    | 'free_cancellation'
    | 'points_earning'
    | 'prepaid_discount'
    | 'hotel_member_benefits'
    | 'airline_miles'
    | 'receipt_support'
  )[];
  allow_prepaid: boolean;
  payment_method_refs?: string[];
  /**
   * @minItems 1
   */
  require_confirmation_if: [
    (
      | 'nonrefundable'
      | 'total_amount_over_budget'
      | 'new_site_login'
      | 'payment_execution'
      | 'card_change'
      | 'points_terms_unclear'
      | 'no_free_cancellation'
    ),
    ...(
      | 'nonrefundable'
      | 'total_amount_over_budget'
      | 'new_site_login'
      | 'payment_execution'
      | 'card_change'
      | 'points_terms_unclear'
      | 'no_free_cancellation'
    )[],
  ];
}
export interface PointsPortalPolicy {
  enabled: boolean;
  preferred_portals: {
    portal: string;
    priority: number;
    login_method_ref?: string;
  }[];
  routing_rules: {
    merchant: string;
    use_points_portal: boolean;
    min_expected_reward?: string;
    clickout_usecase_ref?: string;
    preferred_execution_mode?: 'simulation' | 'assisted_booking';
    reason?: string;
  }[];
  require_confirmation_if: (
    | 'reward_rate_unknown'
    | 'tracking_cookie_blocked'
    | 'merchant_not_listed'
    | 'terms_changed'
    | 'nonrefundable_booking'
    | 'payment_execution'
    | 'coupon_conflict'
    | 'app_transition_required'
  )[];
  evidence_required: (
    | 'portal_name'
    | 'merchant_page'
    | 'reward_rate'
    | 'terms_snapshot'
    | 'timestamp'
    | 'final_booking_site'
    | 'clickout_confirmation'
    | 'tracking_warning'
  )[];
  fallback_rule: 'direct_booking' | 'manual_review' | 'skip_candidate';
}
export interface SiteSelectionPolicy {
  decision_mode: 'auto_with_preflight' | 'ask_when_uncertain' | 'always_confirm_site_group';
  /**
   * @minItems 1
   */
  compare_dimensions: [
    (
      | 'price'
      | 'points'
      | 'coupon'
      | 'login_friction'
      | 'cancellation'
      | 'receipt_support'
      | 'speed'
      | 'familiarity'
      | 'privacy'
    ),
    ...(
      | 'price'
      | 'points'
      | 'coupon'
      | 'login_friction'
      | 'cancellation'
      | 'receipt_support'
      | 'speed'
      | 'familiarity'
      | 'privacy'
    )[],
  ];
  /**
   * @minItems 1
   */
  ask_user_when: [
    (
      | 'sale_possible'
      | 'price_gap_unclear'
      | 'points_advantage_unclear'
      | 'multiple_top_candidates'
      | 'login_friction_tradeoff'
      | 'new_service_category'
      | 'user_requested_precheck'
    ),
    ...(
      | 'sale_possible'
      | 'price_gap_unclear'
      | 'points_advantage_unclear'
      | 'multiple_top_candidates'
      | 'login_friction_tradeoff'
      | 'new_service_category'
      | 'user_requested_precheck'
    )[],
  ];
  max_questions_per_turn?: number;
  favorite_site_groups?: {
    label: string;
    categories: (
      | 'hotel'
      | 'restaurant'
      | 'flight'
      | 'rail'
      | 'activity'
      | 'package'
      | 'shopping'
      | 'medical'
      | 'subscription'
      | 'home_service'
      | 'family'
      | 'gifts'
    )[];
    /**
     * @minItems 1
     */
    preferred_sites: [string, ...string[]];
    backup_sites?: string[];
    notes?: string;
  }[];
  preflight_question_sets?: {
    label: string;
    categories: (
      | 'hotel'
      | 'restaurant'
      | 'flight'
      | 'rail'
      | 'activity'
      | 'package'
      | 'shopping'
      | 'medical'
      | 'subscription'
      | 'home_service'
      | 'family'
      | 'gifts'
    )[];
    /**
     * @minItems 1
     * @maxItems 3
     */
    questions: [string] | [string, string] | [string, string, string];
    notes?: string;
  }[];
  sale_signal_policy?: {
    check_sales_before_decision: boolean;
    recheck_if_material: boolean;
    material_threshold?: string;
    preferred_sale_sources?: string[];
  };
}
