/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run generate:types` to regenerate this file.
 */

export interface BridgeRequest {
  intent: string;
  context?: {
    [k: string]: unknown;
  };
  params?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
