/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Integrated visual protocol using intent-driven routing and engine-based rendering.
 */
export interface KyberionDiagramADFProtocolV11 {
  protocol: 'gemini-diagram-v1';
  intent:
    | 'system_architecture'
    | 'project_roadmap'
    | 'api_sequence'
    | 'strategy_map'
    | 'logic_structure'
    | 'db_schema'
    | 'state_flow'
    | 'ui_wireframe';
  engine?: 'mermaid' | 'salt' | 'd2' | 'html';
  /**
   * Specific diagram type for the mermaid engine.
   */
  diagram_type?: 'flowchart' | 'gantt' | 'sequence' | 'er' | 'state' | 'mindmap' | 'block';
  title?: string;
  theme?: 'base' | 'dark' | 'forest';
  elements: {
    nodes?: unknown[];
    edges?: unknown[];
    /**
     * Raw DSL code for the selected engine.
     */
    diagram?: string;
    /**
     * Local path for html engine.
     */
    html_path?: string;
    [k: string]: unknown;
  };
  overrides?: {
    width?: number;
    height?: number;
    theme_variables?: {
      [k: string]: unknown;
    };
    custom_style?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
