/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Long-running generation job contract for image, video, music, and workflow executions.
 */
export interface GenerationJob {
  kind: 'generation-job';
  job_id: string;
  action: 'generate_image' | 'generate_video' | 'generate_music' | 'run_workflow';
  status: 'submitted' | 'running' | 'retrying' | 'succeeded' | 'failed' | 'timed_out' | 'canceled';
  provider?: {
    engine?: string;
    provider_job_id?: string;
    prompt_id?: string;
    [k: string]: unknown;
  };
  request: {
    target_path?: string;
    workflow_path?: string;
    music_adf?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  result?: {
    artifact?: {
      [k: string]: unknown;
    };
    artifacts?: {
      [k: string]: unknown;
    }[];
    copied_to?: string;
    compiled_music_adf?: {
      [k: string]: unknown;
    };
    error?: string;
    retry_classification?: string;
    backend_id?: string;
    backend_kind?: string;
    backend_provider?: string;
    modality?: 'image' | 'video' | 'music' | 'workflow';
    [k: string]: unknown;
  };
  retry_policy?: {
    max_attempts?: number;
    backoff_seconds?: number;
    [k: string]: unknown;
  };
  attempts?: number;
  modality?: 'image' | 'video' | 'music' | 'workflow';
  created_at: string;
  updated_at?: string;
  completed_at?: string;
  next_retry_at?: string;
  [k: string]: unknown;
}
