/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Schedule contract for recurring image, video, music, or workflow generation jobs.
 */
export interface GenerationSchedule {
  kind: 'generation-schedule';
  schedule_id: string;
  enabled: boolean;
  trigger: {
    type: 'cron' | 'interval' | 'event';
    cron?: string;
    interval_ms?: number;
    event_name?: string;
    timezone?: string;
    [k: string]: unknown;
  };
  job_template: {
    action: 'generate_image' | 'generate_video' | 'generate_music' | 'run_workflow';
    params: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  execution_policy: {
    concurrency: 'allow' | 'skip_if_running' | 'replace_running';
    retry_policy?: {
      max_attempts?: number;
      backoff_seconds?: number;
      [k: string]: unknown;
    };
    depends_on?: string[];
    [k: string]: unknown;
  };
  delivery_policy?: {
    artifact_dir?: string;
    latest_alias_path?: string;
    [k: string]: unknown;
  };
  last_job_id?: string;
  last_job_status?: string;
  last_submitted_at?: string;
  last_completed_at?: string;
  created_at: string;
  updated_at?: string;
  [k: string]: unknown;
}
