/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Reusable preferences for meeting roles, brief questions, facilitation policy, and tracking policy.
 */
export interface MeetingOperationsProfile {
  kind: 'meeting-operations-profile';
  profile_id: string;
  /**
   * @minItems 1
   */
  brief_question_sets: [
    {
      label: string;
      meeting_purposes?: (
        | 'planning'
        | 'status_update'
        | 'decision'
        | 'facilitation'
        | 'workshop'
        | 'incident'
        | 'one_on_one'
        | 'review'
        | 'default'
      )[];
      /**
       * @minItems 1
       */
      questions: [string, ...string[]];
      notes?: string;
    },
    ...{
      label: string;
      meeting_purposes?: (
        | 'planning'
        | 'status_update'
        | 'decision'
        | 'facilitation'
        | 'workshop'
        | 'incident'
        | 'one_on_one'
        | 'review'
        | 'default'
      )[];
      /**
       * @minItems 1
       */
      questions: [string, ...string[]];
      notes?: string;
    }[],
  ];
  /**
   * @minItems 1
   */
  role_sets: [
    {
      label: string;
      meeting_purposes?: (
        | 'planning'
        | 'status_update'
        | 'decision'
        | 'facilitation'
        | 'workshop'
        | 'incident'
        | 'one_on_one'
        | 'review'
        | 'default'
      )[];
      primary_role:
        | 'planner'
        | 'facilitator'
        | 'scribe'
        | 'executor'
        | 'decision_maker'
        | 'tracker';
      support_roles?: (
        | 'planner'
        | 'facilitator'
        | 'scribe'
        | 'executor'
        | 'decision_maker'
        | 'tracker'
      )[];
      notes?: string;
    },
    ...{
      label: string;
      meeting_purposes?: (
        | 'planning'
        | 'status_update'
        | 'decision'
        | 'facilitation'
        | 'workshop'
        | 'incident'
        | 'one_on_one'
        | 'review'
        | 'default'
      )[];
      primary_role:
        | 'planner'
        | 'facilitator'
        | 'scribe'
        | 'executor'
        | 'decision_maker'
        | 'tracker';
      support_roles?: (
        | 'planner'
        | 'facilitator'
        | 'scribe'
        | 'executor'
        | 'decision_maker'
        | 'tracker'
      )[];
      notes?: string;
    }[],
  ];
  facilitation_policy: {
    ask_before_join: boolean;
    ask_before_speaking: boolean;
    ask_before_shared_decision: boolean;
    prefer_written_summary?: boolean;
    capture_transcript?: boolean;
  };
  tracking_policy: {
    default_follow_up_channel: 'slack' | 'email' | 'teams' | 'task_session';
    default_tracking_cadence: 'immediate' | 'daily' | 'weekly' | 'ad_hoc';
    require_owner?: boolean;
    require_deadline?: boolean;
    track_until_closed?: boolean;
  };
  exit_policy: {
    stop_after_agenda_complete: boolean;
    stop_on_missing_authority: boolean;
    capture_final_summary?: boolean;
    capture_action_items?: boolean;
  };
}
