/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Brief contract for a meeting operation, including role, goals, authority, and tracking expectations.
 */
export interface MeetingOperationsBrief {
  kind: 'meeting-operations-brief';
  version: string;
  intent: string;
  meeting_title: string;
  meeting_url: string;
  platform: 'teams' | 'zoom' | 'meet' | 'auto';
  purpose:
    | 'planning'
    | 'status_update'
    | 'decision'
    | 'facilitation'
    | 'workshop'
    | 'incident'
    | 'one_on_one'
    | 'review'
    | 'default';
  primary_role: 'planner' | 'facilitator' | 'scribe' | 'executor' | 'decision_maker' | 'tracker';
  support_roles?: (
    | 'planner'
    | 'facilitator'
    | 'scribe'
    | 'executor'
    | 'decision_maker'
    | 'tracker'
  )[];
  agenda?: string[];
  participants?: {
    name: string;
    person_slug?: string;
    channel_handle?: string;
    role_hint?: 'planner' | 'facilitator' | 'scribe' | 'executor' | 'decision_maker' | 'tracker';
  }[];
  /**
   * @minItems 1
   */
  desired_outcomes: [string, ...string[]];
  authority_scope?: {
    may_facilitate?: boolean;
    may_speak?: boolean;
    may_make_shared_decisions?: boolean;
    may_assign_action_items?: boolean;
    may_track_action_items?: boolean;
  };
  environment?: {
    transport_mode: 'transcribe_first' | 'realtime_voice';
    /**
     * @minItems 1
     */
    items: [
      {
        kind:
          | 'browser'
          | 'audio'
          | 'ffmpeg'
          | 'stt'
          | 'tts'
          | 'voice_profile'
          | 'voice_consent'
          | 'camera'
          | 'screen_share';
        state: 'required' | 'recommended' | 'optional' | 'blocked_by_authority' | 'not_needed';
        reason: string;
        setup_hint?: string;
      },
      ...{
        kind:
          | 'browser'
          | 'audio'
          | 'ffmpeg'
          | 'stt'
          | 'tts'
          | 'voice_profile'
          | 'voice_consent'
          | 'camera'
          | 'screen_share';
        state: 'required' | 'recommended' | 'optional' | 'blocked_by_authority' | 'not_needed';
        reason: string;
        setup_hint?: string;
      }[],
    ];
    questions: string[];
  };
  own_tasks?: string[];
  tracking_expectations?: string[];
  /**
   * @minItems 1
   */
  exit_conditions: [string, ...string[]];
  follow_up_channel?: 'slack' | 'email' | 'teams' | 'task_session';
  notes?: string;
}
