/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface MissionContract {
  mission_id: string;
  /**
   * The security tier of the mission. 'personal' missions are stored in knowledge/personal/missions, 'confidential' in active/missions/confidential, and 'public' in active/missions/public.
   */
  tier: 'personal' | 'confidential' | 'public';
  role?: string;
  skill: string;
  action: string;
  static_params?: {
    [k: string]: unknown;
  };
  safety_gate?: {
    risk_level?: number;
    require_sudo?: boolean;
    approved_by_sovereign?: boolean;
    [k: string]: unknown;
  };
  /**
   * Declarative knowledge scope this mission draws on. Resolved at runtime by tag/domain query (knowledge-index.ts), not by literal path, so it survives knowledge/ directory reorganizations.
   */
  knowledge_injections?: {
    /**
     * Knowledge tier this entry draws from; drives mission tier auto-elevation directly (no path sniffing).
     */
    tier: 'personal' | 'confidential' | 'public';
    /**
     * Required scoping when tier is 'confidential': matches knowledge/confidential/{project}/.
     */
    project?: string;
    /**
     * Knowledge domains to search, e.g. 'design-patterns', 'procedures/browser'.
     */
    domains?: string[];
    /**
     * Frontmatter/hint tags to match, e.g. 'browser-automation', 'pptx'.
     */
    tags?: string[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
