/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface MissionContract {
  mission_id: string;
  /**
   * The security tier of the mission. 'personal' missions are stored in knowledge/personal/missions, 'confidential' in active/missions/confidential, and 'public' in active/missions/public.
   */
  tier: 'personal' | 'confidential' | 'public';
  role?: string;
  skill: string;
  action: string;
  static_params?: {
    [k: string]: unknown;
  };
  safety_gate?: {
    risk_level?: number;
    require_sudo?: boolean;
    approved_by_sovereign?: boolean;
    [k: string]: unknown;
  };
  knowledge_injections?: string[];
  [k: string]: unknown;
}
