/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Reusable preferences for narrated video briefs, visual theme selection, and publish gating.
 */
export interface NarratedVideoPreferenceProfile {
  kind: 'narrated-video-preference-profile';
  profile_id: string;
  /**
   * @minItems 1
   */
  brief_question_sets: [
    {
      label: string;
      video_purposes?: (
        | 'tutorial'
        | 'announcement'
        | 'product_demo'
        | 'marketing'
        | 'onboarding'
        | 'default'
      )[];
      /**
       * @minItems 1
       */
      questions: [string, ...string[]];
      notes?: string;
    },
    ...{
      label: string;
      video_purposes?: (
        | 'tutorial'
        | 'announcement'
        | 'product_demo'
        | 'marketing'
        | 'onboarding'
        | 'default'
      )[];
      /**
       * @minItems 1
       */
      questions: [string, ...string[]];
      notes?: string;
    }[],
  ];
  /**
   * @minItems 1
   */
  theme_sets: [
    {
      label: string;
      video_purposes?: (
        | 'tutorial'
        | 'announcement'
        | 'product_demo'
        | 'marketing'
        | 'onboarding'
        | 'default'
      )[];
      theme_hint: string;
      visual_traits?: string[];
      notes?: string;
    },
    ...{
      label: string;
      video_purposes?: (
        | 'tutorial'
        | 'announcement'
        | 'product_demo'
        | 'marketing'
        | 'onboarding'
        | 'default'
      )[];
      theme_hint: string;
      visual_traits?: string[];
      notes?: string;
    }[],
  ];
  publish_policy: {
    default_target: 'youtube' | 'draft_only';
    default_visibility: 'private' | 'unlisted' | 'public';
    require_human_approval_before_publish: boolean;
    allow_auto_upload?: boolean;
    require_thumbnail?: boolean;
    require_description?: boolean;
    require_tags?: boolean;
    require_caption?: boolean;
  };
  asset_policy?: {
    prefer_first_party_assets?: boolean;
    require_licensed_assets?: boolean;
    allow_generated_thumbnails?: boolean;
  };
}
