/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Publish-side contract for narrated videos prior to YouTube upload or public release.
 */
export interface NarratedVideoPublishPlan {
  kind: 'narrated-video-publish-plan';
  version: string;
  target: 'youtube' | 'draft_only';
  title: string;
  description?: string;
  visibility: 'private' | 'unlisted' | 'public';
  approval_boundary: 'before_upload' | 'before_public_release';
  video_artifact_ref: string;
  thumbnail_ref?: string;
  caption_ref?: string;
  tags?: string[];
  scheduled_publish_at?: string;
  notes?: string;
}
