/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Staged package for YouTube upload preparation prior to public release.
 */
export interface NarratedVideoUploadPackage {
  kind: 'narrated-video-upload-package';
  version: string;
  publish_plan_ref: string;
  target_url: string;
  video_artifact_ref: string;
  thumbnail_ref?: string;
  caption_ref?: string;
  title?: string;
  description?: string;
  visibility: 'private' | 'unlisted' | 'public';
  approval_boundary: 'before_upload' | 'before_public_release';
  /**
   * @minItems 1
   */
  checklist: [string, ...string[]];
  tags?: string[];
  scheduled_publish_at?: string;
  notes?: string;
}
