/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface OperatorInteractionPacket {
  kind: 'operator-interaction-packet';
  interaction_type: 'clarification' | 'execution-preview' | 'status-summary' | 'delivery-summary';
  headline: string;
  summary: string;
  readiness?: string;
  confidence?: number;
  missing_inputs?: string[];
  omitted_question_count?: number;
  questions?: {
    id: string;
    question: string;
    reason: string;
    default_assumption?: string;
    impact?: string;
    [k: string]: unknown;
  }[];
  next_actions?: {
    id: string;
    action: string;
    next_action_type?: 'execute_now' | 'inspect' | 'clarify' | 'start_mission' | 'resume_mission';
    reason?: string;
    priority?: 'now' | 'next' | 'later';
    suggested_command?: string;
    suggested_pipeline_path?: string;
    suggested_followup_request?: string;
    [k: string]: unknown;
  }[];
  suggested_response_style?: 'clarify-first' | 'preview-and-confirm' | 'status-summary';
  refresh_command?: string;
  refresh_packet_path?: string;
  llm_touchpoints?: {
    stage: string;
    purpose: string;
    output_contract: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
