/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface ProposalStorylineADF {
  kind: 'proposal-storyline-adf';
  title: string;
  client?: string;
  core_message?: string;
  document_profile?: string;
  design_system_id?: string;
  branding?: {
    [k: string]: unknown;
  };
  layout_template_id?: string;
  narrative_pattern_id?: string;
  recommended_theme?: string;
  recommended_layout_template_id?: string;
  toc?: {
    [k: string]: unknown;
  }[];
  slides: {
    id: string;
    title: string;
    objective: string;
    body?: string[];
    visual?: string;
    media_kind?: string;
    layout_key?: string;
    semantic_type?: string;
    pattern_id?: string;
    slide_pattern?: {
      [k: string]: unknown;
    };
    body_zone?: string;
    design_system_id?: string;
    branding?: {
      [k: string]: unknown;
    };
  }[];
}
