/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `npm run generate:types` to regenerate this file.
 */

/**
 * Standard output contract for Gemini Skills
 */
export interface SkillOutput {
  /**
   * Name of the skill that produced this output
   */
  skill: string;
  /**
   * Execution result status
   */
  status: 'success' | 'error' | 'partial';
  /**
   * The skill's output data (type varies by skill)
   */
  data?: {
    [k: string]: unknown;
  };
  metadata?: {
    duration_ms?: number;
    token_usage?: number;
    knowledge_tier_used?: 'personal' | 'confidential' | 'public';
    timestamp?: string;
    [k: string]: unknown;
  };
  error?: {
    code?: string;
    message?: string;
    details?: unknown;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
