/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run \`npm run generate:types\` to regenerate this file.
 */

/**
 * Standard input contract for Kyberion
 */
export interface SkillInput {
  /**
   * Name of the skill being invoked
   */
  skill: string;
  /**
   * The action to perform
   */
  action: string;
  /**
   * Skill-specific parameters
   */
  params?: {
    [k: string]: unknown;
  };
  /**
   * Execution context (knowledge tier, caller info)
   */
  context?: {
    knowledge_tier?: 'personal' | 'confidential' | 'public';
    /**
     * Name of the calling skill or user
     */
    caller?: string;
    session_id?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
