/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Reusable slide layout pattern catalog inspired by SLIDE.md. Patterns define content-area structure and constraints separately from theme tokens.
 */
export interface SlidePatternPack {
  kind: 'slide-pattern-pack';
  version: string;
  pack_id: string;
  source: {
    name: string;
    repository?: string;
    revision?: string;
    notes?: string;
  };
  /**
   * @minItems 1
   */
  patterns: [
    {
      pattern_id: string;
      category:
        | 'cover'
        | 'agenda'
        | 'section'
        | 'message'
        | 'comparison'
        | 'flow'
        | 'diagram'
        | 'card_grid'
        | 'chart_data'
        | 'table'
        | 'kpi_summary'
        | 'closing'
        | 'action_items';
      summary: string;
      /**
       * @minItems 1
       */
      suitable_scenes: [string, ...string[]];
      /**
       * @minItems 1
       */
      slide_types: [string, ...string[]];
      semantic_types: string[];
      deck_purposes?: ('proposal' | 'internal_share' | 'briefing' | 'marketing' | 'training' | 'comparison')[];
      structure: {
        layout: string;
        [k: string]: unknown;
      };
      /**
       * @minItems 1
       */
      element_slots: [
        {
          slot_id: string;
          role: string;
          required: boolean;
          min_items?: number;
          max_items?: number;
          max_chars_per_item?: number;
          notes?: string;
        },
        ...{
          slot_id: string;
          role: string;
          required: boolean;
          min_items?: number;
          max_items?: number;
          max_chars_per_item?: number;
          notes?: string;
        }[]
      ];
      constraints?: {
        kind: 'paired_item_counts_match' | 'requires_visual' | 'single_message';
        /**
         * @minItems 1
         */
        slots?: [string, ...string[]];
        message?: string;
      }[];
      renderer_hints: {
        layout_key: string;
        body_zone:
          | 'single-column'
          | 'two-column-callout'
          | 'two-column-risk'
          | 'timeline'
          | 'architecture-panel'
          | 'decision-cta';
        media_kind?: string;
        visual_treatment?: string;
        fallback_pattern_id?: string;
      };
    },
    ...{
      pattern_id: string;
      category:
        | 'cover'
        | 'agenda'
        | 'section'
        | 'message'
        | 'comparison'
        | 'flow'
        | 'diagram'
        | 'card_grid'
        | 'chart_data'
        | 'table'
        | 'kpi_summary'
        | 'closing'
        | 'action_items';
      summary: string;
      /**
       * @minItems 1
       */
      suitable_scenes: [string, ...string[]];
      /**
       * @minItems 1
       */
      slide_types: [string, ...string[]];
      semantic_types: string[];
      deck_purposes?: ('proposal' | 'internal_share' | 'briefing' | 'marketing' | 'training' | 'comparison')[];
      structure: {
        layout: string;
        [k: string]: unknown;
      };
      /**
       * @minItems 1
       */
      element_slots: [
        {
          slot_id: string;
          role: string;
          required: boolean;
          min_items?: number;
          max_items?: number;
          max_chars_per_item?: number;
          notes?: string;
        },
        ...{
          slot_id: string;
          role: string;
          required: boolean;
          min_items?: number;
          max_items?: number;
          max_chars_per_item?: number;
          notes?: string;
        }[]
      ];
      constraints?: {
        kind: 'paired_item_counts_match' | 'requires_visual' | 'single_message';
        /**
         * @minItems 1
         */
        slots?: [string, ...string[]];
        message?: string;
      }[];
      renderer_hints: {
        layout_key: string;
        body_zone:
          | 'single-column'
          | 'two-column-callout'
          | 'two-column-risk'
          | 'timeline'
          | 'architecture-panel'
          | 'decision-cta';
        media_kind?: string;
        visual_treatment?: string;
        fallback_pattern_id?: string;
      };
    }[]
  ];
}
