/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

/**
 * Canonical direct-action, pipeline, and wisdom-owned reconcile contract.
 */
export type WisdomActuatorRequest = {
  action:
    | 'knowledge_search'
    | 'history_search'
    | 'knowledge_inject'
    | 'knowledge_export'
    | 'knowledge_import'
    | 'pipeline'
    | 'reconcile';
  params?: {
    [k: string]: unknown;
  };
  /**
   * @minItems 1
   */
  steps?: [PipelineStep, ...PipelineStep[]];
  context?: {
    [k: string]: unknown;
  };
  options?: PipelineOptions;
  strategy_path?: string;
} & (
  | {
      action: 'knowledge_search';
      params: KnowledgeSearchParams;
      [k: string]: unknown;
    }
  | {
      action: 'history_search';
      params: HistorySearchParams;
      [k: string]: unknown;
    }
  | {
      action: 'knowledge_inject';
      params: KnowledgeInjectParams;
      [k: string]: unknown;
    }
  | {
      action: 'knowledge_export';
      params: KnowledgeExportParams;
      [k: string]: unknown;
    }
  | {
      action: 'knowledge_import';
      params: KnowledgeImportParams;
      [k: string]: unknown;
    }
  | {
      action: 'pipeline';
      [k: string]: unknown;
    }
  | {
      action: 'reconcile';
      [k: string]: unknown;
    }
);
export type PipelineStep =
  | {
      type: 'capture';
      op:
        | 'glob_files'
        | 'history_search'
        | 'knowledge_search'
        | 'query'
        | 'read_file'
        | 'read_json'
        | 'shell';
      params?: PipelineParams;
    }
  | {
      type: 'transform';
      op: 'array_count' | 'json_query' | 'regex_extract' | 'regex_replace' | 'yaml_update';
      params?: PipelineParams;
    }
  | {
      type: 'apply';
      op:
        | 'a2a_fanout'
        | 'perspective_fanout'
        | 'a2a_roleplay'
        | 'adjust_proposal'
        | 'audit_speaker_fairness'
        | 'capture_intuition'
        | 'compute_readiness_matrix'
        | 'conduct_1on_1'
        | 'curate_background_review'
        | 'cross_critique'
        | 'typed_cross_critique'
        | 'decompose_into_tasks'
        | 'deploy_release'
        | 'distill'
        | 'derive_test_inventory'
        | 'emit_dissent_log'
        | 'escalate_for_review'
        | 'evaluate_architecture_ready'
        | 'evaluate_customer_signoff'
        | 'evaluate_decision_rights_approval'
        | 'evaluate_ensemble_convergence'
        | 'evaluate_qa_ready'
        | 'evaluate_requirements_completeness'
        | 'evaluate_simulation_quality'
        | 'evaluate_task_plan_ready'
        | 'execute_self_action_items'
        | 'execute_task_plan'
        | 'extract_action_items'
        | 'extract_design_spec'
        | 'extract_dissent_signals'
        | 'extract_requirements'
        | 'extract_test_plan'
        | 'find_slides_by_owner'
        | 'fork_branches'
        | 'generate_facilitation_script'
        | 'generate_reminder_message'
        | 'inject_prior_knowledge'
        | 'knowledge_export'
        | 'knowledge_import'
        | 'knowledge_inject'
        | 'log'
        | 'peer_advice'
        | 'pptx_diff'
        | 'react_loop'
        | 'reasoning'
        | 'recommend'
        | 'register_presentation_preference_profile'
        | 'render_hypothesis_report'
        | 'resolve_hypothesis_conflict'
        | 'simulate_all'
        | 'simulate_all_ensemble'
        | 'stakeholder_grid_sort'
        | 'synthesize_counterparty_persona'
        | 'task_plan_to_next_tasks'
        | 'tool_use'
        | 'track_pending_action_items'
        | 'transcribe_audio'
        | 'uncertainty_gate'
        | 'write_artifact'
        | 'write_file';
      params?: PipelineParams;
    }
  | {
      type: 'control';
      op: 'if' | 'while';
      params?: PipelineParams;
    };
export type KnowledgeTier = 'personal' | 'confidential' | 'public';
export type ExportAs = string;
export type KnowledgeImportParams = KnowledgeImportParams1 & {
  package_path?: string;
  source_path?: string;
  tier?: KnowledgeTier;
  export_as?: ExportAs;
};
export type KnowledgeImportParams1 = {
  [k: string]: unknown;
};

/**
 * Legacy step parameter envelope; individual handlers perform operation-specific validation.
 */
export interface PipelineParams {
  [k: string]: unknown;
}
export interface PipelineOptions {
  max_steps?: number;
  timeout_ms?: number;
  compatibility_mode?: boolean;
}
export interface KnowledgeSearchParams {
  query: string;
  tier?: KnowledgeTier;
  limit?: number;
  export_as?: ExportAs;
}
export interface HistorySearchParams {
  query?: string;
  session_id?: string;
  mode?: string;
  max_results?: number;
  include_scheduled?: boolean;
  export_as?: ExportAs;
}
export interface KnowledgeInjectParams {
  knowledge_path: string;
  mission_id: string;
  export_as?: ExportAs;
}
export interface KnowledgeExportParams {
  path: string;
  output_path?: string;
  domain?: string;
  visibility?: KnowledgeTier;
  export_as?: ExportAs;
}
