import { withCatalogInputContract } from '@agent/core';

// Self-described operation catalog for media-actuator.
// These entries mirror the operation switches in media-action-{capture,transform,apply}.

type OpSpecKind = 'capture' | 'transform' | 'apply' | 'control';

type InputSchema = Record<string, unknown>;
const MEDIA_MIGRATION_SCHEMA: InputSchema = {
  type: 'object',
  properties: {
    after: {},
    after_from: { type: 'string' },
    allow_external_egress: { type: 'boolean' },
    allow_layout_overflow: { type: 'boolean' },
    angle: { type: 'number' },
    artifact_kind: { type: 'string' },
    artifact_path: { type: 'string' },
    aesthetic: { type: 'string' },
    backend: {},
    background_color: { type: 'string' },
    before: {},
    before_from: { type: 'string' },
    brief: {},
    brief_from: { type: 'string' },
    brand_name: { type: 'string' },
    bind: {},
    content: {},
    content_data: {},
    data: {},
    delete: { type: 'array' },
    design_defaults: {},
    design_from: { type: 'string' },
    design_system_id: { type: 'string' },
    dpi: { type: 'number' },
    export_as: { type: 'string' },
    export_master_as: { type: 'string' },
    from: { type: 'string' },
    hints: {},
    height: { type: 'number' },
    html_paths: { type: 'array' },
    html: { type: 'string' },
    icon_map_path: { type: 'string' },
    icon_root: { type: 'string' },
    input_path: { type: 'string' },
    inputs: { type: 'array' },
    keep_indices: { type: 'array' },
    keep_indices_from: { type: 'string' },
    key: { type: 'string' },
    label: { type: 'string' },
    layout: { type: 'string' },
    layout_from: { type: 'string' },
    lock_media_brief: { type: 'boolean' },
    message: { type: 'string' },
    mission_id: { type: 'string' },
    logo_url: { type: 'string' },
    match_mode: { type: 'string' },
    matchers: { type: 'array' },
    max_pages: { type: 'number' },
    name: { type: 'string' },
    ocr: { type: 'boolean' },
    options: {},
    order: { type: 'array' },
    output_format: { type: 'string' },
    output_path: { type: 'string' },
    owner_labels: { type: 'array' },
    owner_labels_from: { type: 'string' },
    out: {},
    out_dir: { type: 'string' },
    pad: { type: 'number' },
    pages: { type: 'array' },
    paragraph_replacements: {},
    path: { type: 'string' },
    pattern_path: { type: 'string' },
    password: { type: 'string' },
    prefix: { type: 'string' },
    profile: {},
    profile_id: { type: 'string' },
    profile_path: { type: 'string' },
    range: { type: 'string' },
    registry_path: { type: 'string' },
    replacements: {},
    replacements_from: { type: 'string' },
    render_target: { type: 'string' },
    run_shape: {},
    set: {},
    sheet: { type: 'string' },
    skip_zero: { type: 'boolean' },
    sketch: { type: 'string' },
    slides: { type: 'array' },
    source: { type: 'string' },
    story: {},
    stamp: { type: 'string' },
    target_path: { type: 'string' },
    tenant_slug: { type: 'string' },
    text: { type: 'string' },
    theme: {},
    theme_from: { type: 'string' },
    theme_id: { type: 'string' },
    value: {},
    tier: { type: 'string' },
    timeout_ms: { type: 'number' },
    title: { type: 'string' },
    url: { type: 'string' },
    user_password: { type: 'string' },
    owner_password: { type: 'string' },
    values_only: { type: 'boolean' },
    width: { type: 'number' },
    work_dir: { type: 'string' },
    web_from: { type: 'string' },
    web_theme_from: { type: 'string' },
  },
  additionalProperties: false,
};
const MEDIA_EXTRA_OPS = [
  'document_digest',
  'docx_extract',
  'json_read',
  'pdf_delete_pages',
  'pdf_encrypt',
  'pdf_extract',
  'pdf_extract_range',
  'pdf_merge',
  'pdf_metadata',
  'pdf_remove_password',
  'pdf_reorder',
  'pdf_rotate',
  'pdf_split',
  'pdf_stamp',
  'pptx_extract',
  'pptx_slide_text',
  'xlsx_extract',
  'apply_pattern',
  'apply_theme',
  'brief_to_design_protocol',
  'deck_from_html',
  'document_diagram_asset_from_brief',
  'document_outline_from_brief',
  'document_pdf_from_brief',
  'document_report_design_from_brief',
  'document_spreadsheet_design_from_brief',
  'drawio_from_graph',
  'find_slides_by_owner',
  'layout_template_from_pptx_design',
  'lock_media_brief',
  'merge_content',
  'pdf_to_pptx_design',
  'pdf_to_xlsx_design',
  'pptx_diff',
  'pptx_layout_preflight',
  'proposal_content_from_storyline',
  'proposal_storyline_from_brief',
  'set',
  'theme_from_pptx_design',
  'visual_review',
  'visual_review_delivery_gate',
  'd2_render',
  'document_diagram_render_from_brief',
  'docx_render',
  'drawio_write',
  'generate_document',
  'log',
  'mermaid_render',
  'pdf_render',
  'pptx_filter_slides',
  'pptx_patch',
  'pptx_patch_paragraphs',
  'pptx_render',
  'register_presentation_preference_profile',
  'save_brand_to_confidential',
  'write_file',
  'xlsx_render',
] as const;
const MEDIA_REQUIRED_INPUTS: Record<string, string[]> = {
  document_digest: ['path'],
  docx_extract: ['path'],
  json_read: ['path'],
  pdf_delete_pages: ['path', 'delete'],
  pdf_encrypt: ['path', 'user_password'],
  pdf_extract: ['path'],
  pdf_extract_range: ['path', 'pages'],
  pdf_merge: ['inputs'],
  pdf_metadata: ['path'],
  pdf_remove_password: ['path', 'password'],
  pdf_reorder: ['path', 'order'],
  pdf_rotate: ['path', 'angle'],
  pdf_split: ['path'],
  pdf_stamp: ['path', 'stamp'],
  pptx_extract: ['path'],
  pptx_slide_text: ['path'],
  xlsx_extract: ['path'],
  apply_pattern: ['pattern_path'],
  deck_from_html: ['html'],
  pptx_diff: ['before', 'after'],
  pptx_filter_slides: ['path', 'keep_indices'],
  pptx_patch: ['path', 'replacements'],
  pptx_patch_paragraphs: ['path', 'paragraph_replacements'],
  save_brand_to_confidential: ['brand_name', 'tenant_slug'],
  write_file: ['path', 'content'],
};
const MEDIA_EXTRA_CONTRACTS: Record<string, InputSchema> = Object.fromEntries(
  MEDIA_EXTRA_OPS.map((op) => [
    op,
    MEDIA_REQUIRED_INPUTS[op]
      ? { ...MEDIA_MIGRATION_SCHEMA, required: MEDIA_REQUIRED_INPUTS[op] }
      : MEDIA_MIGRATION_SCHEMA,
  ])
);
const MEDIA_EXTRA_EXAMPLES: Record<string, Array<Record<string, unknown>>> = {
  document_digest: [{ path: 'active/shared/tmp/document.pdf' }],
  docx_extract: [{ path: 'active/shared/tmp/document.docx' }],
  json_read: [{ path: 'active/shared/tmp/data.json' }],
  pdf_delete_pages: [{ path: 'active/shared/tmp/document.pdf', delete: [1] }],
  pdf_encrypt: [{ path: 'active/shared/tmp/document.pdf', user_password: 'secret' }],
  pdf_extract: [{ path: 'active/shared/tmp/document.pdf' }],
  pdf_extract_range: [{ path: 'active/shared/tmp/document.pdf', pages: [1] }],
  pdf_merge: [{ inputs: ['active/shared/tmp/a.pdf', 'active/shared/tmp/b.pdf'] }],
  pdf_metadata: [{ path: 'active/shared/tmp/document.pdf' }],
  pdf_remove_password: [{ path: 'active/shared/tmp/document.pdf', password: 'secret' }],
  pdf_reorder: [{ path: 'active/shared/tmp/document.pdf', order: [2, 1] }],
  pdf_rotate: [{ path: 'active/shared/tmp/document.pdf', angle: 90 }],
  pdf_split: [{ path: 'active/shared/tmp/document.pdf', prefix: 'part' }],
  pdf_stamp: [{ path: 'active/shared/tmp/document.pdf', stamp: 'DRAFT' }],
  pptx_extract: [{ path: 'active/shared/tmp/deck.pptx' }],
  pptx_slide_text: [{ path: 'active/shared/tmp/deck.pptx' }],
  xlsx_extract: [{ path: 'active/shared/tmp/data.xlsx' }],
  apply_pattern: [{ pattern_path: 'active/shared/tmp/pattern.json' }],
  apply_theme: [{ theme: {} }],
  brief_to_design_protocol: [{ from: 'brief' }],
  deck_from_html: [{ html: '<h1>Title</h1>' }],
  document_diagram_asset_from_brief: [{ from: 'brief' }],
  document_outline_from_brief: [{ from: 'brief' }],
  document_pdf_from_brief: [{ from: 'brief' }],
  document_report_design_from_brief: [{ from: 'brief' }],
  document_spreadsheet_design_from_brief: [{ from: 'brief' }],
  drawio_from_graph: [{ from: 'graph' }],
  find_slides_by_owner: [{ from: 'deck', owner_labels: ['operator'] }],
  layout_template_from_pptx_design: [{ from: 'design' }],
  lock_media_brief: [{ from: 'brief' }],
  merge_content: [{ content_data: {} }],
  pdf_to_pptx_design: [{ from: 'pdf' }],
  pdf_to_xlsx_design: [{ from: 'pdf' }],
  pptx_diff: [{ before: 'before.pptx', after: 'after.pptx' }],
  pptx_layout_preflight: [{ from: 'deck' }],
  proposal_content_from_storyline: [{ from: 'storyline' }],
  proposal_storyline_from_brief: [{ from: 'brief' }],
  set: [{ key: 'theme', value: {} }],
  theme_from_pptx_design: [{ from: 'design' }],
  visual_review: [{ artifact_path: 'active/shared/tmp/artifact.png' }],
  visual_review_delivery_gate: [{ from: 'visual_review' }],
  d2_render: [{ path: 'active/shared/tmp/diagram.d2' }],
  document_diagram_render_from_brief: [
    { from: 'brief', output_path: 'active/shared/tmp/diagram.png' },
  ],
  docx_render: [{ path: 'active/shared/tmp/document.docx' }],
  drawio_write: [{ path: 'active/shared/tmp/diagram.drawio' }],
  generate_document: [{ from: 'brief', output_path: 'active/shared/tmp/document.docx' }],
  log: [{ message: 'completed' }],
  mermaid_render: [{ path: 'active/shared/tmp/diagram.mmd' }],
  pdf_render: [{ path: 'active/shared/tmp/document.pdf' }],
  pptx_filter_slides: [{ path: 'active/shared/tmp/deck.pptx', keep_indices: [1] }],
  pptx_patch: [{ path: 'active/shared/tmp/deck.pptx', replacements: {} }],
  pptx_patch_paragraphs: [{ path: 'active/shared/tmp/deck.pptx', paragraph_replacements: {} }],
  pptx_render: [{ path: 'active/shared/tmp/deck.pptx' }],
  register_presentation_preference_profile: [{ profile: {} }],
  save_brand_to_confidential: [{ brand_name: 'default', tenant_slug: 'acme' }],
  write_file: [{ path: 'active/shared/tmp/note.txt', content: 'completed' }],
  xlsx_render: [{ path: 'active/shared/tmp/data.xlsx' }],
};

const CAPTURE_OPS = [
  'document_digest',
  'docx_extract',
  'json_read',
  'pdf_delete_pages',
  'pdf_encrypt',
  'pdf_extract',
  'pdf_extract_range',
  'pdf_merge',
  'pdf_metadata',
  'pdf_remove_password',
  'pdf_reorder',
  'pdf_rotate',
  'pdf_split',
  'pdf_stamp',
  'pptx_extract',
  'pptx_slide_text',
  'xlsx_extract',
] as const;

const TRANSFORM_OPS = [
  'apply_pattern',
  'apply_theme',
  'brief_to_design_protocol',
  'deck_from_html',
  'document_diagram_asset_from_brief',
  'document_outline_from_brief',
  'document_pdf_from_brief',
  'document_report_design_from_brief',
  'document_spreadsheet_design_from_brief',
  'drawio_from_graph',
  'find_slides_by_owner',
  'layout_template_from_pptx_design',
  'lock_media_brief',
  'merge_content',
  'pdf_to_pptx_design',
  'pdf_to_xlsx_design',
  'pptx_diff',
  'pptx_layout_preflight',
  'proposal_content_from_storyline',
  'proposal_storyline_from_brief',
  'set',
  'theme_from_pptx_design',
  'visual_review',
  'visual_review_delivery_gate',
] as const;

const APPLY_OPS = [
  'd2_render',
  'document_diagram_render_from_brief',
  'docx_render',
  'drawio_write',
  'generate_document',
  'log',
  'mermaid_render',
  'pdf_render',
  'pptx_filter_slides',
  'pptx_patch',
  'pptx_patch_paragraphs',
  'pptx_render',
  'register_presentation_preference_profile',
  'save_brand_to_confidential',
  'write_file',
  'xlsx_render',
] as const;

function toSpec(op: string, kind: OpSpecKind) {
  const description = MEDIA_EXTRA_CONTRACTS[op]
    ? {
        op,
        kind,
        input_schema: MEDIA_EXTRA_CONTRACTS[op],
        examples: MEDIA_EXTRA_EXAMPLES[op] || [{}],
      }
    : { op, kind };
  return withCatalogInputContract('media', op, kind, description);
}

export function describeOps() {
  return [
    ...CAPTURE_OPS.map((op) => toSpec(op, 'capture')),
    ...TRANSFORM_OPS.map((op) => toSpec(op, 'transform')),
    ...APPLY_OPS.map((op) => toSpec(op, 'apply')),
  ];
}
