import type { ValidateFunction } from 'ajv';
import { compileSchema, createAjv2020 } from './foundation/ajv.js';
import { pathResolver } from './path-resolver.js';

/**
 * A2UI `kyberion-base` catalog (UI-01, SURFACE_UI_UNIFICATION_PLAN §3).
 *
 * The shared component vocabulary every Kyberion surface renders with the same
 * `.kb-*` class contract (`kyberion-ui.css`, generated by
 * `scripts/generate_design_tokens.ts`). Props are validated against
 * `knowledge/product/schemas/a2ui-catalog-kyberion-base.schema.json`; the TS
 * types below mirror that schema and must stay in lock-step with it
 * (`a2ui-catalog.test.ts` pins both).
 */

export const KYBERION_BASE_CATALOG_ID = 'kyberion-base';

export const KYBERION_BASE_CATALOG_SCHEMA_ID =
  'https://kyberion.ai/schemas/a2ui-catalog-kyberion-base.schema.json';

export const KYBERION_BASE_COMPONENT_TYPES = [
  'ui:app-shell',
  'ui:page-header',
  'ui:nav-rail',
  'ui:tabs',
  'ui:stack',
  'ui:grid',
  'ui:section',
  'ui:next-action',
  'ui:metric',
  'ui:kv',
  'ui:table',
  'ui:list',
  'ui:text',
  'ui:status-pill',
  'ui:badge',
  'ui:callout',
  'ui:empty-state',
  'ui:skeleton',
  'ui:button',
  'ui:disclosure',
  // UI-01c settings & forms (SURFACE_UI_UNIFICATION_PLAN §3.3)
  'ui:settings-group',
  'ui:setting-row',
  'ui:switch',
  'ui:checkbox',
  'ui:select',
  'ui:radio-group',
  'ui:segmented',
  'ui:text-field',
  'ui:textarea',
  'ui:slider',
  'ui:integration-item',
  'ui:save-bar',
  'ui:file-drop',
  'ui:camera-capture',
  'ui:avatar-picker',
  'ui:secret-field',
  // UI-01b charts & visualisation (SURFACE_UI_UNIFICATION_PLAN §3.2)
  'ui:bar-chart',
  'ui:line-chart',
  'ui:donut',
  'ui:sparkline',
  'ui:heatmap',
  'ui:meter',
  'ui:sequence',
  'ui:flow',
  'ui:stat-list',
] as const;

export type KyberionBaseComponentType = (typeof KYBERION_BASE_COMPONENT_TYPES)[number];

/**
 * Legacy protocol types that render as a catalog component. Their historical
 * props are free-form (`text` carries `value`, etc.), so aliases are resolved
 * for rendering but are NOT props-validated against the catalog schema.
 */
export const KYBERION_BASE_ALIASES = Object.freeze({
  text: 'ui:text',
  button: 'ui:button',
  card: 'ui:section',
  container: 'ui:stack',
} as const satisfies Record<string, KyberionBaseComponentType>);

export type KyberionBaseAlias = keyof typeof KYBERION_BASE_ALIASES;

// ---------------------------------------------------------------------------
// Shared prop vocabulary
// ---------------------------------------------------------------------------

export type KbTone = 'neutral' | 'accent' | 'info' | 'success' | 'warning' | 'danger';
export type KbCalloutTone = 'info' | 'success' | 'warning' | 'danger';
export type KbSurfaceRole =
  'concierge' | 'presence-studio' | 'chronos-mirror-v2' | 'operator-surface' | 'computer-surface';
export type KbDensity = 'comfortable' | 'compact';
export type KbGap = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type KbButtonVariant = 'primary' | 'secondary' | 'danger' | 'ghost';
export type KbStatusDomain =
  'readiness' | 'connection' | 'provider' | 'mission' | 'progress' | 'runtime';

/**
 * Canonical status values — exactly the set `renderStatus()` in
 * `ux-vocabulary.ts` maps (the dashboard vocabulary the ui-ux governance check
 * enforces). Do not add values here without adding them there first.
 */
export const KB_STATUS_VALUES = [
  'active',
  'archived',
  'available',
  'blocked',
  'busy',
  'completed',
  'connected',
  'connecting',
  'degraded',
  'disconnected',
  'distilling',
  'done',
  'error',
  'failed',
  'fallback',
  'fully_automatable',
  'missing',
  'missing_runtime_prerequisites',
  'n/a',
  'needs_assets',
  'needs_clarification',
  'needs_external_assets',
  'needs_runtime_prerequisites',
  'needs_setup',
  'offline',
  'paused',
  'pending',
  'planned',
  'ready',
  'recovered',
  'review',
  'running',
  'stale',
  'stopped',
  'unavailable',
  'working',
] as const;

export type KbStatus = (typeof KB_STATUS_VALUES)[number];
export type KbStatusTone = 'success' | 'info' | 'warning' | 'danger' | 'neutral';

/** Visual tone for each canonical status; `kyberion-ui.css` is generated from this map. */
export const KB_STATUS_TONES: Readonly<Record<KbStatus, KbStatusTone>> = Object.freeze({
  ready: 'success',
  fully_automatable: 'success',
  connected: 'success',
  available: 'success',
  done: 'success',
  completed: 'success',
  recovered: 'success',
  running: 'success',
  active: 'info',
  connecting: 'info',
  working: 'info',
  busy: 'info',
  review: 'info',
  distilling: 'info',
  needs_clarification: 'warning',
  needs_external_assets: 'warning',
  needs_assets: 'warning',
  needs_setup: 'warning',
  missing_runtime_prerequisites: 'warning',
  needs_runtime_prerequisites: 'warning',
  pending: 'warning',
  degraded: 'warning',
  fallback: 'warning',
  paused: 'warning',
  stale: 'warning',
  blocked: 'danger',
  missing: 'danger',
  error: 'danger',
  unavailable: 'danger',
  failed: 'danger',
  disconnected: 'danger',
  offline: 'danger',
  'n/a': 'neutral',
  planned: 'neutral',
  archived: 'neutral',
  stopped: 'neutral',
});

export interface KbAction {
  id: string;
  payload?: Record<string, unknown>;
}

/** A labelled link or action; exactly one of `href` / `action`. */
export type KbActionRef = {
  label: string;
  variant?: KbButtonVariant;
  disabled?: boolean;
} & ({ href: string; action?: never } | { action: KbAction; href?: never });

export interface KbNavItem {
  id: string;
  label: string;
  hint?: string;
  href: string;
  icon?: string;
  active?: boolean;
}

// ---------------------------------------------------------------------------
// Per-component props
// ---------------------------------------------------------------------------

export interface KbAppShellProps {
  density?: KbDensity;
  theme?: 'system' | 'light' | 'dark';
  role?: KbSurfaceRole;
}

export interface KbPageHeaderProps {
  title: string;
  subtitle?: string;
  role_badge?: { label: string; tone?: KbTone; role?: KbSurfaceRole };
  actions?: KbActionRef[];
}

export interface KbNavRailProps {
  label?: string;
  items: KbNavItem[];
  footer_items?: KbNavItem[];
}

export interface KbTabsProps {
  items: Array<{ id: string; label: string; count?: number; href?: string }>;
  active?: string;
  overflow?: 'wrap' | 'menu';
}

export interface KbStackProps {
  gap?: KbGap;
  direction?: 'vertical' | 'horizontal';
  align?: 'start' | 'center' | 'end' | 'stretch';
  wrap?: boolean;
}

export interface KbGridProps {
  gap?: KbGap;
  columns?: number;
  min_column_width?: 'xs' | 'sm' | 'md' | 'lg';
}

export interface KbSectionProps {
  title?: string;
  description?: string;
  tone?: KbTone;
  actions?: KbActionRef[];
}

export interface KbNextActionProps {
  eyebrow?: string;
  title: string;
  reason?: string;
  /** Required unless `state` is `loading` or `empty`. */
  primary?: KbActionRef;
  secondary?: KbActionRef;
  state?: 'ready' | 'loading' | 'empty';
}

export interface KbMetricProps {
  label: string;
  value: string | number;
  unit?: string;
  delta?: string;
  trend?: 'up' | 'down' | 'flat';
  tone?: KbTone;
  description?: string;
}

export interface KbKvProps {
  items: Array<{ label: string; value: string | number | boolean; mono?: boolean }>;
}

export interface KbTableColumn {
  key: string;
  label: string;
  align?: 'start' | 'center' | 'end';
  mono?: boolean;
  width?: string;
}

export interface KbTableProps {
  caption?: string;
  columns: KbTableColumn[];
  rows: Array<Record<string, string | number | boolean | null>>;
  row_href_key?: string;
  empty?: string;
}

export interface KbListProps {
  items: Array<{ title: string; meta?: string; status?: KbStatus; href?: string }>;
  variant?: 'plain' | 'timeline';
}

export interface KbTextProps {
  text: string;
  variant?: 'body' | 'muted' | 'caption' | 'mono' | 'title';
}

export interface KbStatusPillProps {
  status: KbStatus;
  domain?: KbStatusDomain;
  label?: string;
}

export interface KbBadgeProps {
  label: string;
  tone?: KbTone;
  role?: KbSurfaceRole;
}

export interface KbCalloutProps {
  tone: KbCalloutTone;
  title: string;
  body?: string;
  action?: KbActionRef;
}

export interface KbEmptyStateProps {
  title: string;
  body?: string;
  action?: KbActionRef;
}

export interface KbSkeletonProps {
  lines?: number;
  shape?: 'text' | 'card' | 'table';
}

export type KbButtonProps = {
  label: string;
  variant?: KbButtonVariant;
  disabled?: boolean;
} & ({ href: string; action?: never } | { action: KbAction; href?: never });

export interface KbDisclosureProps {
  summary: string;
  open?: boolean;
}

export interface KyberionBasePropsByType {
  'ui:app-shell': KbAppShellProps;
  'ui:page-header': KbPageHeaderProps;
  'ui:nav-rail': KbNavRailProps;
  'ui:tabs': KbTabsProps;
  'ui:stack': KbStackProps;
  'ui:grid': KbGridProps;
  'ui:section': KbSectionProps;
  'ui:next-action': KbNextActionProps;
  'ui:metric': KbMetricProps;
  'ui:kv': KbKvProps;
  'ui:table': KbTableProps;
  'ui:list': KbListProps;
  'ui:text': KbTextProps;
  'ui:status-pill': KbStatusPillProps;
  'ui:badge': KbBadgeProps;
  'ui:callout': KbCalloutProps;
  'ui:empty-state': KbEmptyStateProps;
  'ui:skeleton': KbSkeletonProps;
  'ui:button': KbButtonProps;
  'ui:disclosure': KbDisclosureProps;
  'ui:settings-group': KbSettingsGroupProps;
  'ui:setting-row': KbSettingRowProps;
  'ui:switch': KbSwitchProps;
  'ui:checkbox': KbCheckboxProps;
  'ui:select': KbSelectProps;
  'ui:radio-group': KbRadioGroupProps;
  'ui:segmented': KbSegmentedProps;
  'ui:text-field': KbTextFieldProps;
  'ui:textarea': KbTextareaProps;
  'ui:slider': KbSliderProps;
  'ui:integration-item': KbIntegrationItemProps;
  'ui:save-bar': KbSaveBarProps;
  'ui:file-drop': KbFileDropProps;
  'ui:camera-capture': KbCameraCaptureProps;
  'ui:avatar-picker': KbAvatarPickerProps;
  'ui:secret-field': KbSecretFieldProps;
  'ui:bar-chart': KbBarChartProps;
  'ui:line-chart': KbLineChartProps;
  'ui:donut': KbDonutProps;
  'ui:sparkline': KbSparklineProps;
  'ui:heatmap': KbHeatmapProps;
  'ui:meter': KbMeterProps;
  'ui:sequence': KbSequenceProps;
  'ui:flow': KbFlowProps;
  'ui:stat-list': KbStatListProps;
}

// ---------------------------------------------------------------------------
// UI-01c settings & forms (SURFACE_UI_UNIFICATION_PLAN §3.3)
// ---------------------------------------------------------------------------
//
// Interaction contract: controls are controlled by `value`; every edit is
// reported as `onAction('field.change', { name, value })` (the caller owns the
// data model). Files, captured images and secret values are NEVER props: the
// schema has no slot for file contents or a secret `value`, and the renderers
// hand those only to `onAction` at runtime (see `KB_FORM_ACTIONS`).

/** Action ids the form components dispatch when the props give no explicit `action`. */
export const KB_FORM_ACTIONS = Object.freeze({
  /** `{ name, value }` — every controlled field edit (never for `ui:secret-field`). */
  fieldChange: 'field.change',
  /** `{ name, files: File[], rejected: [{ name, size, reason }] }` */
  filesAdd: 'file.add',
  /** `{ name, file_id }` — remove / cancel one `files[]` entry. */
  fileRemove: 'file.remove',
  /** `{ name, file: File }` — confirmed camera photo. */
  cameraCapture: 'camera.capture',
  /** `{ name }` */
  cameraCancel: 'camera.cancel',
  /** `{ name, file: File, source: 'upload' | 'camera' }` — square-cropped image. */
  avatarChange: 'avatar.change',
  /** `{ name }` */
  avatarRemove: 'avatar.remove',
} as const);

export interface KbFieldBase {
  /** Field key reported in `field.change` / action payloads. */
  name: string;
  label: string;
  /** Visually hide the label (it stays the accessible name), e.g. inside a `ui:setting-row`. */
  hide_label?: boolean;
  help?: string;
  error?: string;
  required?: boolean;
  disabled?: boolean;
}

export interface KbFieldOption {
  value: string;
  label: string;
  description?: string;
  disabled?: boolean;
}

export interface KbSettingsGroupProps {
  title: string;
  description?: string;
}

export interface KbSettingRowProps {
  label: string;
  description?: string;
  /** Visual separation for dangerous settings (delete, reset). */
  tone?: 'neutral' | 'danger';
}

export interface KbSwitchProps extends KbFieldBase {
  value?: boolean;
}

export interface KbCheckboxProps extends KbFieldBase {
  value?: boolean;
}

export interface KbSelectProps extends KbFieldBase {
  value?: string;
  options: KbFieldOption[];
  placeholder?: string;
}

export interface KbRadioGroupProps extends KbFieldBase {
  value?: string;
  options: KbFieldOption[];
  direction?: 'vertical' | 'horizontal';
}

export interface KbSegmentedProps extends KbFieldBase {
  value?: string;
  options: KbFieldOption[];
}

export interface KbTextFieldProps extends KbFieldBase {
  value?: string | number;
  type?: 'text' | 'email' | 'url' | 'number' | 'search';
  placeholder?: string;
  maxlength?: number;
  min?: number;
  max?: number;
  step?: number;
  readonly?: boolean;
}

export interface KbTextareaProps extends KbFieldBase {
  value?: string;
  placeholder?: string;
  maxlength?: number;
  rows?: number;
  readonly?: boolean;
}

export interface KbSliderProps extends KbFieldBase {
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
}

export type KbIntegrationState = 'connected' | 'needs_reauth' | 'disconnected' | 'error';

export interface KbIntegrationItemProps {
  title: string;
  state: KbIntegrationState;
  description?: string;
  /** Account / scope detail, e.g. the connected address. */
  detail?: string;
  icon?: string;
  actions?: KbActionRef[];
}

export interface KbSaveBarProps {
  state: 'clean' | 'dirty' | 'saving' | 'saved' | 'error';
  message?: string;
  save_action: KbAction;
  discard_action?: KbAction;
  save_label?: string;
  discard_label?: string;
}

/** One selected file's metadata — never its contents. */
export interface KbFileEntry {
  id: string;
  name: string;
  size?: number;
  status: 'queued' | 'uploading' | 'done' | 'error';
  /** 0–100 while `uploading`. */
  progress?: number;
  error?: string;
}

export interface KbFileDropProps extends KbFieldBase {
  description?: string;
  /** `<input accept>` list: extensions (`.pdf`) and MIME types (`image/*`). */
  accept?: string;
  multiple?: boolean;
  max_bytes?: number;
  max_files?: number;
  files?: KbFileEntry[];
  action?: KbAction;
  remove_action?: KbAction;
}

export interface KbCameraCaptureProps extends KbFieldBase {
  description?: string;
  facing?: 'user' | 'environment';
  aspect?: 'square' | 'landscape';
  action?: KbAction;
  cancel_action?: KbAction;
}

export interface KbAvatarPickerProps extends KbFieldBase {
  /** Current image (http(s) / same-origin URL); never inline data. */
  image_url?: string;
  initials?: string;
  shape?: 'circle' | 'square';
  allow_camera?: boolean;
  removable?: boolean;
  action?: KbAction;
  remove_action?: KbAction;
}

/**
 * Secret input (API tokens). There is deliberately no `value`: a stored
 * secret is never sent back to the page — only `configured` and `last4`.
 * Submit dispatches `action` with `{ name, service_id?, secret_key?, value }`.
 */
export interface KbSecretFieldProps extends KbFieldBase {
  action: KbAction;
  remove_action?: KbAction;
  configured?: boolean;
  last4?: string;
  placeholder?: string;
  service_id?: string;
  secret_key?: string;
}

// ---------------------------------------------------------------------------
// UI-01b charts & visualisation (SURFACE_UI_UNIFICATION_PLAN §3.2)
// ---------------------------------------------------------------------------
//
// Layout (scales, ticks, stacking, DAG layering, sequence ordering) lives once
// in `libs/shared-ui/vanilla/charts.js`; both renderers draw its vnode tree.
// Colors come only from the `--kb-ui-viz-*` tokens (categorical slots 1..8,
// sequential / diverging steps 1..5). More than 8 series are never cycled:
// only the first 8 are drawn (a donut folds the rest into "Other").

interface KbChartCommonProps {
  title?: string;
  description?: string;
  density?: KbDensity;
  /** Override for the localized "no data" empty state. */
  empty?: string;
}

export interface KbChartDatum {
  label: string;
  value: number | null;
}

export interface KbBarChartProps extends KbChartCommonProps {
  categories?: string[];
  series?: Array<{ name: string; values: Array<number | null> }>;
  /** Single-series shorthand (chronos `display:bar-chart` compatible). */
  data?: KbChartDatum[];
  orientation?: 'vertical' | 'horizontal';
  stacked?: boolean;
  unit?: string;
  show_values?: boolean;
}

export interface KbLineChartProps extends KbChartCommonProps {
  series: Array<{ name: string; points: Array<{ x: string | number; y: number | null }> }>;
  area?: boolean;
  y_unit?: string;
}

export interface KbDonutProps extends KbChartCommonProps {
  segments?: KbChartDatum[];
  /** chronos `display:donut` shorthand. */
  data?: KbChartDatum[];
  center_label?: string;
  center_value?: string | number;
  unit?: string;
}

export interface KbSparklineProps {
  points: Array<number | null>;
  label?: string;
  tone?: KbTone;
  unit?: string;
  show_value?: boolean;
  empty?: string;
}

export interface KbHeatmapProps extends KbChartCommonProps {
  rows: string[];
  columns: string[];
  values: Array<Array<number | null>>;
  unit?: string;
  scale?: 'sequential' | 'diverging';
  midpoint?: number;
  show_values?: boolean;
}

export interface KbMeterProps {
  label?: string;
  value: number | null;
  /** Default 100. */
  max?: number;
  unit?: string;
  thresholds?: Array<{ value: number; tone: 'success' | 'warning' | 'danger' }>;
  description?: string;
  empty?: string;
}

export interface KbSequenceProps extends KbChartCommonProps {
  participants: Array<string | { id: string; label?: string }>;
  messages: Array<{
    from: string;
    to: string;
    label: string;
    at?: string | number;
    status?: KbStatus;
    /** `reply` draws a dashed arrow. */
    kind?: 'call' | 'reply' | 'note';
  }>;
}

export interface KbFlowProps extends KbChartCommonProps {
  nodes: Array<{ id: string; label: string; stage?: string; status?: KbStatus; meta?: string }>;
  edges?: Array<{ from: string; to: string; label?: string }>;
  stages?: Array<string | { id: string; label?: string }>;
}

export interface KbStatListProps {
  title?: string;
  density?: KbDensity;
  empty?: string;
  items: Array<{ label: string; value: string | number; unit?: string; hint?: string }>;
}

// ---------------------------------------------------------------------------
// Resolution & validation
// ---------------------------------------------------------------------------

const CATALOG_TYPE_SET: ReadonlySet<string> = new Set(KYBERION_BASE_COMPONENT_TYPES);

export function isKyberionBaseComponentType(type: string): type is KyberionBaseComponentType {
  return CATALOG_TYPE_SET.has(type);
}

/** Resolve a component type (or legacy alias) to its catalog type; `null` when outside the catalog. */
export function resolveKyberionBaseType(type: string): KyberionBaseComponentType | null {
  if (isKyberionBaseComponentType(type)) return type;
  return Object.prototype.hasOwnProperty.call(KYBERION_BASE_ALIASES, type)
    ? KYBERION_BASE_ALIASES[type as KyberionBaseAlias]
    : null;
}

let catalogValidators: Map<KyberionBaseComponentType, ValidateFunction> | null = null;

function loadCatalogValidators(): Map<KyberionBaseComponentType, ValidateFunction> {
  if (catalogValidators) return catalogValidators;
  const ajv = createAjv2020({ allowUnionTypes: true });
  compileSchema(
    pathResolver.knowledge('product/schemas/a2ui-catalog-kyberion-base.schema.json'),
    ajv
  );
  const validators = new Map<KyberionBaseComponentType, ValidateFunction>();
  for (const type of KYBERION_BASE_COMPONENT_TYPES) {
    const validate = ajv.getSchema(`${KYBERION_BASE_CATALOG_SCHEMA_ID}#/$defs/props:${type}`);
    if (!validate)
      throw new Error(`A2UI catalog ${KYBERION_BASE_CATALOG_ID} has no schema for ${type}.`);
    validators.set(type, validate);
  }
  catalogValidators = validators;
  return validators;
}

function formatAjvErrors(validate: ValidateFunction): string {
  return (validate.errors || [])
    .slice(0, 5)
    .map((error) => {
      const where = error.instancePath || '(props)';
      const extra =
        error.keyword === 'additionalProperties'
          ? ` (${String((error.params as { additionalProperty?: string }).additionalProperty)})`
          : error.keyword === 'enum'
            ? ` (${((error.params as { allowedValues?: unknown[] }).allowedValues || []).join('|')})`
            : '';
      return `${where} ${error.message ?? error.keyword}${extra}`;
    })
    .join('; ');
}

/**
 * Validate props for a `ui:*` catalog component. Throws with a readable reason
 * on violation. Types outside the catalog (including legacy aliases) are not
 * checked here — callers decide their policy.
 */
export function validateA2UIComponentProps<T extends KyberionBaseComponentType>(
  type: T,
  props: unknown
): KyberionBasePropsByType[T] {
  if (!isKyberionBaseComponentType(type)) {
    throw new Error(
      `A2UI component type ${String(type)} is not in catalog ${KYBERION_BASE_CATALOG_ID}.`
    );
  }
  const validate = loadCatalogValidators().get(type);
  if (!validate)
    throw new Error(`A2UI catalog ${KYBERION_BASE_CATALOG_ID} has no schema for ${type}.`);
  if (!validate(props)) {
    throw new Error(`A2UI ${type} props are invalid: ${formatAjvErrors(validate)}.`);
  }
  return props as KyberionBasePropsByType[T];
}
