import type { ValidateFunction } from 'ajv';
import { compileSchema, createAjv2020 } from './foundation/ajv.js';
import { pathResolver } from './path-resolver.js';

/**
 * A2UI `kyberion-base` catalog (UI-01, SURFACE_UI_UNIFICATION_PLAN §3).
 *
 * The shared component vocabulary every Kyberion surface renders with the same
 * `.kb-*` class contract (`kyberion-ui.css`, generated by
 * `scripts/generate_design_tokens.ts`). Props are validated against
 * `knowledge/product/schemas/a2ui-catalog-kyberion-base.schema.json`; the TS
 * types below mirror that schema and must stay in lock-step with it
 * (`a2ui-catalog.test.ts` pins both).
 */

export const KYBERION_BASE_CATALOG_ID = 'kyberion-base';

export const KYBERION_BASE_CATALOG_SCHEMA_ID =
  'https://kyberion.ai/schemas/a2ui-catalog-kyberion-base.schema.json';

export const KYBERION_BASE_COMPONENT_TYPES = [
  'ui:app-shell',
  'ui:page-header',
  'ui:nav-rail',
  'ui:tabs',
  'ui:stack',
  'ui:grid',
  'ui:section',
  'ui:next-action',
  'ui:metric',
  'ui:kv',
  'ui:table',
  'ui:list',
  'ui:text',
  'ui:status-pill',
  'ui:badge',
  'ui:callout',
  'ui:empty-state',
  'ui:skeleton',
  'ui:button',
  'ui:disclosure',
] as const;

export type KyberionBaseComponentType = (typeof KYBERION_BASE_COMPONENT_TYPES)[number];

/**
 * Legacy protocol types that render as a catalog component. Their historical
 * props are free-form (`text` carries `value`, etc.), so aliases are resolved
 * for rendering but are NOT props-validated against the catalog schema.
 */
export const KYBERION_BASE_ALIASES = Object.freeze({
  text: 'ui:text',
  button: 'ui:button',
  card: 'ui:section',
  container: 'ui:stack',
} as const satisfies Record<string, KyberionBaseComponentType>);

export type KyberionBaseAlias = keyof typeof KYBERION_BASE_ALIASES;

// ---------------------------------------------------------------------------
// Shared prop vocabulary
// ---------------------------------------------------------------------------

export type KbTone = 'neutral' | 'accent' | 'info' | 'success' | 'warning' | 'danger';
export type KbCalloutTone = 'info' | 'success' | 'warning' | 'danger';
export type KbSurfaceRole =
  'concierge' | 'presence-studio' | 'chronos-mirror-v2' | 'operator-surface' | 'computer-surface';
export type KbDensity = 'comfortable' | 'compact';
export type KbGap = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type KbButtonVariant = 'primary' | 'secondary' | 'danger' | 'ghost';
export type KbStatusDomain =
  'readiness' | 'connection' | 'provider' | 'mission' | 'progress' | 'runtime';

/**
 * Canonical status values — exactly the set `renderStatus()` in
 * `ux-vocabulary.ts` maps (the dashboard vocabulary the ui-ux governance check
 * enforces). Do not add values here without adding them there first.
 */
export const KB_STATUS_VALUES = [
  'active',
  'archived',
  'available',
  'blocked',
  'busy',
  'completed',
  'connected',
  'connecting',
  'degraded',
  'disconnected',
  'distilling',
  'done',
  'error',
  'failed',
  'fallback',
  'fully_automatable',
  'missing',
  'missing_runtime_prerequisites',
  'n/a',
  'needs_assets',
  'needs_clarification',
  'needs_external_assets',
  'needs_runtime_prerequisites',
  'needs_setup',
  'offline',
  'paused',
  'pending',
  'planned',
  'ready',
  'recovered',
  'review',
  'running',
  'stale',
  'stopped',
  'unavailable',
  'working',
] as const;

export type KbStatus = (typeof KB_STATUS_VALUES)[number];
export type KbStatusTone = 'success' | 'info' | 'warning' | 'danger' | 'neutral';

/** Visual tone for each canonical status; `kyberion-ui.css` is generated from this map. */
export const KB_STATUS_TONES: Readonly<Record<KbStatus, KbStatusTone>> = Object.freeze({
  ready: 'success',
  fully_automatable: 'success',
  connected: 'success',
  available: 'success',
  done: 'success',
  completed: 'success',
  recovered: 'success',
  running: 'success',
  active: 'info',
  connecting: 'info',
  working: 'info',
  busy: 'info',
  review: 'info',
  distilling: 'info',
  needs_clarification: 'warning',
  needs_external_assets: 'warning',
  needs_assets: 'warning',
  needs_setup: 'warning',
  missing_runtime_prerequisites: 'warning',
  needs_runtime_prerequisites: 'warning',
  pending: 'warning',
  degraded: 'warning',
  fallback: 'warning',
  paused: 'warning',
  stale: 'warning',
  blocked: 'danger',
  missing: 'danger',
  error: 'danger',
  unavailable: 'danger',
  failed: 'danger',
  disconnected: 'danger',
  offline: 'danger',
  'n/a': 'neutral',
  planned: 'neutral',
  archived: 'neutral',
  stopped: 'neutral',
});

export interface KbAction {
  id: string;
  payload?: Record<string, unknown>;
}

/** A labelled link or action; exactly one of `href` / `action`. */
export type KbActionRef = {
  label: string;
  variant?: KbButtonVariant;
  disabled?: boolean;
} & ({ href: string; action?: never } | { action: KbAction; href?: never });

export interface KbNavItem {
  id: string;
  label: string;
  hint?: string;
  href: string;
  icon?: string;
  active?: boolean;
}

// ---------------------------------------------------------------------------
// Per-component props
// ---------------------------------------------------------------------------

export interface KbAppShellProps {
  density?: KbDensity;
  theme?: 'system' | 'light' | 'dark';
  role?: KbSurfaceRole;
}

export interface KbPageHeaderProps {
  title: string;
  subtitle?: string;
  role_badge?: { label: string; tone?: KbTone; role?: KbSurfaceRole };
  actions?: KbActionRef[];
}

export interface KbNavRailProps {
  label?: string;
  items: KbNavItem[];
  footer_items?: KbNavItem[];
}

export interface KbTabsProps {
  items: Array<{ id: string; label: string; count?: number; href?: string }>;
  active?: string;
  overflow?: 'wrap' | 'menu';
}

export interface KbStackProps {
  gap?: KbGap;
  direction?: 'vertical' | 'horizontal';
  align?: 'start' | 'center' | 'end' | 'stretch';
  wrap?: boolean;
}

export interface KbGridProps {
  gap?: KbGap;
  columns?: number;
  min_column_width?: 'xs' | 'sm' | 'md' | 'lg';
}

export interface KbSectionProps {
  title?: string;
  description?: string;
  tone?: KbTone;
  actions?: KbActionRef[];
}

export interface KbNextActionProps {
  eyebrow?: string;
  title: string;
  reason?: string;
  /** Required unless `state` is `loading` or `empty`. */
  primary?: KbActionRef;
  secondary?: KbActionRef;
  state?: 'ready' | 'loading' | 'empty';
}

export interface KbMetricProps {
  label: string;
  value: string | number;
  unit?: string;
  delta?: string;
  trend?: 'up' | 'down' | 'flat';
  tone?: KbTone;
  description?: string;
}

export interface KbKvProps {
  items: Array<{ label: string; value: string | number | boolean; mono?: boolean }>;
}

export interface KbTableColumn {
  key: string;
  label: string;
  align?: 'start' | 'center' | 'end';
  mono?: boolean;
  width?: string;
}

export interface KbTableProps {
  caption?: string;
  columns: KbTableColumn[];
  rows: Array<Record<string, string | number | boolean | null>>;
  row_href_key?: string;
  empty?: string;
}

export interface KbListProps {
  items: Array<{ title: string; meta?: string; status?: KbStatus; href?: string }>;
  variant?: 'plain' | 'timeline';
}

export interface KbTextProps {
  text: string;
  variant?: 'body' | 'muted' | 'caption' | 'mono' | 'title';
}

export interface KbStatusPillProps {
  status: KbStatus;
  domain?: KbStatusDomain;
  label?: string;
}

export interface KbBadgeProps {
  label: string;
  tone?: KbTone;
  role?: KbSurfaceRole;
}

export interface KbCalloutProps {
  tone: KbCalloutTone;
  title: string;
  body?: string;
  action?: KbActionRef;
}

export interface KbEmptyStateProps {
  title: string;
  body?: string;
  action?: KbActionRef;
}

export interface KbSkeletonProps {
  lines?: number;
  shape?: 'text' | 'card' | 'table';
}

export type KbButtonProps = {
  label: string;
  variant?: KbButtonVariant;
  disabled?: boolean;
} & ({ href: string; action?: never } | { action: KbAction; href?: never });

export interface KbDisclosureProps {
  summary: string;
  open?: boolean;
}

export interface KyberionBasePropsByType {
  'ui:app-shell': KbAppShellProps;
  'ui:page-header': KbPageHeaderProps;
  'ui:nav-rail': KbNavRailProps;
  'ui:tabs': KbTabsProps;
  'ui:stack': KbStackProps;
  'ui:grid': KbGridProps;
  'ui:section': KbSectionProps;
  'ui:next-action': KbNextActionProps;
  'ui:metric': KbMetricProps;
  'ui:kv': KbKvProps;
  'ui:table': KbTableProps;
  'ui:list': KbListProps;
  'ui:text': KbTextProps;
  'ui:status-pill': KbStatusPillProps;
  'ui:badge': KbBadgeProps;
  'ui:callout': KbCalloutProps;
  'ui:empty-state': KbEmptyStateProps;
  'ui:skeleton': KbSkeletonProps;
  'ui:button': KbButtonProps;
  'ui:disclosure': KbDisclosureProps;
}

// ---------------------------------------------------------------------------
// Resolution & validation
// ---------------------------------------------------------------------------

const CATALOG_TYPE_SET: ReadonlySet<string> = new Set(KYBERION_BASE_COMPONENT_TYPES);

export function isKyberionBaseComponentType(type: string): type is KyberionBaseComponentType {
  return CATALOG_TYPE_SET.has(type);
}

/** Resolve a component type (or legacy alias) to its catalog type; `null` when outside the catalog. */
export function resolveKyberionBaseType(type: string): KyberionBaseComponentType | null {
  if (isKyberionBaseComponentType(type)) return type;
  return Object.prototype.hasOwnProperty.call(KYBERION_BASE_ALIASES, type)
    ? KYBERION_BASE_ALIASES[type as KyberionBaseAlias]
    : null;
}

let catalogValidators: Map<KyberionBaseComponentType, ValidateFunction> | null = null;

function loadCatalogValidators(): Map<KyberionBaseComponentType, ValidateFunction> {
  if (catalogValidators) return catalogValidators;
  const ajv = createAjv2020({ allowUnionTypes: true });
  compileSchema(
    pathResolver.knowledge('product/schemas/a2ui-catalog-kyberion-base.schema.json'),
    ajv
  );
  const validators = new Map<KyberionBaseComponentType, ValidateFunction>();
  for (const type of KYBERION_BASE_COMPONENT_TYPES) {
    const validate = ajv.getSchema(`${KYBERION_BASE_CATALOG_SCHEMA_ID}#/$defs/props:${type}`);
    if (!validate)
      throw new Error(`A2UI catalog ${KYBERION_BASE_CATALOG_ID} has no schema for ${type}.`);
    validators.set(type, validate);
  }
  catalogValidators = validators;
  return validators;
}

function formatAjvErrors(validate: ValidateFunction): string {
  return (validate.errors || [])
    .slice(0, 5)
    .map((error) => {
      const where = error.instancePath || '(props)';
      const extra =
        error.keyword === 'additionalProperties'
          ? ` (${String((error.params as { additionalProperty?: string }).additionalProperty)})`
          : error.keyword === 'enum'
            ? ` (${((error.params as { allowedValues?: unknown[] }).allowedValues || []).join('|')})`
            : '';
      return `${where} ${error.message ?? error.keyword}${extra}`;
    })
    .join('; ');
}

/**
 * Validate props for a `ui:*` catalog component. Throws with a readable reason
 * on violation. Types outside the catalog (including legacy aliases) are not
 * checked here — callers decide their policy.
 */
export function validateA2UIComponentProps<T extends KyberionBaseComponentType>(
  type: T,
  props: unknown
): KyberionBasePropsByType[T] {
  if (!isKyberionBaseComponentType(type)) {
    throw new Error(
      `A2UI component type ${String(type)} is not in catalog ${KYBERION_BASE_CATALOG_ID}.`
    );
  }
  const validate = loadCatalogValidators().get(type);
  if (!validate)
    throw new Error(`A2UI catalog ${KYBERION_BASE_CATALOG_ID} has no schema for ${type}.`);
  if (!validate(props)) {
    throw new Error(`A2UI ${type} props are invalid: ${formatAjvErrors(validate)}.`);
  }
  return props as KyberionBasePropsByType[T];
}
