import type { ValidateFunction } from 'ajv';
import { compileSchema, createAjv2020 } from './foundation/ajv.js';
import { pathResolver } from './path-resolver.js';

/**
 * A2UI `kyberion-base` catalog (UI-01, SURFACE_UI_UNIFICATION_PLAN §3).
 *
 * The shared component vocabulary every Kyberion surface renders with the same
 * `.kb-*` class contract (`kyberion-ui.css`, generated by
 * `scripts/generate_design_tokens.ts`). Props are validated against
 * `knowledge/product/schemas/a2ui-catalog-kyberion-base.schema.json`; the TS
 * types below mirror that schema and must stay in lock-step with it
 * (`a2ui-catalog.test.ts` pins both).
 */

export const A2UI_BASE_CATALOG_ID = 'kyberion-base';

export const A2UI_BASE_CATALOG_SCHEMA_ID =
  'https://kyberion.ai/schemas/a2ui-catalog-kyberion-base.schema.json';

export const A2UI_BASE_COMPONENT_TYPES = [
  'ui:app-shell',
  'ui:page-header',
  'ui:nav-rail',
  'ui:tabs',
  'ui:stack',
  'ui:grid',
  'ui:section',
  'ui:next-action',
  'ui:metric',
  'ui:kv',
  'ui:table',
  'ui:list',
  'ui:text',
  'ui:code',
  'ui:status-pill',
  'ui:badge',
  'ui:callout',
  'ui:empty-state',
  'ui:skeleton',
  'ui:button',
  'ui:disclosure',
  'ui:display-controls',
  // UI-01c settings & forms (SURFACE_UI_UNIFICATION_PLAN §3.3)
  'ui:settings-group',
  'ui:setting-row',
  'ui:switch',
  'ui:checkbox',
  'ui:select',
  'ui:radio-group',
  'ui:segmented',
  'ui:text-field',
  'ui:textarea',
  'ui:slider',
  'ui:integration-item',
  'ui:save-bar',
  'ui:file-drop',
  'ui:camera-capture',
  'ui:avatar-picker',
  'ui:secret-field',
  // UI-01b charts & visualisation (SURFACE_UI_UNIFICATION_PLAN §3.2)
  'ui:bar-chart',
  'ui:line-chart',
  'ui:donut',
  'ui:sparkline',
  'ui:heatmap',
  'ui:meter',
  'ui:sequence',
  'ui:flow',
  'ui:stat-list',
  // PA-02 voice (PADS_A2UI_AND_AVATAR_PLAN §3)
  'ui:voice-input',
  'ui:voice-state',
  // PA-01 pads (PADS_A2UI_AND_AVATAR_PLAN §3)
  'ui:toolbar',
  'ui:dialog',
  'ui:drawing-palette',
  'ui:sketch-board',
] as const;

export type KyberionBaseComponentType = (typeof A2UI_BASE_COMPONENT_TYPES)[number];

/**
 * Legacy protocol types that render as a catalog component. Their historical
 * props are free-form (`text` carries `value`, etc.), so aliases are resolved
 * for rendering but are NOT props-validated against the catalog schema.
 */
export const A2UI_BASE_ALIASES = Object.freeze({
  text: 'ui:text',
  button: 'ui:button',
  card: 'ui:section',
  container: 'ui:stack',
} as const satisfies Record<string, KyberionBaseComponentType>);

export type KyberionBaseAlias = keyof typeof A2UI_BASE_ALIASES;

// ---------------------------------------------------------------------------
// Shared prop vocabulary
// ---------------------------------------------------------------------------

export type KbTone = 'neutral' | 'accent' | 'info' | 'success' | 'warning' | 'danger';
export type KbCalloutTone = 'info' | 'success' | 'warning' | 'danger';
export type KbSurfaceRole =
  'concierge' | 'presence-studio' | 'chronos-mirror-v2' | 'operator-surface' | 'computer-surface';
export type KbDensity = 'comfortable' | 'compact';
export type KbGap = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type KbButtonVariant = 'primary' | 'secondary' | 'danger' | 'ghost';
export type KbStatusDomain =
  'readiness' | 'connection' | 'provider' | 'mission' | 'progress' | 'runtime';

/**
 * Canonical status values — exactly the set `renderStatus()` in
 * `ux-vocabulary.ts` maps (the dashboard vocabulary the ui-ux governance check
 * enforces). Do not add values here without adding them there first.
 */
export const KB_STATUS_VALUES = [
  'active',
  'archived',
  'available',
  'blocked',
  'busy',
  'completed',
  'connected',
  'connecting',
  'degraded',
  'disconnected',
  'distilling',
  'done',
  'error',
  'failed',
  'fallback',
  'fully_automatable',
  'missing',
  'missing_runtime_prerequisites',
  'n/a',
  'needs_assets',
  'needs_clarification',
  'needs_external_assets',
  'needs_runtime_prerequisites',
  'needs_setup',
  'offline',
  'paused',
  'pending',
  'planned',
  'ready',
  'recovered',
  'review',
  'running',
  'stale',
  'stopped',
  'unavailable',
  'working',
] as const;

export type KbStatus = (typeof KB_STATUS_VALUES)[number];
export type KbStatusTone = 'success' | 'info' | 'warning' | 'danger' | 'neutral';

/** Visual tone for each canonical status; `kyberion-ui.css` is generated from this map. */
export const KB_STATUS_TONES: Readonly<Record<KbStatus, KbStatusTone>> = Object.freeze({
  ready: 'success',
  fully_automatable: 'success',
  connected: 'success',
  available: 'success',
  done: 'success',
  completed: 'success',
  recovered: 'success',
  running: 'success',
  active: 'info',
  connecting: 'info',
  working: 'info',
  busy: 'info',
  review: 'info',
  distilling: 'info',
  needs_clarification: 'warning',
  needs_external_assets: 'warning',
  needs_assets: 'warning',
  needs_setup: 'warning',
  missing_runtime_prerequisites: 'warning',
  needs_runtime_prerequisites: 'warning',
  pending: 'warning',
  degraded: 'warning',
  fallback: 'warning',
  paused: 'warning',
  stale: 'warning',
  blocked: 'danger',
  missing: 'danger',
  error: 'danger',
  unavailable: 'danger',
  failed: 'danger',
  disconnected: 'danger',
  offline: 'danger',
  'n/a': 'neutral',
  planned: 'neutral',
  archived: 'neutral',
  stopped: 'neutral',
});

/**
 * Status glyph families (UI final round): the pill / chart glyph says what
 * KIND of state it is, independent of the tone color — a running item must
 * not wear the "done" check mark. Every canonical status belongs to exactly
 * one family; `kyberion-ui.css` is generated from this map and the vanilla
 * renderer's `KB_STATUS_GLYPHS` (charts.js) is pinned to it by test.
 */
export type KbStatusFamily =
  'done' | 'running' | 'waiting' | 'paused' | 'degraded' | 'failed' | 'idle';

/** One glyph per family (plain characters; the CSS generator escapes them). */
export const KB_STATUS_FAMILY_GLYPHS: Readonly<Record<KbStatusFamily, string>> = Object.freeze({
  done: '\u2713',
  running: '\u25D0',
  waiting: '!',
  paused: '\u2016',
  degraded: '\u25B2',
  failed: '\u2715',
  idle: '\u25CB',
});

export const KB_STATUS_FAMILIES: Readonly<Record<KbStatus, KbStatusFamily>> = Object.freeze({
  ready: 'done',
  fully_automatable: 'done',
  connected: 'done',
  available: 'done',
  done: 'done',
  completed: 'done',
  recovered: 'done',
  running: 'running',
  active: 'running',
  connecting: 'running',
  working: 'running',
  busy: 'running',
  distilling: 'running',
  review: 'waiting',
  needs_clarification: 'waiting',
  needs_external_assets: 'waiting',
  needs_assets: 'waiting',
  needs_setup: 'waiting',
  missing_runtime_prerequisites: 'waiting',
  needs_runtime_prerequisites: 'waiting',
  pending: 'waiting',
  paused: 'paused',
  degraded: 'degraded',
  fallback: 'degraded',
  stale: 'degraded',
  blocked: 'failed',
  missing: 'failed',
  error: 'failed',
  unavailable: 'failed',
  failed: 'failed',
  disconnected: 'failed',
  offline: 'failed',
  'n/a': 'idle',
  planned: 'idle',
  archived: 'idle',
  stopped: 'idle',
});

export interface KbAction {
  id: string;
  payload?: Record<string, unknown>;
}

/**
 * A labelled link or action; exactly one of `href` / `action`. `action` is
 * either a full `{ id, payload? }` or just the action id (dispatched to the
 * host's `onAction` without a payload).
 */
export type KbActionRef = {
  label: string;
  variant?: KbButtonVariant;
  disabled?: boolean;
} & ({ href: string; action?: never } | { action: KbAction | string; href?: never });

export interface KbNavItem {
  id: string;
  label: string;
  hint?: string;
  href: string;
  icon?: string;
  active?: boolean;
}

// ---------------------------------------------------------------------------
// Per-component props
// ---------------------------------------------------------------------------

export interface KbAppShellProps {
  density?: KbDensity;
  theme?: 'system' | 'light' | 'dark';
  role?: KbSurfaceRole;
}

export interface KbPageHeaderProps {
  title: string;
  subtitle?: string;
  role_badge?: { label: string; tone?: KbTone; role?: KbSurfaceRole };
  actions?: KbActionRef[];
}

/** `ui:nav-rail` brand slot: product / surface name, optional subtitle and logo image. */
export interface KbNavBrand {
  name: string;
  subtitle?: string;
  /** http(s) / same-origin image URL; without it a token-colored mark is drawn. */
  logo_url?: string;
}

/**
 * `ui:nav-rail` context slot (tenant / workspace the viewer is looking at).
 * With `options` + `action` it is a switcher: choosing an option dispatches
 * `action` with `{ value }` merged into its payload. With only `action` the
 * block is a button dispatching `action`; with only `href` it is a link.
 */
export interface KbNavContext {
  label: string;
  detail?: string;
  /** Accessible name of the switch control / option list. */
  switch_label?: string;
  href?: string;
  action?: KbAction;
  options?: Array<{ value: string; label: string; selected?: boolean }>;
}

export interface KbNavRailProps {
  label?: string;
  brand?: KbNavBrand;
  context?: KbNavContext;
  items: KbNavItem[];
  footer_items?: KbNavItem[];
}

export interface KbTabsProps {
  items: Array<{ id: string; label: string; count?: number; href?: string }>;
  active?: string;
  overflow?: 'wrap' | 'menu';
  /** `primary` (default) = underlined page tabs; `secondary` = pill-style sub-navigation. */
  variant?: 'primary' | 'secondary';
}

export interface KbStackProps {
  gap?: KbGap;
  direction?: 'vertical' | 'horizontal';
  align?: 'start' | 'center' | 'end' | 'stretch';
  wrap?: boolean;
}

export interface KbGridProps {
  gap?: KbGap;
  columns?: number;
  min_column_width?: 'xs' | 'sm' | 'md' | 'lg';
}

export interface KbSectionProps {
  title?: string;
  description?: string;
  tone?: KbTone;
  actions?: KbActionRef[];
}

export interface KbNextActionProps {
  eyebrow?: string;
  title: string;
  reason?: string;
  /** Required unless `state` is `loading` or `empty`. */
  primary?: KbActionRef;
  secondary?: KbActionRef;
  state?: 'ready' | 'loading' | 'empty';
}

export interface KbMetricProps {
  label: string;
  value: string | number;
  unit?: string;
  delta?: string;
  trend?: 'up' | 'down' | 'flat';
  tone?: KbTone;
  description?: string;
}

export interface KbKvProps {
  items: Array<{ label: string; value: string | number | boolean; mono?: boolean }>;
}

export interface KbTableColumn {
  key: string;
  label: string;
  align?: 'start' | 'center' | 'end';
  mono?: boolean;
  width?: string;
}

/** `ui:table` rich cell: a title with an optional mono id line (and link). */
export interface KbTableTitleCell {
  title: string;
  id?: string;
  href?: string;
}

/** `ui:table` rich cell: a status pill. */
export interface KbTableStatusCell {
  status: KbStatus;
  label?: string;
  domain?: KbStatusDomain;
}

/** `ui:table` rich cell: a badge. */
export interface KbTableBadgeCell {
  badge: string;
  tone?: KbTone;
}

export type KbTableScalar = string | number | boolean | null;
export type KbTableCell = KbTableScalar | KbTableTitleCell | KbTableStatusCell | KbTableBadgeCell;

export interface KbTableProps {
  caption?: string;
  columns: KbTableColumn[];
  rows: Array<Record<string, KbTableCell>>;
  row_href_key?: string;
  empty?: string;
}

export interface KbListItem {
  title: string;
  meta?: string;
  status?: KbStatus;
  /** Visible text of the status pill (default: the localized status label). */
  status_label?: string;
  /** 0–100: drawn as a small meter under the title, with accessible text. */
  progress?: number;
  href?: string;
}

export interface KbListProps {
  items: KbListItem[];
  variant?: 'plain' | 'timeline';
}

export interface KbTextProps {
  text: string;
  variant?: 'body' | 'muted' | 'caption' | 'mono' | 'title';
}

/** `ui:code`: a monospace, wrapping (`pre-wrap`) code / log block. */
export interface KbCodeProps {
  code: string;
  /** Language / format hint (shown as a label; no syntax highlighting). */
  language?: string;
  title?: string;
}

export interface KbStatusPillProps {
  status: KbStatus;
  domain?: KbStatusDomain;
  label?: string;
}

export interface KbBadgeProps {
  label: string;
  tone?: KbTone;
  role?: KbSurfaceRole;
}

export interface KbCalloutProps {
  tone: KbCalloutTone;
  title: string;
  body?: string;
  action?: KbActionRef;
}

export interface KbEmptyStateProps {
  title: string;
  body?: string;
  action?: KbActionRef;
}

export interface KbSkeletonProps {
  lines?: number;
  shape?: 'text' | 'card' | 'table';
}

export type KbButtonProps = {
  label: string;
  variant?: KbButtonVariant;
  disabled?: boolean;
  /** Native `title` attribute (tooltip / accessible description). */
  title?: string;
  /** Link target, only meaningful with `href`. `_blank` always gets `rel="noopener"`. */
  target?: '_blank' | '_self';
} & ({ href: string; action?: never } | { action: KbAction; href?: never });

export interface KbDisclosureProps {
  summary: string;
  open?: boolean;
}

/**
 * Action ids `ui:display-controls` dispatches (payload `{ value }`). The
 * component never persists anything: the host stores the choice (the
 * front-desk surfaces use `kyberion.ui.theme` / `kyberion.ui.locale`).
 */
export const KB_DISPLAY_CONTROLS_ACTIONS = Object.freeze({
  theme: 'display.theme',
  locale: 'display.locale',
} as const);

/** `ui:display-controls`: theme (system / light / dark) segmented control + language select. */
export interface KbDisplayControlsProps {
  theme?: 'system' | 'light' | 'dark';
  locale?: string;
  /**
   * Language choices (label in its own language). Default: Japanese and
   * English, each shown by its endonym (`Intl.DisplayNames`).
   */
  locales?: Array<{ value: string; label: string }>;
}

export interface KyberionBasePropsByType {
  'ui:app-shell': KbAppShellProps;
  'ui:page-header': KbPageHeaderProps;
  'ui:nav-rail': KbNavRailProps;
  'ui:tabs': KbTabsProps;
  'ui:stack': KbStackProps;
  'ui:grid': KbGridProps;
  'ui:section': KbSectionProps;
  'ui:next-action': KbNextActionProps;
  'ui:metric': KbMetricProps;
  'ui:kv': KbKvProps;
  'ui:table': KbTableProps;
  'ui:list': KbListProps;
  'ui:text': KbTextProps;
  'ui:code': KbCodeProps;
  'ui:status-pill': KbStatusPillProps;
  'ui:badge': KbBadgeProps;
  'ui:callout': KbCalloutProps;
  'ui:empty-state': KbEmptyStateProps;
  'ui:skeleton': KbSkeletonProps;
  'ui:button': KbButtonProps;
  'ui:disclosure': KbDisclosureProps;
  'ui:display-controls': KbDisplayControlsProps;
  'ui:settings-group': KbSettingsGroupProps;
  'ui:setting-row': KbSettingRowProps;
  'ui:switch': KbSwitchProps;
  'ui:checkbox': KbCheckboxProps;
  'ui:select': KbSelectProps;
  'ui:radio-group': KbRadioGroupProps;
  'ui:segmented': KbSegmentedProps;
  'ui:text-field': KbTextFieldProps;
  'ui:textarea': KbTextareaProps;
  'ui:slider': KbSliderProps;
  'ui:integration-item': KbIntegrationItemProps;
  'ui:save-bar': KbSaveBarProps;
  'ui:file-drop': KbFileDropProps;
  'ui:camera-capture': KbCameraCaptureProps;
  'ui:avatar-picker': KbAvatarPickerProps;
  'ui:secret-field': KbSecretFieldProps;
  'ui:bar-chart': KbBarChartProps;
  'ui:line-chart': KbLineChartProps;
  'ui:donut': KbDonutProps;
  'ui:sparkline': KbSparklineProps;
  'ui:heatmap': KbHeatmapProps;
  'ui:meter': KbMeterProps;
  'ui:sequence': KbSequenceProps;
  'ui:flow': KbFlowProps;
  'ui:stat-list': KbStatListProps;
  // PA-02 voice
  'ui:voice-input': KbVoiceInputProps;
  'ui:voice-state': KbVoiceStateProps;
  // PA-01 pads
  'ui:toolbar': KbToolbarProps;
  'ui:dialog': KbDialogProps;
  'ui:drawing-palette': KbDrawingPaletteProps;
  'ui:sketch-board': KbSketchBoardProps;
}

// ---------------------------------------------------------------------------
// UI-01c settings & forms (SURFACE_UI_UNIFICATION_PLAN §3.3)
// ---------------------------------------------------------------------------
//
// Interaction contract: controls are controlled by `value`; every edit is
// reported as `onAction('field.change', { name, value })` (the caller owns the
// data model). Files, captured images and secret values are NEVER props: the
// schema has no slot for file contents or a secret `value`, and the renderers
// hand those only to `onAction` at runtime (see `KB_FORM_ACTIONS`).

/** Action ids the form components dispatch when the props give no explicit `action`. */
export const KB_FORM_ACTIONS = Object.freeze({
  /** `{ name, value }` — every controlled field edit (never for `ui:secret-field`). */
  fieldChange: 'field.change',
  /** `{ name, files: File[], rejected: [{ name, size, reason }] }` */
  filesAdd: 'file.add',
  /** `{ name, file_id }` — remove / cancel one `files[]` entry. */
  fileRemove: 'file.remove',
  /** `{ name, file: File }` — confirmed camera photo. */
  cameraCapture: 'camera.capture',
  /** `{ name }` */
  cameraCancel: 'camera.cancel',
  /** `{ name, file: File, source: 'upload' | 'camera' }` — square-cropped image. */
  avatarChange: 'avatar.change',
  /** `{ name }` */
  avatarRemove: 'avatar.remove',
} as const);

export interface KbFieldBase {
  /** Field key reported in `field.change` / action payloads. */
  name: string;
  label: string;
  /** Visually hide the label (it stays the accessible name), e.g. inside a `ui:setting-row`. */
  hide_label?: boolean;
  help?: string;
  error?: string;
  required?: boolean;
  disabled?: boolean;
}

export interface KbFieldOption {
  value: string;
  label: string;
  description?: string;
  disabled?: boolean;
}

export interface KbSettingsGroupProps {
  title: string;
  description?: string;
}

export interface KbSettingRowProps {
  label: string;
  description?: string;
  /** Visual separation for dangerous settings (delete, reset). */
  tone?: 'neutral' | 'danger';
}

export interface KbSwitchProps extends KbFieldBase {
  value?: boolean;
}

export interface KbCheckboxProps extends KbFieldBase {
  value?: boolean;
}

export interface KbSelectProps extends KbFieldBase {
  value?: string;
  options: KbFieldOption[];
  placeholder?: string;
}

export interface KbRadioGroupProps extends KbFieldBase {
  value?: string;
  options: KbFieldOption[];
  direction?: 'vertical' | 'horizontal';
}

export interface KbSegmentedProps extends KbFieldBase {
  value?: string;
  options: KbFieldOption[];
}

export interface KbTextFieldProps extends KbFieldBase {
  value?: string | number;
  type?: 'text' | 'email' | 'url' | 'number' | 'search';
  placeholder?: string;
  maxlength?: number;
  min?: number;
  max?: number;
  step?: number;
  readonly?: boolean;
}

export interface KbTextareaProps extends KbFieldBase {
  value?: string;
  placeholder?: string;
  maxlength?: number;
  rows?: number;
  readonly?: boolean;
}

export interface KbSliderProps extends KbFieldBase {
  value?: number;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
}

export type KbIntegrationState = 'connected' | 'needs_reauth' | 'disconnected' | 'error';

export interface KbIntegrationItemProps {
  title: string;
  state: KbIntegrationState;
  description?: string;
  /** Account / scope detail, e.g. the connected address. */
  detail?: string;
  icon?: string;
  actions?: KbActionRef[];
}

export interface KbSaveBarProps {
  state: 'clean' | 'dirty' | 'saving' | 'saved' | 'error';
  message?: string;
  save_action: KbAction;
  discard_action?: KbAction;
  save_label?: string;
  discard_label?: string;
}

/** One selected file's metadata — never its contents. */
export interface KbFileEntry {
  id: string;
  name: string;
  size?: number;
  status: 'queued' | 'uploading' | 'done' | 'error';
  /** 0–100 while `uploading`. */
  progress?: number;
  error?: string;
}

export interface KbFileDropProps extends KbFieldBase {
  description?: string;
  /** `<input accept>` list: extensions (`.pdf`) and MIME types (`image/*`). */
  accept?: string;
  multiple?: boolean;
  max_bytes?: number;
  max_files?: number;
  files?: KbFileEntry[];
  action?: KbAction;
  remove_action?: KbAction;
}

export interface KbCameraCaptureProps extends KbFieldBase {
  description?: string;
  facing?: 'user' | 'environment';
  aspect?: 'square' | 'landscape';
  action?: KbAction;
  cancel_action?: KbAction;
}

export interface KbAvatarPickerProps extends KbFieldBase {
  /** Current image (http(s) / same-origin URL); never inline data. */
  image_url?: string;
  initials?: string;
  shape?: 'circle' | 'square';
  allow_camera?: boolean;
  removable?: boolean;
  action?: KbAction;
  remove_action?: KbAction;
}

/**
 * Secret input (API tokens). There is deliberately no `value`: a stored
 * secret is never sent back to the page — only `configured` and `last4`.
 * Submit dispatches `action` with `{ name, service_id?, secret_key?, value }`.
 */
export interface KbSecretFieldProps extends KbFieldBase {
  action: KbAction;
  remove_action?: KbAction;
  configured?: boolean;
  last4?: string;
  placeholder?: string;
  service_id?: string;
  secret_key?: string;
  /**
   * Host-reported outcome of the last submit. The field shows "sending" after
   * a submit until the host sets `saved` or `error` — it never reports success
   * on its own. `error` reopens the input.
   */
  status?: 'idle' | 'pending' | 'error' | 'saved';
  /** Host-localized reason shown instead of the generic error text (status `error`). */
  status_error?: string;
}

// ---------------------------------------------------------------------------
// UI-01b charts & visualisation (SURFACE_UI_UNIFICATION_PLAN §3.2)
// ---------------------------------------------------------------------------
//
// Layout (scales, ticks, stacking, DAG layering, sequence ordering) lives once
// in `libs/shared-ui/vanilla/charts.js`; both renderers draw its vnode tree.
// Colors come only from the `--kb-ui-viz-*` tokens (categorical slots 1..8,
// sequential / diverging steps 1..5). More than 8 series are never cycled:
// only the first 8 are drawn (a donut folds the rest into "Other").

interface KbChartCommonProps {
  title?: string;
  description?: string;
  density?: KbDensity;
  /** Override for the localized "no data" empty state. */
  empty?: string;
}

export interface KbChartDatum {
  label: string;
  value: number | null;
}

export interface KbBarChartProps extends KbChartCommonProps {
  categories?: string[];
  series?: Array<{ name: string; values: Array<number | null> }>;
  /** Single-series shorthand (chronos `display:bar-chart` compatible). */
  data?: KbChartDatum[];
  orientation?: 'vertical' | 'horizontal';
  stacked?: boolean;
  unit?: string;
  show_values?: boolean;
}

export interface KbLineChartProps extends KbChartCommonProps {
  series: Array<{ name: string; points: Array<{ x: string | number; y: number | null }> }>;
  area?: boolean;
  y_unit?: string;
}

export interface KbDonutProps extends KbChartCommonProps {
  segments?: KbChartDatum[];
  /** chronos `display:donut` shorthand. */
  data?: KbChartDatum[];
  center_label?: string;
  center_value?: string | number;
  unit?: string;
}

export interface KbSparklineProps {
  points: Array<number | null>;
  label?: string;
  tone?: KbTone;
  unit?: string;
  show_value?: boolean;
  empty?: string;
}

export interface KbHeatmapProps extends KbChartCommonProps {
  rows: string[];
  columns: string[];
  values: Array<Array<number | null>>;
  unit?: string;
  scale?: 'sequential' | 'diverging';
  midpoint?: number;
  show_values?: boolean;
}

export interface KbMeterProps {
  label?: string;
  value: number | null;
  /** Default 100. */
  max?: number;
  unit?: string;
  thresholds?: Array<{ value: number; tone: 'success' | 'warning' | 'danger' }>;
  /**
   * `lower_is_better` (default; usage against a limit: "Near the limit",
   * "Over the limit") or `higher_is_better` (rates such as completion:
   * "On track", "Below target"). Only the state words change; the tone is
   * always the highest threshold at or below `value`.
   */
  direction?: 'higher_is_better' | 'lower_is_better';
  description?: string;
  empty?: string;
}

export interface KbSequenceProps extends KbChartCommonProps {
  participants: Array<string | { id: string; label?: string }>;
  messages: Array<{
    from: string;
    to: string;
    label: string;
    at?: string | number;
    status?: KbStatus;
    /** `reply` draws a dashed arrow. */
    kind?: 'call' | 'reply' | 'note';
  }>;
}

export interface KbFlowProps extends KbChartCommonProps {
  nodes: Array<{ id: string; label: string; stage?: string; status?: KbStatus; meta?: string }>;
  edges?: Array<{ from: string; to: string; label?: string }>;
  stages?: Array<string | { id: string; label?: string }>;
}

export interface KbStatListProps {
  title?: string;
  density?: KbDensity;
  empty?: string;
  items: Array<{ label: string; value: string | number; unit?: string; hint?: string }>;
}

// ---------------------------------------------------------------------------
// PA-02 voice (PADS_A2UI_AND_AVATAR_PLAN_2026-09-23 §3)
// ---------------------------------------------------------------------------
//
// `ui:voice-input` owns its microphone state; the mic opens only from a user
// action. Recorded audio (File) and transcripts reach the host only in the
// `onAction` payloads below — never in props.

/** Action ids `ui:voice-input` dispatches unless `actions.<event>` overrides them. */
export const KB_VOICE_ACTIONS = Object.freeze({
  /** `{ name, state }` — every internal state change (`KbVoiceInputState`). */
  state: 'voice.state',
  /** `{ name, text, final: boolean }` — dictation interim / final text. */
  transcript: 'voice.transcript',
  /** `{ name, file: File, duration_ms, final: boolean }` — record mode (one per chunk with `chunk_ms`). */
  recording: 'voice.recording',
  /** `{ name, code: KbVoiceErrorCode }` */
  error: 'voice.error',
} as const);

export type KbVoiceInputState =
  'idle' | 'requesting' | 'listening' | 'recording' | 'processing' | 'error' | 'unsupported';

export type KbVoiceErrorCode =
  'permission_denied' | 'not_supported' | 'no_speech' | 'network' | 'aborted' | 'unknown';

export interface KbVoiceInputProps {
  /** Field key reported in every voice action payload. */
  name: string;
  label: string;
  hide_label?: boolean;
  help?: string;
  disabled?: boolean;
  /** `dictation` (default): Web Speech recognition. `record`: MediaRecorder audio. */
  mode?: 'dictation' | 'record';
  /** BCP-47 recognition language; default from the render locale (en → en-US, ja → ja-JP). */
  lang?: string;
  continuous?: boolean;
  /** Hold the button (or Space) to talk; otherwise click toggles. */
  push_to_talk?: boolean;
  /** Live input-level meter (default true). */
  show_level?: boolean;
  /** Dictation: show the interim transcript line. */
  show_transcript?: boolean;
  /** Record mode: deliver a chunk every N ms (default: one file on stop). */
  chunk_ms?: number;
  /** Stop automatically after N seconds. */
  max_seconds?: number;
  /** Host-controlled state while idle: `transcribing` (processing) or `error`. */
  status?: 'idle' | 'transcribing' | 'error';
  /** Host-localized reason shown with `status: 'error'`. */
  status_error?: string;
  /** Override the dispatched action per event. */
  actions?: {
    state?: KbAction;
    transcript?: KbAction;
    recording?: KbAction;
    error?: KbAction;
  };
}

export type KbVoiceStateValue = 'idle' | 'listening' | 'thinking' | 'speaking' | 'muted' | 'error';

/** Display-only conversation state (reused by the talking avatar). */
export interface KbVoiceStateProps {
  state: KbVoiceStateValue;
  /** Overrides the localized default label. */
  label?: string;
  /** Host-driven loudness 0..1 (e.g. TTS output); drives the bar heights. */
  level?: number;
  variant?: 'bars' | 'orb' | 'dot';
  size?: 'sm' | 'md' | 'lg';
  /** Show the label visibly (default true; it always stays the accessible text). */
  show_label?: boolean;
}

// ---------------------------------------------------------------------------
// PA-01 pads (PADS_A2UI_AND_AVATAR_PLAN_2026-09-23 §3)
// ---------------------------------------------------------------------------
//
// `ui:toolbar`, `ui:dialog` and `ui:drawing-palette` are controlled (the host
// passes `pressed` / `open` / `tool`...). `ui:sketch-board` owns its drawing
// state and hands the host a controller in `drawing.ready`. Files (toolbar
// file items, dropped background images) reach the host only as onAction
// payloads — never props.

/** Action ids `ui:toolbar` dispatches when an item has no explicit `action`. */
export const KB_TOOLBAR_ACTIONS = Object.freeze({
  /** `{ id }` — a `button` item. */
  click: 'toolbar.click',
  /** `{ id, pressed: boolean }` — a `toggle` item (the new value). */
  toggle: 'toolbar.toggle',
  /** `{ id, files: File[] }` — a `file` item. */
  files: 'toolbar.files',
} as const);

/** Action ids `ui:dialog` dispatches unless `action` / `cancel_action` override them. */
export const KB_DIALOG_ACTIONS = Object.freeze({
  /** `{ choice?: string, value?: string }` — confirm button, a choice, or Enter in the input. */
  confirm: 'dialog.confirm',
  /** `{}` — cancel button or Escape. */
  cancel: 'dialog.cancel',
} as const);

/** Action ids `ui:drawing-palette` / `ui:sketch-board` dispatch. */
export const KB_DRAWING_ACTIONS = Object.freeze({
  /** Palette: `{ name, tool? | color? | width? }`; sketch board: `{ name, dirty, strokes }`. */
  change: 'drawing.change',
  /** `{ name }` (palette). */
  undo: 'drawing.undo',
  /** `{ name }` (palette). */
  clear: 'drawing.clear',
  /** `{ name, controller: KbSketchController }` (sketch board, on mount). */
  ready: 'drawing.ready',
  /** `{ name, file: File }` — an image dropped / pasted as background (sketch board). */
  background: 'drawing.background',
} as const);

export const KB_DRAWING_TOOLS = [
  'pen',
  'highlighter',
  'rect',
  'ellipse',
  'line',
  'arrow',
  'text',
  'eraser',
] as const;

export type KbDrawingTool = (typeof KB_DRAWING_TOOLS)[number];

export interface KbToolbarItem {
  type: 'button' | 'toggle' | 'file' | 'separator' | 'spacer' | 'status';
  /** Required for button / toggle / file; reported in the action payload. */
  id?: string;
  /** Required for button / toggle / file (stays the accessible name with `hide_label`). */
  label?: string;
  /** Short glyph / emoji shown before the label (decorative). */
  icon?: string;
  /** Icon-only button: the label becomes `aria-label` + `title`. */
  hide_label?: boolean;
  variant?: KbButtonVariant;
  /** Toggle state (controlled). */
  pressed?: boolean;
  disabled?: boolean;
  action?: KbAction;
  /** File item: `<input accept>` list. */
  accept?: string;
  multiple?: boolean;
  /** Status item text (`role=status`, polite). Required for status. */
  text?: string;
  tone?: KbTone;
}

/** `ui:toolbar`: WAI-ARIA toolbar (roving tabindex, arrow keys); wraps on narrow widths. */
export interface KbToolbarProps {
  /** Accessible name of the toolbar. */
  label: string;
  items: KbToolbarItem[];
  sticky?: boolean;
  density?: KbDensity;
}

/** `ui:dialog`: modal confirm / prompt / multi-choice (replaces confirm() / prompt()). */
export interface KbDialogProps {
  open: boolean;
  title: string;
  message?: string;
  /** `danger` renders an `alertdialog` with a danger confirm button. */
  tone?: 'neutral' | 'danger';
  input?: {
    name: string;
    label: string;
    placeholder?: string;
    value?: string;
    multiline?: boolean;
  };
  /** Replaces the Cancel / Confirm pair (e.g. save / discard / cancel). */
  choices?: Array<{ id: string; label: string; variant?: KbButtonVariant }>;
  confirm_label?: string;
  cancel_label?: string;
  action?: KbAction;
  cancel_action?: KbAction;
}

/** `ui:drawing-palette`: controlled tool / color / width picker. */
export interface KbDrawingPaletteProps {
  name: string;
  label: string;
  tools?: KbDrawingTool[];
  tool?: KbDrawingTool;
  /** `#rrggbb` swatches (default: a set readable on dark and light canvases). */
  colors?: string[];
  color?: string;
  allow_custom_color?: boolean;
  width?: number;
  min_width?: number;
  max_width?: number;
  can_undo?: boolean;
  show_clear?: boolean;
  orientation?: 'horizontal' | 'vertical';
}

/** `ui:sketch-board`: stateful palette + canvas (pointer drawing, undo, PNG export). */
export interface KbSketchBoardProps {
  name: string;
  label: string;
  tools?: KbDrawingTool[];
  colors?: string[];
  default_tool?: KbDrawingTool;
  default_color?: string;
  default_width?: number;
  min_width?: number;
  max_width?: number;
  /** Colour input next to the swatches (default true). */
  allow_custom_color?: boolean;
  /** Canvas pixels (default 1280 × 720). */
  canvas_width?: number;
  canvas_height?: number;
  background?: 'dark' | 'light' | 'transparent';
  /** http(s) / same-origin image; never inline data. */
  background_image_url?: string;
  /** Drop / paste an image as the background (reported as `drawing.background`). */
  accept_image_drop?: boolean;
  /** Undo depth (default 40); older strokes are flattened. */
  max_undo?: number;
  show_download?: boolean;
}

/** What `drawing.ready` hands the host (runtime object, never serialized). */
export interface KbSketchController {
  toBlob(): Promise<Blob>;
  isEmpty(): boolean;
  clear(): void;
  undo(): void;
  setBackgroundImage(source: Blob | string | null): Promise<boolean>;
}

// ---------------------------------------------------------------------------
// Resolution & validation
// ---------------------------------------------------------------------------

const CATALOG_TYPE_SET: ReadonlySet<string> = new Set(A2UI_BASE_COMPONENT_TYPES);

export function isKyberionBaseComponentType(type: string): type is KyberionBaseComponentType {
  return CATALOG_TYPE_SET.has(type);
}

/** Resolve a component type (or legacy alias) to its catalog type; `null` when outside the catalog. */
export function resolveKyberionBaseType(type: string): KyberionBaseComponentType | null {
  if (isKyberionBaseComponentType(type)) return type;
  return Object.prototype.hasOwnProperty.call(A2UI_BASE_ALIASES, type)
    ? A2UI_BASE_ALIASES[type as KyberionBaseAlias]
    : null;
}

let catalogValidators: Map<KyberionBaseComponentType, ValidateFunction> | null = null;

function loadCatalogValidators(): Map<KyberionBaseComponentType, ValidateFunction> {
  if (catalogValidators) return catalogValidators;
  const ajv = createAjv2020({ allowUnionTypes: true });
  compileSchema(
    pathResolver.knowledge('product/schemas/a2ui-catalog-kyberion-base.schema.json'),
    ajv
  );
  const validators = new Map<KyberionBaseComponentType, ValidateFunction>();
  for (const type of A2UI_BASE_COMPONENT_TYPES) {
    const validate = ajv.getSchema(`${A2UI_BASE_CATALOG_SCHEMA_ID}#/$defs/props:${type}`);
    if (!validate)
      throw new Error(`A2UI catalog ${A2UI_BASE_CATALOG_ID} has no schema for ${type}.`);
    validators.set(type, validate);
  }
  catalogValidators = validators;
  return validators;
}

function formatAjvErrors(validate: ValidateFunction): string {
  return (validate.errors || [])
    .slice(0, 5)
    .map((error) => {
      const where = error.instancePath || '(props)';
      const extra =
        error.keyword === 'additionalProperties'
          ? ` (${String((error.params as { additionalProperty?: string }).additionalProperty)})`
          : error.keyword === 'enum'
            ? ` (${((error.params as { allowedValues?: unknown[] }).allowedValues || []).join('|')})`
            : '';
      return `${where} ${error.message ?? error.keyword}${extra}`;
    })
    .join('; ');
}

/**
 * Validate props for a `ui:*` catalog component. Throws with a readable reason
 * on violation. Types outside the catalog (including legacy aliases) are not
 * checked here — callers decide their policy.
 */
export function validateA2UIComponentProps<T extends KyberionBaseComponentType>(
  type: T,
  props: unknown
): KyberionBasePropsByType[T] {
  if (!isKyberionBaseComponentType(type)) {
    throw new Error(
      `A2UI component type ${String(type)} is not in catalog ${A2UI_BASE_CATALOG_ID}.`
    );
  }
  const validate = loadCatalogValidators().get(type);
  if (!validate) throw new Error(`A2UI catalog ${A2UI_BASE_CATALOG_ID} has no schema for ${type}.`);
  if (!validate(props)) {
    throw new Error(`A2UI ${type} props are invalid: ${formatAjvErrors(validate)}.`);
  }
  return props as KyberionBasePropsByType[T];
}
