export {
  activateApplication,
  detectFocusedInput,
  keystrokeText,
  pasteText,
  pressKey,
  pressKeyCode,
  toggleDictation,
  clickAt,
  rightClickAt,
  moveMouse,
  toAppleScriptString,
  scrollAt,
  dragFrom,
  runAppleScript,
  getScreenSize,
  getWindowList,
  quitApplication,
  systemNotify,
  clipboardRead,
  clipboardWrite,
  takeScreenshot,
} from './apple-event-bridge.js';
export {
  listKnownAppCapabilities,
  listTerminalTargets,
  listChromeTabs,
  activateChromeTabByTitle,
  activateChromeTabByUrl,
  closeChromeTabByTitle,
  closeChromeTabByUrl,
  emptyFinderTrash,
  revealFinderPath,
  openFinderPath,
} from './os-app-adapters.js';
export { terminalBridge } from './terminal-bridge.js';
export type { FocusedInputState } from './apple-event-bridge.js';
