/**
 * Event-sourced worker state restore contract (KD-03).
 *
 * Promotes the KC-02 `worker-event-stream.ts` observation stream (record/replay)
 * into **state reconstruction**. The KC-02 stream answers "what happened"; this
 * module answers "what state am I in after a process restart", reconstructed
 * *purely* from an append-only journal. It is the worker-granularity precedent
 * for MO-06 (durable resume of the in-memory `MissionCoordinationBus`); that bus
 * stays untouched here.
 *
 * Modeled on kimi-code `wire/` (op/model + restore + versioned migration), with
 * Kyberion vocabulary and invariants:
 *
 *  1. **op/model contract** — restorable state (KD-01 goal, delegation ledger /
 *     active background tasks, pending-approval references) is declared via
 *     {@link EventSourcingKernel.defineModel} + {@link
 *     EventSourcingKernel.defineOp}. Every `apply` is a **pure** function that
 *     returns the *same reference* when nothing changes. Non-deterministic
 *     values (ids, timestamps) are generated by the live service and carried in
 *     the op payload — never invented inside `apply`.
 *  2. **restore contract** — validate → versioned migration ({@link
 *     CURRENT_JOURNAL_VERSION}, with a v1→v2 migration in {@link
 *     JOURNAL_MIGRATIONS}) → **silent** replay → ordered `onDidRestore` hooks.
 *     Restore runs inside {@link runInRestoreMode}; the emission seam {@link
 *     deliverOneShotReminder} throws if invoked while restoring, so no
 *     UI/notification, LLM call, or tool execution can happen during replay —
 *     enforced structurally, not by convention.
 *  3. **CQRS separation** — the JSONL journal (secure-io) is authoritative. The
 *     derived goal/delegation summary index ({@link
 *     WorkerStateJournal.summary}) is rebuildable: on corruption it is wiped and
 *     reprojected from the journal.
 *  4. **fork/clear hygiene** — a mission fork or goal cancel records exactly one
 *     one-shot reminder (KD-01's {@link GOAL_CANCEL_SYSTEM_REMINDER} / a fork
 *     variant) telling the model to ignore prior reminders. Replay reconstructs
 *     the *pending* reminder deterministically but never re-delivers it —
 *     delivery only ever happens via a live `reminder.consume` append.
 *  5. **KD-01 integration** — after restore, an `active` goal comes back
 *     `paused` ({@link demoteActiveOnResume}); the restored goal feeds
 *     `runGoalDrivenLoop({ resumeFrom })` unchanged.
 */

import { z } from 'zod';
import { logger } from './core.js';
import { pathResolver } from './path-resolver.js';
import {
  safeAppendFileSync,
  safeExistsSync,
  safeMkdir,
  safeReadFile,
  safeRmSync,
  safeWriteFile,
} from './secure-io.js';
import {
  demoteActiveOnResume,
  GOAL_CANCEL_SYSTEM_REMINDER,
  GOAL_STATES,
  type GoalRuntimeState,
  type GoalState,
} from './worker-goal.js';

// ---------------------------------------------------------------------------
// Generic event-sourcing kernel (op/model contract)
// ---------------------------------------------------------------------------

/** Non-deterministic values carried by the live service, exposed to `apply`. */
export interface OpMeta {
  seq: number;
  ts: string;
}

/**
 * A pure reducer for one op. It MUST return `state` unchanged (same reference)
 * when the op is a no-op, and MUST NOT generate ids/timestamps or perform I/O.
 */
export type OpApply<S, P> = (state: S, payload: P, meta: OpMeta) => S;

export interface ModelDefinition<S> {
  readonly name: string;
  readonly initial: () => S;
}

export interface OpDefinition<S = unknown, P = unknown> {
  readonly name: string;
  readonly model: string;
  readonly schema: z.ZodType<P>;
  readonly apply: OpApply<S, P>;
}

/**
 * Minimal op/model registry + pure projector. Unknown ops and torn journal
 * lines are tolerated (skipped) so a partially-written or forward-versioned
 * record can never poison replay of the rest.
 */
export class EventSourcingKernel {
  private readonly models = new Map<string, ModelDefinition<unknown>>();
  private readonly ops = new Map<string, OpDefinition>();

  defineModel<S>(name: string, initial: () => S): ModelDefinition<S> {
    if (this.models.has(name))
      throw new Error(`[worker-state-journal] model "${name}" already defined`);
    const def: ModelDefinition<S> = { name, initial };
    this.models.set(name, def as ModelDefinition<unknown>);
    return def;
  }

  defineOp<S, P>(
    name: string,
    def: { model: ModelDefinition<S>; schema: z.ZodType<P>; apply: OpApply<S, P> }
  ): OpDefinition<S, P> {
    if (this.ops.has(name)) throw new Error(`[worker-state-journal] op "${name}" already defined`);
    if (!this.models.has(def.model.name)) {
      throw new Error(
        `[worker-state-journal] op "${name}" references unknown model "${def.model.name}"`
      );
    }
    const op: OpDefinition<S, P> = {
      name,
      model: def.model.name,
      schema: def.schema,
      apply: def.apply,
    };
    this.ops.set(name, op as OpDefinition);
    return op;
  }

  hasOp(name: string): boolean {
    return this.ops.has(name);
  }

  /** Validate a payload against its op schema (throws on an invalid contract). */
  validatePayload(opName: string, payload: unknown): unknown {
    const op = this.ops.get(opName);
    if (!op) throw new Error(`[worker-state-journal] unknown op "${opName}"`);
    return op.schema.parse(payload);
  }

  /**
   * Fold a stream of validated + migrated envelopes into a per-model state map.
   * Pure: no I/O, no clock, no emission. Callers wrap this in
   * {@link runInRestoreMode} during restore to structurally forbid side effects.
   */
  project(events: readonly JournalEventEnvelope[]): Map<string, unknown> {
    const states = new Map<string, unknown>();
    for (const [name, model] of this.models) states.set(name, model.initial());
    for (const event of events) {
      const op = this.ops.get(event.op);
      if (!op) continue; // unknown/forward op — tolerate
      let payload: unknown;
      try {
        payload = op.schema.parse(event.payload);
      } catch {
        continue; // a payload that no longer validates must not poison replay
      }
      const current = states.get(op.model);
      const next = op.apply(current, payload, { seq: event.seq, ts: event.ts });
      states.set(op.model, next);
    }
    return states;
  }
}

// ---------------------------------------------------------------------------
// Restore mode: structural "no side effects during replay" guard
// ---------------------------------------------------------------------------

let RESTORING = false;

/** True while a `restore()` (validate → migrate → replay → hooks) is running. */
export function isRestoring(): boolean {
  return RESTORING;
}

/**
 * Guard placed at every emission seam (notification / LLM / tool). Throws when
 * called during restore — this is how "no UI/LLM/tool during restore" is
 * enforced structurally rather than by convention.
 */
export function assertNotDuringRestore(seam: string): void {
  if (RESTORING) {
    throw new Error(
      `[worker-state-journal] "${seam}" is forbidden during restore: replay must not emit notifications, call the model, or execute tools`
    );
  }
}

/** Run `fn` with the restore guard armed; restores the prior flag afterwards. */
export function runInRestoreMode<T>(fn: () => T): T {
  const prev = RESTORING;
  RESTORING = true;
  try {
    return fn();
  } finally {
    RESTORING = prev;
  }
}

/**
 * THE one-shot-reminder emission seam. The live service calls this to actually
 * hand a fork/cancel reminder to the model, then appends a `reminder.consume`
 * op so the log records that it was delivered. Calling it during restore throws
 * (see {@link assertNotDuringRestore}), guaranteeing replay never re-delivers.
 */
export function deliverOneShotReminder(
  reminder: OneShotReminder,
  sink: (reminder: OneShotReminder) => void
): void {
  assertNotDuringRestore('deliverOneShotReminder');
  sink(reminder);
}

// ---------------------------------------------------------------------------
// Journal envelope + versioned migration
// ---------------------------------------------------------------------------

/** Current on-disk journal schema version. New records are written at this version. */
export const CURRENT_JOURNAL_VERSION = 2;

export const journalEventEnvelopeSchema = z
  .object({
    /** Schema version of THIS record (migrated up to {@link CURRENT_JOURNAL_VERSION}). */
    v: z.number().int().positive(),
    seq: z.number().int().nonnegative(),
    ts: z.string(),
    op: z.string(),
    payload: z.unknown(),
  })
  .strict();

export type JournalEventEnvelope = z.infer<typeof journalEventEnvelopeSchema>;

/** A migration transforms a record from version `v` to version `v + 1`. */
export type JournalMigration = (env: JournalEventEnvelope) => JournalEventEnvelope;

/**
 * Version-keyed migration chain. Keyed by the *source* version.
 *
 * v1→v2: early journals recorded a delegation's lifecycle under `state`; v2
 * renamed it to `status` (aligning with the KC-06 delegation record). The
 * migration renames the field silently, proving the migration chain works and
 * that a v1 journal remains readable alongside v2 records.
 */
export const JOURNAL_MIGRATIONS: Record<number, JournalMigration> = {
  1: (env) => {
    if (env.op === 'delegation.upsert' && env.payload && typeof env.payload === 'object') {
      const payload = env.payload as Record<string, unknown>;
      if ('state' in payload && !('status' in payload)) {
        const { state, ...rest } = payload;
        return { ...env, v: 2, payload: { ...rest, status: state } };
      }
    }
    return { ...env, v: 2 };
  },
};

/**
 * Migrate a single envelope up to {@link CURRENT_JOURNAL_VERSION}. Throws when a
 * step is missing (unknown intermediate version) or when the record is *newer*
 * than this code — a journal from the future must not be silently misread.
 */
export function migrateEnvelope(env: JournalEventEnvelope): JournalEventEnvelope {
  let current = env;
  if (current.v > CURRENT_JOURNAL_VERSION) {
    throw new Error(
      `[worker-state-journal] journal record v${current.v} is newer than supported v${CURRENT_JOURNAL_VERSION}`
    );
  }
  while (current.v < CURRENT_JOURNAL_VERSION) {
    const migrate = JOURNAL_MIGRATIONS[current.v];
    if (!migrate) throw new Error(`[worker-state-journal] no migration from journal v${current.v}`);
    const next = migrate(current);
    if (next.v <= current.v) {
      throw new Error(
        `[worker-state-journal] migration from v${current.v} did not advance the version`
      );
    }
    current = next;
  }
  return current;
}

// ---------------------------------------------------------------------------
// Worker restorable state: model + ops
// ---------------------------------------------------------------------------

export interface DelegationLedgerEntry {
  delegationId: string;
  owner: string;
  instruction: string;
  status: 'started' | 'completed' | 'failed';
  /** KC-06 background/async delegation — an "active background task" while `started`. */
  background?: boolean;
  createdAt: string;
  completedAt?: string;
  resultSummary?: string;
  error?: string;
  missionId?: string;
}

/** Pending approvals are held by *reference* only — never the approval payload. */
export interface PendingApprovalRef {
  requestId: string;
  channel?: string;
  requestedBy?: string;
}

export type OneShotReminderOrigin = 'goal_cancel' | 'mission_fork';

export interface OneShotReminder {
  id: string;
  text: string;
  origin: OneShotReminderOrigin;
}

/** The full worker state reconstructable from the journal. */
export interface WorkerRestorableState {
  goal: GoalRuntimeState | null;
  delegations: Record<string, DelegationLedgerEntry>;
  pendingApprovals: Record<string, PendingApprovalRef>;
  /** At most one undelivered fork/cancel reminder (see fork/clear hygiene). */
  pendingReminder: OneShotReminder | null;
}

function initialWorkerState(): WorkerRestorableState {
  return { goal: null, delegations: {}, pendingApprovals: {}, pendingReminder: null };
}

const goalRuntimeStateSchema = z
  .object({
    goalId: z.string(),
    objective: z.string(),
    state: z.enum(GOAL_STATES),
    turnCount: z.number(),
    blockedStreak: z.number(),
    pendingBlockerSignature: z.string().optional(),
    terminalKind: z.enum(['technical', 'business']).optional(),
    terminalReason: z.string().optional(),
    missionId: z.string().optional(),
    createdAt: z.string(),
    updatedAt: z.string(),
    budget: z
      .object({
        tokenBudget: z.number().optional(),
        turnBudget: z.number().optional(),
        wallClockBudgetMs: z.number().optional(),
      })
      .optional(),
    budgetStats: z
      .object({
        tokensUsed: z.number(),
        turnsUsed: z.number(),
        wallClockMsUsed: z.number(),
      })
      .optional(),
  })
  .strict();

const delegationLedgerEntrySchema = z
  .object({
    delegationId: z.string(),
    owner: z.string(),
    instruction: z.string(),
    status: z.enum(['started', 'completed', 'failed']),
    background: z.boolean().optional(),
    createdAt: z.string(),
    completedAt: z.string().optional(),
    resultSummary: z.string().optional(),
    error: z.string().optional(),
    missionId: z.string().optional(),
  })
  .strict();

const pendingApprovalRefSchema = z
  .object({
    requestId: z.string(),
    channel: z.string().optional(),
    requestedBy: z.string().optional(),
  })
  .strict();

/** The one-shot fork reminder, mirroring KD-01's {@link GOAL_CANCEL_SYSTEM_REMINDER}. */
export const MISSION_FORK_SYSTEM_REMINDER =
  'This worker was forked to a new mission. Ignore all earlier active-goal and continuation ' +
  'reminders inherited from the parent; only goals stated for THIS mission apply.';

/** Shared kernel holding the worker model + ops. */
export const workerStateKernel = new EventSourcingKernel();

const workerModel = workerStateKernel.defineModel<WorkerRestorableState>(
  'worker',
  initialWorkerState
);

/** op names as constants so callers/tests never guess the strings. */
export const WORKER_STATE_OPS = {
  goalUpsert: 'goal.upsert',
  goalCancel: 'goal.cancel',
  delegationUpsert: 'delegation.upsert',
  approvalRequest: 'approval.request',
  approvalResolve: 'approval.resolve',
  missionFork: 'mission.fork',
  reminderConsume: 'reminder.consume',
} as const;

workerStateKernel.defineOp(WORKER_STATE_OPS.goalUpsert, {
  model: workerModel,
  schema: goalRuntimeStateSchema,
  apply: (state, goal) => ({ ...state, goal }),
});

workerStateKernel.defineOp(WORKER_STATE_OPS.goalCancel, {
  model: workerModel,
  schema: z.object({ goalId: z.string(), reminderId: z.string() }).strict(),
  apply: (state, payload) => ({
    ...state,
    goal: null,
    pendingReminder: {
      id: payload.reminderId,
      text: GOAL_CANCEL_SYSTEM_REMINDER,
      origin: 'goal_cancel' as const,
    },
  }),
});

workerStateKernel.defineOp(WORKER_STATE_OPS.delegationUpsert, {
  model: workerModel,
  schema: delegationLedgerEntrySchema,
  apply: (state, entry) => ({
    ...state,
    delegations: { ...state.delegations, [entry.delegationId]: entry },
  }),
});

workerStateKernel.defineOp(WORKER_STATE_OPS.approvalRequest, {
  model: workerModel,
  schema: pendingApprovalRefSchema,
  apply: (state, ref) => ({
    ...state,
    pendingApprovals: { ...state.pendingApprovals, [ref.requestId]: ref },
  }),
});

workerStateKernel.defineOp(WORKER_STATE_OPS.approvalResolve, {
  model: workerModel,
  schema: z.object({ requestId: z.string() }).strict(),
  apply: (state, payload) => {
    if (!(payload.requestId in state.pendingApprovals)) return state; // no-op => same reference
    const next = { ...state.pendingApprovals };
    delete next[payload.requestId];
    return { ...state, pendingApprovals: next };
  },
});

workerStateKernel.defineOp(WORKER_STATE_OPS.missionFork, {
  model: workerModel,
  schema: z.object({ reminderId: z.string(), forkedFrom: z.string().optional() }).strict(),
  apply: (state, payload) => ({
    ...state,
    pendingReminder: {
      id: payload.reminderId,
      text: MISSION_FORK_SYSTEM_REMINDER,
      origin: 'mission_fork' as const,
    },
  }),
});

workerStateKernel.defineOp(WORKER_STATE_OPS.reminderConsume, {
  model: workerModel,
  schema: z.object({ reminderId: z.string() }).strict(),
  apply: (state, payload) => {
    // Idempotent: consuming a reminder that isn't pending is a no-op and MUST
    // return the same reference (proves replay never re-fires a consumed one).
    if (!state.pendingReminder || state.pendingReminder.id !== payload.reminderId) return state;
    return { ...state, pendingReminder: null };
  },
});

// ---------------------------------------------------------------------------
// Derived index (CQRS): goal/delegation summary lookup
// ---------------------------------------------------------------------------

export interface GoalDelegationSummary {
  goalId: string | null;
  goalState: GoalState | null;
  delegationCount: number;
  /** Delegations still `started` — the "active background tasks" count. */
  activeDelegationCount: number;
  pendingApprovalCount: number;
  hasPendingReminder: boolean;
  /** Journal seq this summary was projected from (staleness check aid). */
  projectedThroughSeq: number;
}

const goalDelegationSummarySchema = z
  .object({
    goalId: z.string().nullable(),
    goalState: z.enum(GOAL_STATES).nullable(),
    delegationCount: z.number().int().nonnegative(),
    activeDelegationCount: z.number().int().nonnegative(),
    pendingApprovalCount: z.number().int().nonnegative(),
    hasPendingReminder: z.boolean(),
    projectedThroughSeq: z.number().int(),
  })
  .strict();

function summarize(
  state: WorkerRestorableState,
  projectedThroughSeq: number
): GoalDelegationSummary {
  const delegations = Object.values(state.delegations);
  return {
    goalId: state.goal?.goalId ?? null,
    goalState: state.goal?.state ?? null,
    delegationCount: delegations.length,
    activeDelegationCount: delegations.filter((d) => d.status === 'started').length,
    pendingApprovalCount: Object.keys(state.pendingApprovals).length,
    hasPendingReminder: state.pendingReminder !== null,
    projectedThroughSeq,
  };
}

// ---------------------------------------------------------------------------
// WorkerStateJournal: authoritative append log + restore + self-healing index
// ---------------------------------------------------------------------------

export interface WorkerStateJournalOptions {
  /** Authoritative append-only JSONL journal (resolved through secure-io). */
  journalPath: string;
  /** Derived summary index; defaults to `<journalPath>.index.json`. */
  indexPath?: string;
  now?: () => string;
}

export interface OnDidRestoreHook {
  (state: WorkerRestorableState): void;
}

interface ReadResult {
  events: JournalEventEnvelope[];
  maxSeq: number;
}

export class WorkerStateJournal {
  private readonly kernel = workerStateKernel;
  private readonly journalPath: string;
  private readonly indexPath: string;
  private readonly now: () => string;
  private readonly restoreHooks: Array<{ order: number; index: number; hook: OnDidRestoreHook }> =
    [];
  private hookCounter = 0;
  private seqLoaded = false;
  private seq = 0;

  constructor(options: WorkerStateJournalOptions) {
    this.journalPath = pathResolver.rootResolve(options.journalPath);
    this.indexPath = options.indexPath
      ? pathResolver.rootResolve(options.indexPath)
      : `${this.journalPath}.index.json`;
    this.now = options.now ?? (() => new Date().toISOString());
  }

  /** Register an ordered post-restore hook (lower `order` runs first). */
  onDidRestore(hook: OnDidRestoreHook, order = 0): () => void {
    const entry = { order, index: this.hookCounter++, hook };
    this.restoreHooks.push(entry);
    return () => {
      const at = this.restoreHooks.indexOf(entry);
      if (at >= 0) this.restoreHooks.splice(at, 1);
    };
  }

  // -- live append (side effects allowed; not during restore) ----------------

  /**
   * Validate a payload against its op contract, assign seq/ts from the live
   * service, and append the record to the authoritative journal. Returns the
   * written envelope. Appending is the authoritative act only — reminder
   * *delivery* is a separate, guarded step ({@link deliverOneShotReminder}).
   */
  append(opName: string, payload: unknown): JournalEventEnvelope {
    assertNotDuringRestore('WorkerStateJournal.append');
    const validated = this.kernel.validatePayload(opName, payload);
    this.ensureSeqLoaded();
    const envelope: JournalEventEnvelope = journalEventEnvelopeSchema.parse({
      v: CURRENT_JOURNAL_VERSION,
      seq: this.seq++,
      ts: this.now(),
      op: opName,
      payload: validated,
    });
    this.ensureDir(this.journalPath);
    safeAppendFileSync(this.journalPath, `${JSON.stringify(envelope)}\n`);
    return envelope;
  }

  recordGoal(goal: GoalRuntimeState): JournalEventEnvelope {
    return this.append(WORKER_STATE_OPS.goalUpsert, goal);
  }

  cancelGoal(goalId: string, reminderId: string): JournalEventEnvelope {
    return this.append(WORKER_STATE_OPS.goalCancel, { goalId, reminderId });
  }

  recordDelegation(entry: DelegationLedgerEntry): JournalEventEnvelope {
    return this.append(WORKER_STATE_OPS.delegationUpsert, entry);
  }

  requestApproval(ref: PendingApprovalRef): JournalEventEnvelope {
    return this.append(WORKER_STATE_OPS.approvalRequest, ref);
  }

  resolveApproval(requestId: string): JournalEventEnvelope {
    return this.append(WORKER_STATE_OPS.approvalResolve, { requestId });
  }

  forkMission(reminderId: string, forkedFrom?: string): JournalEventEnvelope {
    return this.append(WORKER_STATE_OPS.missionFork, {
      reminderId,
      ...(forkedFrom ? { forkedFrom } : {}),
    });
  }

  /** Record that the current pending reminder was delivered (so replay won't re-fire it). */
  consumeReminder(reminderId: string): JournalEventEnvelope {
    return this.append(WORKER_STATE_OPS.reminderConsume, { reminderId });
  }

  // -- restore (silent, pure) ------------------------------------------------

  /**
   * Reconstruct the worker state purely from the journal:
   * validate → migrate → silent replay → demote active goal → ordered hooks.
   *
   * The whole body runs inside {@link runInRestoreMode}, so any emission seam
   * (notification / LLM / tool) invoked by a hook throws instead of firing.
   * After restore, `this.seq` continues from the journal's max seq, so a
   * live append picks up exactly where the dead process left off.
   */
  restore(): WorkerRestorableState {
    const read = this.readJournal();
    this.seq = read.maxSeq + 1;
    this.seqLoaded = true;
    return runInRestoreMode(() => {
      const states = this.kernel.project(read.events);
      let state = (states.get('worker') as WorkerRestorableState) ?? initialWorkerState();
      // KD-01: a persisted `active` goal means the prior process died mid-turn —
      // demote to `paused` so it never self-advances until an explicit resume.
      if (state.goal && state.goal.state === 'active') {
        state = { ...state, goal: demoteActiveOnResume(state.goal, this.now) };
      }
      const ordered = [...this.restoreHooks].sort((a, b) => a.order - b.order || a.index - b.index);
      for (const { hook } of ordered) {
        hook(state);
      }
      return state;
    });
  }

  // -- derived index (CQRS, self-healing) ------------------------------------

  /**
   * Return the goal/delegation summary. Reads the derived index file; if it is
   * missing or corrupt, wipes it and reprojects from the authoritative journal
   * (self-healing) before returning.
   */
  summary(): GoalDelegationSummary {
    const loaded = this.loadIndex();
    if (loaded) return loaded;
    return this.rebuildSummary();
  }

  /** Force a reprojection of the derived index from the journal. */
  rebuildSummary(): GoalDelegationSummary {
    const read = this.readJournal();
    const state = runInRestoreMode(() => {
      const states = this.kernel.project(read.events);
      return (states.get('worker') as WorkerRestorableState) ?? initialWorkerState();
    });
    const summary = summarize(state, read.maxSeq);
    try {
      this.ensureDir(this.indexPath);
      safeWriteFile(this.indexPath, `${JSON.stringify(summary, null, 2)}\n`);
    } catch (error) {
      // The index is derived and rebuildable; never fail on a write hiccup.
      logger.warn(
        `[worker-state-journal] derived index write failed (non-fatal): ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
    return summary;
  }

  private loadIndex(): GoalDelegationSummary | null {
    if (!safeExistsSync(this.indexPath)) return null;
    try {
      const raw = String(safeReadFile(this.indexPath, { encoding: 'utf-8' }));
      // Reconstruct explicitly: zod v4 infers `.nullable()` keys as optional,
      // so round-trip through the hand-written contract shape instead of the
      // schema's looser inferred type.
      const parsed = goalDelegationSummarySchema.parse(JSON.parse(raw));
      return {
        goalId: parsed.goalId ?? null,
        goalState: parsed.goalState ?? null,
        delegationCount: parsed.delegationCount,
        activeDelegationCount: parsed.activeDelegationCount,
        pendingApprovalCount: parsed.pendingApprovalCount,
        hasPendingReminder: parsed.hasPendingReminder,
        projectedThroughSeq: parsed.projectedThroughSeq,
      };
    } catch {
      // Corrupt derived index: wipe so the next reader reprojects cleanly.
      try {
        safeRmSync(this.indexPath, { force: true });
      } catch {
        /* best-effort */
      }
      return null;
    }
  }

  // -- internals -------------------------------------------------------------

  private ensureSeqLoaded(): void {
    if (this.seqLoaded) return;
    this.seq = this.readJournal().maxSeq + 1;
    this.seqLoaded = true;
  }

  private readJournal(): ReadResult {
    if (!safeExistsSync(this.journalPath)) return { events: [], maxSeq: -1 };
    const raw = String(safeReadFile(this.journalPath, { encoding: 'utf-8' }));
    const events: JournalEventEnvelope[] = [];
    let maxSeq = -1;
    for (const line of raw.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try {
        const parsed = journalEventEnvelopeSchema.parse(JSON.parse(trimmed));
        const migrated = migrateEnvelope(parsed);
        events.push(migrated);
        if (migrated.seq > maxSeq) maxSeq = migrated.seq;
      } catch {
        // A torn/corrupt/forward line must not poison replay of the rest.
      }
    }
    return { events, maxSeq };
  }

  private ensureDir(filePath: string): void {
    const dir = filePath.replace(/[/\\][^/\\]+$/, '');
    if (dir && dir !== filePath && !safeExistsSync(dir)) {
      safeMkdir(dir, { recursive: true });
    }
  }
}
